-- Generated by tools/build_wave1_evolution_block_67.py; bounded block 15.
return {
  schema="kasc.wave1-evolution-block/v1",
  sourceCommit="d4f9a4af58ade123fbc0558f68b1c69daa97d9e4",
  edges={
    {fromDex=664,toDex=665,level=9,sourceRow=342}, -- scatterbug -> spewpa
    {fromDex=665,toDex=666,level=12,sourceRow=341}, -- spewpa -> vivillon
    {fromDex=704,toDex=705,level=40,sourceRow=340}, -- goomy -> sliggoo
    {fromDex=789,toDex=790,level=43,sourceRow=402}, -- cosmog -> cosmoem
  },
}
