-- Generated by tools/build_wave1_evolution_block_67.py; bounded block 2.
return {
  schema="kasc.wave1-evolution-block/v1",
  sourceCommit="d4f9a4af58ade123fbc0558f68b1c69daa97d9e4",
  edges={
    {fromDex=396,toDex=397,level=14,sourceRow=198}, -- starly -> staravia
    {fromDex=397,toDex=398,level=34,sourceRow=199}, -- staravia -> staraptor
    {fromDex=399,toDex=400,level=15,sourceRow=200}, -- bidoof -> bibarel
    {fromDex=401,toDex=402,level=10,sourceRow=201}, -- kricketot -> kricketune
    {fromDex=408,toDex=409,level=30,sourceRow=205}, -- cranidos -> rampardos
    {fromDex=410,toDex=411,level=30,sourceRow=206}, -- shieldon -> bastiodon
    {fromDex=418,toDex=419,level=26,sourceRow=210}, -- buizel -> floatzel
    {fromDex=420,toDex=421,level=25,sourceRow=211}, -- cherubi -> cherrim
    {fromDex=422,toDex=423,level=30,sourceRow=212}, -- shellos -> gastrodon
    {fromDex=425,toDex=426,level=28,sourceRow=214}, -- drifloon -> drifblim
    {fromDex=431,toDex=432,level=38,sourceRow=218}, -- glameow -> purugly
    {fromDex=434,toDex=435,level=34,sourceRow=219}, -- stunky -> skuntank
    {fromDex=436,toDex=437,level=33,sourceRow=220}, -- bronzor -> bronzong
    {fromDex=449,toDex=450,level=34,sourceRow=224}, -- hippopotas -> hippowdon
    {fromDex=451,toDex=452,level=40,sourceRow=225}, -- skorupi -> drapion
    {fromDex=453,toDex=454,level=37,sourceRow=226}, -- croagunk -> toxicroak
    {fromDex=456,toDex=457,level=31,sourceRow=227}, -- finneon -> lumineon
    {fromDex=459,toDex=460,level=40,sourceRow=228}, -- snover -> abomasnow
  },
}
