-- Generated by tools/build_wave1_evolution_block_67.py; bounded block 19.
return {
  schema="kasc.wave1-evolution-block/v1",
  sourceCommit="d4f9a4af58ade123fbc0558f68b1c69daa97d9e4",
  edges={
    {fromDex=427,toDex=428,method="KA_BACKEND_FRIENDSHIP",friendship=true,sourceRow=215}, -- buneary -> lopunny
    {fromDex=527,toDex=528,method="KA_BACKEND_FRIENDSHIP",friendship=true,sourceRow=266}, -- woobat -> swoobat
    {fromDex=541,toDex=542,method="KA_BACKEND_FRIENDSHIP",friendship=true,sourceRow=273}, -- swadloon -> leavanny
    {fromDex=772,toDex=773,method="KA_BACKEND_FRIENDSHIP",friendship=true,sourceRow=399}, -- type-null -> silvally
    {fromDex=872,toDex=873,method="KA_BACKEND_FRIENDSHIP_NIGHT",friendship=true,timeOfDay="night",sourceRow=442}, -- snom -> frosmoth
  },
}
