-- Generated by tools/build_wave1_evolution_block_67.py; bounded block 9.
return {
  schema="kasc.wave1-evolution-block/v1",
  sourceCommit="d4f9a4af58ade123fbc0558f68b1c69daa97d9e4",
  edges={
    {fromDex=438,toDex=185,method="KA_BABY_MIMIC",move="MIMIC",sourceRow=103}, -- bonsly -> sudowoodo
    {fromDex=439,toDex=122,method="KA_BABY_MIMIC",move="MIMIC",sourceRow=71}, -- mime-jr -> mr-mime
    {fromDex=458,toDex=226,method="KA_BABY_REMORAID",partySpecies="REMORAID",sourceRow=121}, -- mantyke -> mantine
  },
}
