-- Generated by tools/build_wave1_evolution_block_67.py; bounded block 21.
return {
  schema="kasc.wave1-evolution-block/v1",
  sourceCommit="d4f9a4af58ade123fbc0558f68b1c69daa97d9e4",
  edges={
    {fromDex=415,toDex=416,level=21,method="KA_BACKEND_LEVEL_FEMALE",gender="FEMALE",sourceRow=209}, -- combee -> vespiquen
    {fromDex=757,toDex=758,level=33,method="KA_BACKEND_LEVEL_FEMALE",gender="FEMALE",sourceRow=393}, -- salandit -> salazzle
  },
}
