-- Generated by tools/build_wave1_evolution_block_67.py; bounded block 7.
return {
  schema="kasc.wave1-evolution-block/v1",
  sourceCommit="d4f9a4af58ade123fbc0558f68b1c69daa97d9e4",
  edges={
    {fromDex=511,toDex=512,item="LEAF_STONE",sourceRow=257}, -- pansage -> simisage
    {fromDex=513,toDex=514,item="FIRE_STONE",sourceRow=258}, -- pansear -> simisear
    {fromDex=515,toDex=516,item="WATER_STONE",sourceRow=259}, -- panpour -> simipour
    {fromDex=517,toDex=518,item="MOON_STONE",sourceRow=260}, -- munna -> musharna
    {fromDex=546,toDex=547,item="SUN_STONE",sourceRow=276}, -- cottonee -> whimsicott
    {fromDex=572,toDex=573,item="SHINY_STONE",sourceRow=288}, -- minccino -> cinccino
    {fromDex=602,toDex=603,level=39,sourceRow=304}, -- tynamo -> eelektrik
    {fromDex=603,toDex=604,item="THUNDER_STONE",sourceRow=305}, -- eelektrik -> eelektross
    {fromDex=607,toDex=608,level=41,sourceRow=307}, -- litwick -> lampent
    {fromDex=608,toDex=609,item="DUSK_STONE",sourceRow=308}, -- lampent -> chandelure
    {fromDex=679,toDex=680,level=35,sourceRow=339}, -- honedge -> doublade
    {fromDex=680,toDex=681,item="DUSK_STONE",sourceRow=348}, -- doublade -> aegislash
    {fromDex=694,toDex=695,item="SUN_STONE",sourceRow=355}, -- helioptile -> heliolisk
    {fromDex=736,toDex=737,level=20,sourceRow=382}, -- grubbin -> charjabug
    {fromDex=737,toDex=738,item="THUNDER_STONE",sourceRow=410}, -- charjabug -> vikavolt
    {fromDex=938,toDex=939,item="THUNDER_STONE",sourceRow=487}, -- tadbulb -> bellibolt
    {fromDex=951,toDex=952,item="FIRE_STONE",sourceRow=493}, -- capsakid -> scovillain
  },
}
