-- Generated by tools/build_wave1_evolution_block_67.py; bounded block 25.
return {
  schema="kasc.wave1-evolution-block/v1",
  sourceCommit="d4f9a4af58ade123fbc0558f68b1c69daa97d9e4",
  edges={
    {fromDex=265,toDex=266,level=7,method="KA_HOENN_WURMPLE_SILCOON",sourceRow=138}, -- wurmple -> silcoon
    {fromDex=265,toDex=268,level=7,method="KA_HOENN_WURMPLE_CASCOON",sourceRow=140}, -- wurmple -> cascoon
  },
}
