-- Generated by tools/build_wave1_evolution_block_67.py; bounded block 8.
return {
  schema="kasc.wave1-evolution-block/v1",
  sourceCommit="d4f9a4af58ade123fbc0558f68b1c69daa97d9e4",
  edges={
    {fromDex=252,toDex=253,level=16,sourceRow=130}, -- treecko -> grovyle
    {fromDex=253,toDex=254,level=36,sourceRow=131}, -- grovyle -> sceptile
    {fromDex=255,toDex=256,level=16,sourceRow=132}, -- torchic -> combusken
    {fromDex=256,toDex=257,level=36,sourceRow=133}, -- combusken -> blaziken
    {fromDex=258,toDex=259,level=16,sourceRow=134}, -- mudkip -> marshtomp
    {fromDex=259,toDex=260,level=36,sourceRow=135}, -- marshtomp -> swampert
    {fromDex=261,toDex=262,level=18,sourceRow=136}, -- poochyena -> mightyena
    {fromDex=263,toDex=264,level=20,sourceRow=137}, -- zigzagoon -> linoone
    {fromDex=266,toDex=267,level=10,sourceRow=139}, -- silcoon -> beautifly
    {fromDex=268,toDex=269,level=10,sourceRow=141}, -- cascoon -> dustox
    {fromDex=270,toDex=271,level=14,sourceRow=142}, -- lotad -> lombre
    {fromDex=273,toDex=274,level=14,sourceRow=144}, -- seedot -> nuzleaf
    {fromDex=276,toDex=277,level=22,sourceRow=146}, -- taillow -> swellow
    {fromDex=278,toDex=279,level=25,sourceRow=147}, -- wingull -> pelipper
    {fromDex=280,toDex=281,level=20,sourceRow=148}, -- ralts -> kirlia
    {fromDex=281,toDex=282,level=30,sourceRow=149}, -- kirlia -> gardevoir
    {fromDex=283,toDex=284,level=22,sourceRow=150}, -- surskit -> masquerain
    {fromDex=285,toDex=286,level=23,sourceRow=151}, -- shroomish -> breloom
    {fromDex=287,toDex=288,level=18,sourceRow=152}, -- slakoth -> vigoroth
    {fromDex=288,toDex=289,level=36,sourceRow=153}, -- vigoroth -> slaking
    {fromDex=290,toDex=291,level=20,sourceRow=154}, -- nincada -> ninjask
    {fromDex=293,toDex=294,level=20,sourceRow=156}, -- whismur -> loudred
    {fromDex=294,toDex=295,level=40,sourceRow=157}, -- loudred -> exploud
    {fromDex=296,toDex=297,level=24,sourceRow=158}, -- makuhita -> hariyama
    {fromDex=307,toDex=308,level=37,sourceRow=162}, -- meditite -> medicham
    {fromDex=309,toDex=310,level=26,sourceRow=163}, -- electrike -> manectric
    {fromDex=316,toDex=317,level=26,sourceRow=165}, -- gulpin -> swalot
    {fromDex=318,toDex=319,level=30,sourceRow=166}, -- carvanha -> sharpedo
    {fromDex=320,toDex=321,level=40,sourceRow=167}, -- wailmer -> wailord
    {fromDex=322,toDex=323,level=33,sourceRow=168}, -- numel -> camerupt
    {fromDex=325,toDex=326,level=32,sourceRow=169}, -- spoink -> grumpig
    {fromDex=328,toDex=329,level=35,sourceRow=170}, -- trapinch -> vibrava
    {fromDex=329,toDex=330,level=45,sourceRow=171}, -- vibrava -> flygon
    {fromDex=331,toDex=332,level=32,sourceRow=172}, -- cacnea -> cacturne
    {fromDex=333,toDex=334,level=35,sourceRow=173}, -- swablu -> altaria
    {fromDex=339,toDex=340,level=30,sourceRow=174}, -- barboach -> whiscash
    {fromDex=341,toDex=342,level=30,sourceRow=175}, -- corphish -> crawdaunt
    {fromDex=343,toDex=344,level=36,sourceRow=176}, -- baltoy -> claydol
    {fromDex=345,toDex=346,level=40,sourceRow=177}, -- lileep -> cradily
    {fromDex=347,toDex=348,level=40,sourceRow=178}, -- anorith -> armaldo
    {fromDex=353,toDex=354,level=37,sourceRow=180}, -- shuppet -> banette
    {fromDex=355,toDex=356,level=37,sourceRow=181}, -- duskull -> dusclops
    {fromDex=360,toDex=202,level=15,sourceRow=112}, -- wynaut -> wobbuffet
    {fromDex=361,toDex=362,level=42,sourceRow=183}, -- snorunt -> glalie
    {fromDex=363,toDex=364,level=32,sourceRow=184}, -- spheal -> sealeo
    {fromDex=364,toDex=365,level=44,sourceRow=185}, -- sealeo -> walrein
    {fromDex=387,toDex=388,level=18,sourceRow=192}, -- turtwig -> grotle
    {fromDex=388,toDex=389,level=32,sourceRow=193}, -- grotle -> torterra
    {fromDex=390,toDex=391,level=14,sourceRow=194}, -- chimchar -> monferno
    {fromDex=391,toDex=392,level=36,sourceRow=195}, -- monferno -> infernape
    {fromDex=393,toDex=394,level=16,sourceRow=196}, -- piplup -> prinplup
    {fromDex=394,toDex=395,level=36,sourceRow=197}, -- prinplup -> empoleon
    {fromDex=495,toDex=496,level=17,sourceRow=247}, -- snivy -> servine
    {fromDex=496,toDex=497,level=36,sourceRow=248}, -- servine -> serperior
    {fromDex=498,toDex=499,level=17,sourceRow=249}, -- tepig -> pignite
    {fromDex=499,toDex=500,level=36,sourceRow=250}, -- pignite -> emboar
    {fromDex=501,toDex=502,level=17,sourceRow=251}, -- oshawott -> dewott
    {fromDex=502,toDex=503,level=36,sourceRow=252}, -- dewott -> samurott
    {fromDex=650,toDex=651,level=16,sourceRow=334}, -- chespin -> quilladin
    {fromDex=651,toDex=652,level=36,sourceRow=336}, -- quilladin -> chesnaught
    {fromDex=653,toDex=654,level=16,sourceRow=331}, -- fennekin -> braixen
    {fromDex=654,toDex=655,level=36,sourceRow=333}, -- braixen -> delphox
    {fromDex=656,toDex=657,level=16,sourceRow=337}, -- froakie -> frogadier
    {fromDex=657,toDex=658,level=36,sourceRow=338}, -- frogadier -> greninja
    {fromDex=722,toDex=723,level=17,sourceRow=373}, -- rowlet -> dartrix
    {fromDex=723,toDex=724,level=34,sourceRow=374}, -- dartrix -> decidueye
    {fromDex=725,toDex=726,level=17,sourceRow=375}, -- litten -> torracat
    {fromDex=726,toDex=727,level=34,sourceRow=376}, -- torracat -> incineroar
    {fromDex=728,toDex=729,level=17,sourceRow=377}, -- popplio -> brionne
    {fromDex=729,toDex=730,level=34,sourceRow=378}, -- brionne -> primarina
  },
}
