-- Generated by tools/build_wave1_evolution_block_67.py; bounded block 13.
return {
  schema="kasc.wave1-evolution-block/v1",
  sourceCommit="d4f9a4af58ade123fbc0558f68b1c69daa97d9e4",
  edges={
    {fromDex=761,toDex=762,level=18,sourceRow=395}, -- bounsweet -> steenee
    {fromDex=762,toDex=763,method="KA_BACKEND_KNOWN_MOVE",move="STOMP",sourceRow=396}, -- steenee -> tsareena
    {fromDex=803,toDex=804,method="KA_BACKEND_KNOWN_MOVE",move="DRAGON_PULSE",sourceRow=405}, -- poipole -> naganadel
    {fromDex=852,toDex=853,method="KA_BACKEND_KNOWN_MOVE",move="TAUNT",sourceRow=435}, -- clobbopus -> grapploct
    {fromDex=1011,toDex=1019,method="KA_BACKEND_KNOWN_MOVE",move="DRAGON_CHEER",sourceRow=543}, -- dipplin -> hydrapple
  },
}
