-- Generated by tools/build_wave1_evolution_block_67.py; bounded block 4.
return {
  schema="kasc.wave1-evolution-block/v1",
  sourceCommit="d4f9a4af58ade123fbc0558f68b1c69daa97d9e4",
  edges={
    {fromDex=659,toDex=660,level=20,sourceRow=345}, -- bunnelby -> diggersby
    {fromDex=661,toDex=662,level=17,sourceRow=328}, -- fletchling -> fletchinder
    {fromDex=662,toDex=663,level=35,sourceRow=330}, -- fletchinder -> talonflame
    {fromDex=672,toDex=673,level=32,sourceRow=357}, -- skiddo -> gogoat
    {fromDex=688,toDex=689,level=39,sourceRow=343}, -- binacle -> barbaracle
    {fromDex=690,toDex=691,level=48,sourceRow=351}, -- skrelp -> dragalge
    {fromDex=692,toDex=693,level=37,sourceRow=335}, -- clauncher -> clawitzer
    {fromDex=714,toDex=715,level=48,sourceRow=359}, -- noibat -> noivern
    {fromDex=731,toDex=732,level=14,sourceRow=379}, -- pikipek -> trumbeak
    {fromDex=732,toDex=733,level=28,sourceRow=380}, -- trumbeak -> toucannon
    {fromDex=742,toDex=743,level=25,sourceRow=385}, -- cutiefly -> ribombee
    {fromDex=747,toDex=748,level=38,sourceRow=388}, -- mareanie -> toxapex
    {fromDex=749,toDex=750,level=30,sourceRow=389}, -- mudbray -> mudsdale
    {fromDex=751,toDex=752,level=22,sourceRow=390}, -- dewpider -> araquanid
    {fromDex=755,toDex=756,level=24,sourceRow=392}, -- morelull -> shiinotic
    {fromDex=759,toDex=760,level=27,sourceRow=394}, -- stufful -> bewear
    {fromDex=767,toDex=768,level=30,sourceRow=397}, -- wimpod -> golisopod
    {fromDex=769,toDex=770,level=42,sourceRow=398}, -- sandygast -> palossand
    {fromDex=782,toDex=783,level=35,sourceRow=400}, -- jangmo-o -> hakamo-o
    {fromDex=783,toDex=784,level=45,sourceRow=401}, -- hakamo-o -> kommo-o
  },
}
