-- Generated by tools/build_wave1_evolution_block_67.py; bounded block 28.
return {
  schema="kasc.wave1-evolution-block/v1",
  sourceCommit="d4f9a4af58ade123fbc0558f68b1c69daa97d9e4",
  edges={
    {fromDex=281,toDex=475,item="DAWN_STONE",gender="MALE",sourceRow=243}, -- kirlia -> gallade
    {fromDex=361,toDex=478,item="DAWN_STONE",gender="FEMALE",sourceRow=246}, -- snorunt -> froslass
  },
}
