-- Generated by tools/build_wave1_evolution_block_67.py; bounded block 16.
return {
  schema="kasc.wave1-evolution-block/v1",
  sourceCommit="d4f9a4af58ade123fbc0558f68b1c69daa97d9e4",
  edges={
    {fromDex=840,toDex=841,item="TART_APPLE",sourceRow=429}, -- applin -> flapple
    {fromDex=840,toDex=842,item="SWEET_APPLE",sourceRow=430}, -- applin -> appletun
    {fromDex=840,toDex=1011,item="SYRUPY_APPLE",sourceRow=541}, -- applin -> dipplin
    {fromDex=974,toDex=975,item="ICE_STONE",sourceRow=503}, -- cetoddle -> cetitan
  },
}
