-- Generated by tools/build_wave1_evolution_block_67.py; bounded block 1.
return {
  schema="kasc.wave1-evolution-block/v1",
  sourceCommit="d4f9a4af58ade123fbc0558f68b1c69daa97d9e4",
  edges={
    {fromDex=304,toDex=305,level=32,sourceRow=160}, -- aron -> lairon
    {fromDex=305,toDex=306,level=42,sourceRow=161}, -- lairon -> aggron
    {fromDex=371,toDex=372,level=30,sourceRow=188}, -- bagon -> shelgon
    {fromDex=372,toDex=373,level=50,sourceRow=189}, -- shelgon -> salamence
    {fromDex=374,toDex=375,level=20,sourceRow=190}, -- beldum -> metang
    {fromDex=375,toDex=376,level=45,sourceRow=191}, -- metang -> metagross
    {fromDex=403,toDex=404,level=15,sourceRow=202}, -- shinx -> luxio
    {fromDex=404,toDex=405,level=30,sourceRow=203}, -- luxio -> luxray
    {fromDex=443,toDex=444,level=24,sourceRow=221}, -- gible -> gabite
    {fromDex=444,toDex=445,level=48,sourceRow=222}, -- gabite -> garchomp
    {fromDex=577,toDex=578,level=32,sourceRow=291}, -- solosis -> duosion
    {fromDex=578,toDex=579,level=41,sourceRow=292}, -- duosion -> reuniclus
    {fromDex=610,toDex=611,level=38,sourceRow=309}, -- axew -> fraxure
    {fromDex=611,toDex=612,level=48,sourceRow=310}, -- fraxure -> haxorus
    {fromDex=633,toDex=634,level=50,sourceRow=318}, -- deino -> zweilous
    {fromDex=634,toDex=635,level=64,sourceRow=319}, -- zweilous -> hydreigon
    {fromDex=885,toDex=886,level=50,sourceRow=444}, -- dreepy -> drakloak
    {fromDex=886,toDex=887,level=60,sourceRow=445}, -- drakloak -> dragapult
    {fromDex=996,toDex=997,level=35,sourceRow=509}, -- frigibax -> arctibax
    {fromDex=997,toDex=998,level=54,sourceRow=510}, -- arctibax -> baxcalibur
  },
}
