-- Generated by tools/build_wave1_evolution_block_67.py; bounded block 22.
return {
  schema="kasc.wave1-evolution-block/v1",
  sourceCommit="d4f9a4af58ade123fbc0558f68b1c69daa97d9e4",
  edges={
    {fromDex=674,toDex=675,level=32,method="KA_BACKEND_LEVEL_DARK_PARTY",partyType="DARK",sourceRow=349}, -- pancham -> pangoro
  },
}
