-- Generated by tools/build_wave1_evolution_block_67.py; bounded block 27.
return {
  schema="kasc.wave1-evolution-block/v1",
  sourceCommit="d4f9a4af58ade123fbc0558f68b1c69daa97d9e4",
  edges={
    {fromDex=349,toDex=350,item="PRISM_SCALE",sourceRow=321}, -- feebas -> milotic
    {fromDex=366,toDex=367,item="DEEP_SEA_TOOTH",sourceRow=186}, -- clamperl -> huntail
    {fromDex=366,toDex=368,item="DEEP_SEA_SCALE",sourceRow=187}, -- clamperl -> gorebyss
  },
}
