-- Generated by tools/build_wave1_evolution_block_67.py; bounded block 17.
return {
  schema="kasc.wave1-evolution-block/v1",
  sourceCommit="d4f9a4af58ade123fbc0558f68b1c69daa97d9e4",
  edges={
    {fromDex=935,toDex=936,item="AUSPICIOUS_ARMOR",sourceRow=485}, -- charcadet -> armarouge
    {fromDex=935,toDex=937,item="MALICIOUS_ARMOR",sourceRow=486}, -- charcadet -> ceruledge
  },
}
