-- Generated by tools/build_wave1_evolution_block_67.py; bounded block 6.
return {
  schema="kasc.wave1-evolution-block/v1",
  sourceCommit="d4f9a4af58ade123fbc0558f68b1c69daa97d9e4",
  edges={
    {fromDex=906,toDex=907,level=16,sourceRow=468}, -- sprigatito -> floragato
    {fromDex=907,toDex=908,level=36,sourceRow=469}, -- floragato -> meowscarada
    {fromDex=909,toDex=910,level=16,sourceRow=470}, -- fuecoco -> crocalor
    {fromDex=910,toDex=911,level=36,sourceRow=471}, -- crocalor -> skeledirge
    {fromDex=912,toDex=913,level=16,sourceRow=472}, -- quaxly -> quaxwell
    {fromDex=913,toDex=914,level=36,sourceRow=473}, -- quaxwell -> quaquaval
    {fromDex=917,toDex=918,level=15,sourceRow=475}, -- tarountula -> spidops
    {fromDex=919,toDex=920,level=24,sourceRow=476}, -- nymble -> lokix
    {fromDex=926,toDex=927,level=26,sourceRow=480}, -- fidough -> dachsbun
    {fromDex=928,toDex=929,level=25,sourceRow=481}, -- smoliv -> dolliv
    {fromDex=929,toDex=930,level=35,sourceRow=482}, -- dolliv -> arboliva
    {fromDex=932,toDex=933,level=24,sourceRow=483}, -- nacli -> naclstack
    {fromDex=933,toDex=934,level=38,sourceRow=484}, -- naclstack -> garganacl
    {fromDex=940,toDex=941,level=25,sourceRow=488}, -- wattrel -> kilowattrel
    {fromDex=942,toDex=943,level=30,sourceRow=489}, -- maschiff -> mabosstiff
    {fromDex=944,toDex=945,level=28,sourceRow=490}, -- shroodle -> grafaiai
    {fromDex=948,toDex=949,level=30,sourceRow=492}, -- toedscool -> toedscruel
    {fromDex=955,toDex=956,level=35,sourceRow=495}, -- flittle -> espathra
    {fromDex=957,toDex=958,level=24,sourceRow=496}, -- tinkatink -> tinkatuff
    {fromDex=958,toDex=959,level=38,sourceRow=497}, -- tinkatuff -> tinkaton
    {fromDex=960,toDex=961,level=26,sourceRow=498}, -- wiglett -> wugtrio
    {fromDex=965,toDex=966,level=40,sourceRow=500}, -- varoom -> revavroom
    {fromDex=969,toDex=970,level=35,sourceRow=501}, -- glimmet -> glimmora
  },
}
