-- Generated by tools/build_wave1_evolution_block_67.py; bounded block 12.
return {
  schema="kasc.wave1-evolution-block/v1",
  sourceCommit="d4f9a4af58ade123fbc0558f68b1c69daa97d9e4",
  edges={
    {fromDex=554,toDex=555,level=35,sourceRow=280}, -- darumaka -> darmanitan
    {fromDex=570,toDex=571,level=30,sourceRow=287}, -- zorua -> zoroark
    {fromDex=627,toDex=628,level=54,sourceRow=316}, -- rufflet -> braviary
    {fromDex=712,toDex=713,level=37,sourceRow=354}, -- bergmite -> avalugg
  },
}
