-- Generated by tools/build_wave1_evolution_block_67.py; bounded block 20.
return {
  schema="kasc.wave1-evolution-block/v1",
  sourceCommit="d4f9a4af58ade123fbc0558f68b1c69daa97d9e4",
  edges={
    {fromDex=696,toDex=697,level=39,method="KA_BACKEND_LEVEL_DAY",timeOfDay="day",sourceRow=352}, -- tyrunt -> tyrantrum
    {fromDex=698,toDex=699,level=39,method="KA_BACKEND_LEVEL_NIGHT",timeOfDay="night",sourceRow=353}, -- amaura -> aurorus
    {fromDex=734,toDex=735,level=20,method="KA_BACKEND_LEVEL_DAY",timeOfDay="day",sourceRow=381}, -- yungoos -> gumshoos
    {fromDex=753,toDex=754,level=34,method="KA_BACKEND_LEVEL_DAY",timeOfDay="day",sourceRow=391}, -- fomantis -> lurantis
    {fromDex=971,toDex=972,level=30,method="KA_BACKEND_LEVEL_NIGHT",timeOfDay="night",sourceRow=502}, -- greavard -> houndstone
  },
}
