-- Generated by tools/build_wave1_evolution_block_67.py; bounded block 26.
return {
  schema="kasc.wave1-evolution-block/v1",
  sourceCommit="d4f9a4af58ade123fbc0558f68b1c69daa97d9e4",
  edges={
    {fromDex=298,toDex=183,method="FRIENDSHIP",friendship=true,sourceRow=101}, -- azurill -> marill
    {fromDex=183,toDex=184,level=18,sourceRow=102}, -- marill -> azumarill
  },
}
