-- Generated by tools/build_wave1_evolution_block_67.py; bounded block 10.
return {
  schema="kasc.wave1-evolution-block/v1",
  sourceCommit="d4f9a4af58ade123fbc0558f68b1c69daa97d9e4",
  edges={
    {fromDex=406,toDex=315,method="KA_BABY_FRIENDSHIP_DAY",friendship=true,timeOfDay="day",sourceRow=164}, -- budew -> roselia
    {fromDex=315,toDex=407,item="SHINY_STONE",sourceRow=204}, -- roselia -> roserade
    {fromDex=433,toDex=358,method="KA_BABY_FRIENDSHIP_NIGHT",friendship=true,timeOfDay="night",sourceRow=182}, -- chingling -> chimecho
    {fromDex=446,toDex=143,method="KA_BABY_FRIENDSHIP",friendship=true,sourceRow=81}, -- munchlax -> snorlax
  },
}
