-- Generated by tools/build_wave1_evolution_block_67.py; bounded block 5.
return {
  schema="kasc.wave1-evolution-block/v1",
  sourceCommit="d4f9a4af58ade123fbc0558f68b1c69daa97d9e4",
  edges={
    {fromDex=810,toDex=811,level=16,sourceRow=411}, -- grookey -> thwackey
    {fromDex=811,toDex=812,level=35,sourceRow=412}, -- thwackey -> rillaboom
    {fromDex=813,toDex=814,level=16,sourceRow=413}, -- scorbunny -> raboot
    {fromDex=814,toDex=815,level=35,sourceRow=414}, -- raboot -> cinderace
    {fromDex=816,toDex=817,level=16,sourceRow=415}, -- sobble -> drizzile
    {fromDex=817,toDex=818,level=35,sourceRow=416}, -- drizzile -> inteleon
    {fromDex=819,toDex=820,level=24,sourceRow=417}, -- skwovet -> greedent
    {fromDex=821,toDex=822,level=18,sourceRow=418}, -- rookidee -> corvisquire
    {fromDex=822,toDex=823,level=38,sourceRow=419}, -- corvisquire -> corviknight
    {fromDex=824,toDex=825,level=10,sourceRow=420}, -- blipbug -> dottler
    {fromDex=825,toDex=826,level=30,sourceRow=421}, -- dottler -> orbeetle
    {fromDex=827,toDex=828,level=18,sourceRow=422}, -- nickit -> thievul
    {fromDex=829,toDex=830,level=20,sourceRow=423}, -- gossifleur -> eldegoss
    {fromDex=831,toDex=832,level=24,sourceRow=424}, -- wooloo -> dubwool
    {fromDex=833,toDex=834,level=22,sourceRow=425}, -- chewtle -> drednaw
    {fromDex=835,toDex=836,level=25,sourceRow=426}, -- yamper -> boltund
    {fromDex=837,toDex=838,level=18,sourceRow=427}, -- rolycoly -> carkol
    {fromDex=838,toDex=839,level=34,sourceRow=428}, -- carkol -> coalossal
    {fromDex=843,toDex=844,level=36,sourceRow=431}, -- silicobra -> sandaconda
    {fromDex=846,toDex=847,level=26,sourceRow=432}, -- arrokuda -> barraskewda
    {fromDex=850,toDex=851,level=28,sourceRow=434}, -- sizzlipede -> centiskorch
    {fromDex=856,toDex=857,level=32,sourceRow=437}, -- hatenna -> hattrem
    {fromDex=857,toDex=858,level=42,sourceRow=438}, -- hattrem -> hatterene
    {fromDex=859,toDex=860,level=32,sourceRow=439}, -- impidimp -> morgrem
    {fromDex=860,toDex=861,level=42,sourceRow=440}, -- morgrem -> grimmsnarl
    {fromDex=878,toDex=879,level=34,sourceRow=443}, -- cufant -> copperajah
  },
}
