-- Generated by tools/build_wave1_evolution_block_67.py; bounded block 11.
return {
  schema="kasc.wave1-evolution-block/v1",
  sourceCommit="d4f9a4af58ade123fbc0558f68b1c69daa97d9e4",
  edges={
    {fromDex=440,toDex=113,method="KA_HAPPINY_OVAL_DAY",timeOfDay="day",heldItem="OVAL_STONE",sourceRow=67}, -- happiny -> chansey
    {fromDex=113,toDex=242,method="KA_WAVE1_CHANSEY_FRIENDSHIP",friendship=true,sourceRow=127}, -- chansey -> blissey
  },
}
