-- Generated by tools/build_wave1_evolution_block_67.py; bounded block 14.
return {
  schema="kasc.wave1-evolution-block/v1",
  sourceCommit="d4f9a4af58ade123fbc0558f68b1c69daa97d9e4",
  edges={
    {fromDex=524,toDex=525,level=25,sourceRow=264}, -- roggenrola -> boldore
    {fromDex=532,toDex=533,level=25,sourceRow=268}, -- timburr -> gurdurr
    {fromDex=540,toDex=541,level=20,sourceRow=272}, -- sewaddle -> swadloon
    {fromDex=548,toDex=549,item="SUN_STONE",sourceRow=277}, -- petilil -> lilligant
    {fromDex=624,toDex=625,level=52,sourceRow=315}, -- pawniard -> bisharp
    {fromDex=921,toDex=922,level=18,sourceRow=477}, -- pawmi -> pawmo
  },
}
