-- Generated by tools/build_wave1_evolution_block_67.py; bounded block 24.
return {
  schema="kasc.wave1-evolution-block/v1",
  sourceCommit="d4f9a4af58ade123fbc0558f68b1c69daa97d9e4",
  edges={
    {fromDex=271,toDex=272,item="WATER_STONE",sourceRow=143}, -- lombre -> ludicolo
    {fromDex=274,toDex=275,item="LEAF_STONE",sourceRow=145}, -- nuzleaf -> shiftry
    {fromDex=300,toDex=301,item="MOON_STONE",sourceRow=159}, -- skitty -> delcatty
  },
}
