-- Generated by tools/build_wave1_evolution_block_67.py; bounded block 18.
return {
  schema="kasc.wave1-evolution-block/v1",
  sourceCommit="d4f9a4af58ade123fbc0558f68b1c69daa97d9e4",
  edges={
    {fromDex=739,toDex=740,item="ICE_STONE",sourceRow=512}, -- crabrawler -> crabominable
    {fromDex=884,toDex=1018,item="METAL_ALLOY",sourceRow=542}, -- duraludon -> archaludon
  },
}
