-- Generated by tools/build_wave1_evolution_block_67.py; bounded block 23.
return {
  schema="kasc.wave1-evolution-block/v1",
  sourceCommit="d4f9a4af58ade123fbc0558f68b1c69daa97d9e4",
  edges={
    {fromDex=669,toDex=670,level=19,sourceRow=346}, -- flabebe -> floette
    {fromDex=670,toDex=671,item="SHINY_STONE",sourceRow=347}, -- floette -> florges
  },
}
