-- Generated by tools/build_wave1_evolution_block_67.py; bounded block 3.
return {
  schema="kasc.wave1-evolution-block/v1",
  sourceCommit="d4f9a4af58ade123fbc0558f68b1c69daa97d9e4",
  edges={
    {fromDex=504,toDex=505,level=20,sourceRow=253}, -- patrat -> watchog
    {fromDex=506,toDex=507,level=16,sourceRow=254}, -- lillipup -> herdier
    {fromDex=507,toDex=508,level=32,sourceRow=255}, -- herdier -> stoutland
    {fromDex=509,toDex=510,level=20,sourceRow=256}, -- purrloin -> liepard
    {fromDex=519,toDex=520,level=21,sourceRow=261}, -- pidove -> tranquill
    {fromDex=520,toDex=521,level=32,sourceRow=262}, -- tranquill -> unfezant
    {fromDex=522,toDex=523,level=27,sourceRow=263}, -- blitzle -> zebstrika
    {fromDex=529,toDex=530,level=31,sourceRow=267}, -- drilbur -> excadrill
    {fromDex=535,toDex=536,level=25,sourceRow=270}, -- tympole -> palpitoad
    {fromDex=536,toDex=537,level=36,sourceRow=271}, -- palpitoad -> seismitoad
    {fromDex=543,toDex=544,level=22,sourceRow=274}, -- venipede -> whirlipede
    {fromDex=544,toDex=545,level=30,sourceRow=275}, -- whirlipede -> scolipede
    {fromDex=551,toDex=552,level=29,sourceRow=278}, -- sandile -> krokorok
    {fromDex=552,toDex=553,level=40,sourceRow=279}, -- krokorok -> krookodile
    {fromDex=557,toDex=558,level=34,sourceRow=281}, -- dwebble -> crustle
    {fromDex=559,toDex=560,level=39,sourceRow=282}, -- scraggy -> scrafty
    {fromDex=562,toDex=563,level=34,sourceRow=283}, -- yamask -> cofagrigus
    {fromDex=564,toDex=565,level=37,sourceRow=284}, -- tirtouga -> carracosta
    {fromDex=566,toDex=567,level=37,sourceRow=285}, -- archen -> archeops
    {fromDex=568,toDex=569,level=36,sourceRow=286}, -- trubbish -> garbodor
    {fromDex=574,toDex=575,level=32,sourceRow=289}, -- gothita -> gothorita
    {fromDex=575,toDex=576,level=41,sourceRow=290}, -- gothorita -> gothitelle
    {fromDex=580,toDex=581,level=35,sourceRow=293}, -- ducklett -> swanna
    {fromDex=582,toDex=583,level=35,sourceRow=294}, -- vanillite -> vanillish
    {fromDex=583,toDex=584,level=47,sourceRow=295}, -- vanillish -> vanilluxe
    {fromDex=585,toDex=586,level=34,sourceRow=296}, -- deerling -> sawsbuck
    {fromDex=590,toDex=591,level=39,sourceRow=298}, -- foongus -> amoonguss
    {fromDex=592,toDex=593,level=40,sourceRow=299}, -- frillish -> jellicent
    {fromDex=595,toDex=596,level=36,sourceRow=300}, -- joltik -> galvantula
    {fromDex=597,toDex=598,level=40,sourceRow=301}, -- ferroseed -> ferrothorn
    {fromDex=599,toDex=600,level=38,sourceRow=302}, -- klink -> klang
    {fromDex=600,toDex=601,level=49,sourceRow=303}, -- klang -> klinklang
    {fromDex=605,toDex=606,level=42,sourceRow=306}, -- elgyem -> beheeyem
    {fromDex=613,toDex=614,level=37,sourceRow=311}, -- cubchoo -> beartic
    {fromDex=619,toDex=620,level=50,sourceRow=313}, -- mienfoo -> mienshao
    {fromDex=622,toDex=623,level=43,sourceRow=314}, -- golett -> golurk
    {fromDex=629,toDex=630,level=54,sourceRow=317}, -- vullaby -> mandibuzz
    {fromDex=636,toDex=637,level=59,sourceRow=320}, -- larvesta -> volcarona
  },
}
