-- Save-gated manual battle matrix. This remains completely dormant on normal
-- playthroughs and appears only in the dedicated acceptance saves generated by
-- tools/create_character_battle_acceptance_saves.lua.

return function(mod, opts)
  opts = opts or {}
  local i18n = opts.i18n
  local Q = {}

  local STAGES = {
    { key = "LAB",       en = "LAB",       de = "LABOR", class = "OPP_RIVAL1", first = 1 },
    { key = "ROUTE22_A", en = "R22-A",     de = "R22-A", class = "OPP_RIVAL1", first = 4 },
    { key = "CERULEAN",  en = "CERUL.",    de = "AZURIA", class = "OPP_RIVAL1", first = 7 },
    { key = "SS_ANNE",   en = "S.S.ANNE",  de = "M.S.ANNE", class = "OPP_RIVAL2", first = 1 },
    { key = "TOWER",     en = "TOWER",     de = "TURM", class = "OPP_RIVAL2", first = 4 },
    { key = "SILPH",     en = "SILPH",     de = "SILPH", class = "OPP_RIVAL2", first = 7 },
    { key = "ROUTE22_B", en = "R22-B",     de = "R22-B", class = "OPP_RIVAL2", first = 10 },
    { key = "CHAMPION",  en = "CHAMPION",  de = "CHAMP", class = "OPP_RIVAL3", first = 1 },
  }
  local BRANCHES = {
    { en = "WATER", de = "WASSER" },
    { en = "GRASS", de = "PFLANZE" },
    { en = "FIRE", de = "FEUER" },
  }

  local function tr(en, de)
    return i18n and i18n.text(en, de) or en
  end

  local function state()
    local value = mod.save:get("battle_acceptance")
    return type(value) == "table" and value or nil
  end

  function Q.enabled()
    local s = state()
    return s and s.enabled == true or false
  end

  function Q.rows()
    local rows = {}
    for stageIndex, stage in ipairs(STAGES) do
      for branch, branchDef in ipairs(BRANCHES) do
        rows[#rows + 1] = {
          label = ("%02d %s %s"):format(stageIndex,
            tr(stage.en, stage.de), tr(branchDef.en, branchDef.de)),
          value = {
            stage = stage.key,
            class = stage.class,
            partyIndex = stage.first + branch - 1,
            branch = branch,
          },
        }
      end
    end
    return rows
  end

  function Q.launch(game, row)
    assert(game and game.overworld, "battle acceptance requires overworld")
    assert(row and row.class and row.partyIndex, "invalid battle acceptance row")
    local BattleState = require("src.battle.BattleState")
    local battle = BattleState.newTrainer(game, row.class, row.partyIndex)
    battle.acceptanceBattle = true
    battle.acceptanceStage = row.stage
    battle.acceptanceBranch = row.branch
    game.overworld:pushBattle(battle)
    return battle
  end

  function Q.open(game)
    local rows = Q.rows()
    game.stack:push((mod.ui.KantoListMenu or mod.ui.ListMenu).new(game,
      tr("RIVAL BATTLES", "RIVALEN-KAEMPFE"), rows, {
        pageJump = true,
        onCancel = function() end,
        onChoose = function(item, menu)
          if not item then return end
          menu:close()
          Q.launch(game, item.value)
        end,
      }))
  end

  mod.hooks:wrap("ui.start_menu.items", function(nextItems, game, items)
    local out = nextItems(game, items)
    if type(out) ~= "table" or not Q.enabled() then return out end
    return mod.ui.insertBefore(out, tr("SAVE", "SICHERN"), {
      label = tr("RIVAL TEST", "RIVALEN-TEST"),
      onSelect = function() Q.open(game) end,
    })
  end, 980)

  Q.stages = STAGES
  Q.branches = BRANCHES
  return Q
end
