-- Identity-authored Red / Blue / Green dialogue.
-- Every value is { English, German }; callers select exactly one language
-- from the active game translation, never from a separate mod-language knob.

local function p(en, de) return { en, de } end

return {
  selection = {
    GREEN = { label = p("GREEN", "GRÜN"), relation = p("MY GRANDDAUGHTER", "MEINE ENKELIN") },
    BLUE = { label = p("BLUE", "BLAU"), relation = p("MY GRANDSON", "MEIN ENKEL") },
    RED = { label = p("RED", "ROT"), relation = p("A BOY FROM\nPALLET TOWN", "EIN JUNGE AUS\nALABASTIA") },
  },

  introAsk = {
    BLUE = p("This is my grand-\nson.\fHe's been your\nrival for years.\f...What was his\nname again?",
      "Das ist mein\nEnkel.\fEr ist seit Jahren\ndein Rivale.\f...Wie hieß er\nnoch gleich?"),
    GREEN = p("This is my grand-\ndaughter.\fShe's your cousin.\f...What was her\nname again?",
      "Das ist meine\nEnkelin.\fSie ist deine\nCousine.\f...Wie hieß sie\nnoch gleich?"),
    RED = p("This boy is from\nPALLET TOWN.\f...I seem to have\nforgotten his name.",
      "Dieser Junge ist\naus ALABASTIA.\f...Seinen Namen habe\nich wohl vergessen."),
  },
  introConfirm = {
    BLUE = p("That's right! His\nname is {RIVAL}!", "Natürlich! Er\nheißt {RIVAL}!"),
    GREEN = p("Of course! Her\nname is {RIVAL}!", "Natürlich! Sie\nheißt {RIVAL}!"),
    RED = p("Right! {RIVAL}!\fA trainer from\nPALLET TOWN.", "Richtig! {RIVAL}!\fEin Trainer aus\nALABASTIA."),
  },
  motherGreen = p(
    "MOM: Right.\nAll girls leave\vhome someday.\fPROF. OAK next\ndoor is looking\vfor you.",
    "MUTTER: Richtig.\nAlle Mädchen ziehen\veines Tages los.\fPROF. EICH von\nnebenan sucht dich."),
  oakFamilyHouse = p("OAK FAMILY HOUSE", "HAUS DER FAMILIE\nEICH"),
  daisyRedAtLab = p("Hi {PLAYER}!\n{RIVAL} is at\vPROF. OAK's lab.",
    "Hallo {PLAYER}!\n{RIVAL} ist im\vLabor von PROF.\nEICH."),
  lanceGreen = p("You have one more\nchallenge ahead.\fHer name is...\n{RIVAL}!\fShe beat the ELITE\nFOUR before you!\fShe is the real\nLEAGUE champion!",
    "Eine letzte\nHerausforderung\vwartet noch.\fIhr Name ist...\n{RIVAL}!\fSie besiegte die\nTOP VIER vor dir!\fSie ist die wahre\nLIGA-Meisterin!"),

  rival = {
    RED = {
      _OaksLabRivalFedUpWithWaitingText = p("{RIVAL}: PROF. OAK.\nI'm here.", "{RIVAL}: PROF. EICH.\nIch bin da."),
      _OaksLabRivalGrampsIsntAroundText = p("{RIVAL}: {PLAYER}.\nPROF. OAK isn't\vhere.", "{RIVAL}: {PLAYER}.\nPROF. EICH ist\vnicht hier."),
      _OaksLabRivalGrampsText = p("{RIVAL}: PROF. OAK.", "{RIVAL}: PROF. EICH."),
      _OaksLabRivalWhatAboutMeText = p("{RIVAL}: PROF. OAK.\nAnd me?", "{RIVAL}: PROF. EICH.\nUnd ich?"),
      _OaksLabRivalWhatDidYouCallMeForText = p("{RIVAL}: You called,\nPROF. OAK?", "{RIVAL}: Sie riefen,\nPROF. EICH?"),
      _OaksLabRivalGoAheadAndChooseText = p("{RIVAL}: Go ahead,\n{PLAYER}. I'll\vchoose after you.", "{RIVAL}: Nur zu,\n{PLAYER}. Ich wähle\vdanach."),
      _OaksLabRivalIllTakeThisOneText = p("{RIVAL}: Then I'll\ntake this one.", "{RIVAL}: Dann nehme\nich dieses."),
      _OaksLabRivalIllTakeYouOnText = p("{RIVAL}: {PLAYER}.\nWait.\fLet's see what our\nPOKéMON can do.", "{RIVAL}: {PLAYER}.\nWarte.\fSehen wir, was\nunsere POKéMON\vkönnen."),
      _OaksLabRivalLeaveItAllToMeText = p("{RIVAL}: Understood,\nPROF. OAK.\f{PLAYER}. I'll finish\nthe POKéDEX too.", "{RIVAL}: Verstanden,\nPROF. EICH.\f{PLAYER}. Ich werde\nden POKéDEX auch\vvervollständigen."),
      _OaksLabRivalSmellYouLaterText = p("{RIVAL}: I'll train\nthis POKéMON.\fSee you, {PLAYER}.", "{RIVAL}: Ich trainiere\ndieses POKéMON.\fBis dann, {PLAYER}."),
      _OaksLabRivalMyPokemonLooksStrongerText = p("{RIVAL}: Mine looks\nready.", "{RIVAL}: Meines ist\nbereit."),
      _OaksLabRivalIPickedTheWrongPokemonText = p("...I chose\npoorly.", "...Falsch\ngewählt."),
      _OaksLabRivalAmIGreatOrWhatText = p("{RIVAL}: ...Good\nbattle.", "{RIVAL}: ...Guter\nKampf."),
      _Rival1WinText = p("{RIVAL}: ...Good\nbattle.", "{RIVAL}: ...Guter\nKampf."),
      _CeruleanCityRivalPreBattleText = p("{RIVAL}: {PLAYER}.\nYou've improved.\fShow me your team.", "{RIVAL}: {PLAYER}.\nDu bist besser.\fZeig mir dein Team."),
      _CeruleanCityRivalDefeatedText = p("You won.\nGood battle.", "Du hast gewonnen.\nGuter Kampf."),
      _CeruleanCityRivalIWentToBillsText = p("{RIVAL}: I met BILL.\nHis system is\vimpressive.\fYou should thank\nhim too.\fSee you.", "{RIVAL}: Ich traf BILL.\nSein System ist\vbeeindruckend.\fBedank dich auch\nbei ihm.\fBis dann."),
      _PokemonTower2FRivalWhatBringsYouHereText = p("{RIVAL}: {PLAYER}.\nWhy are you here?\fLet's battle.", "{RIVAL}: {PLAYER}.\nWarum bist du hier?\fKämpfen wir."),
      _PokemonTower2FRivalDefeatedText = p("You won.\fMy team needs\nmore training.", "Du hast gewonnen.\fMein Team braucht\nmehr Training."),
      _PokemonTower2FRivalVictoryText = p("{RIVAL}: Train them\nmore.", "{RIVAL}: Trainiere sie\nweiter."),
      _Route22RivalBeforeBattleText1 = p("{RIVAL}: The guard\nneeds BADGEs.\fAre your POKéMON\nready?", "{RIVAL}: Die Wache\nverlangt ORDEN.\fSind deine POKéMON\nbereit?"),
      _Route22Rival1VictoryText = p("{RIVAL}: Build a\nbigger team.", "{RIVAL}: Stell ein\ngrößeres Team auf."),
      _Route22RivalBeforeBattleText2 = p("{RIVAL}: You have all\nthe BADGEs too.\fOne battle before\nthe LEAGUE.", "{RIVAL}: Du hast auch\nalle ORDEN.\fEin Kampf vor der\nLIGA."),
      _Route22Rival2VictoryText = p("{RIVAL}: Train more.\nI'll be waiting.", "{RIVAL}: Trainiere\nweiter. Ich warte."),
      _SSAnne2FRivalText = p("{RIVAL}: {PLAYER}.\nYou made it aboard.\fHow is your\nPOKéDEX?", "{RIVAL}: {PLAYER}.\nDu bist an Bord.\fWie steht dein\nPOKéDEX?"),
      _SSAnne2FRivalDefeatedText = p("...You won.\fYour team has\ngrown.", "...Du hast gewonnen.\fDein Team ist\nstärker."),
      _SSAnne2FRivalCutMasterText = p("{RIVAL}: The captain\nknows CUT.\fGo see him.", "{RIVAL}: Der Kapitän\nkennt ZERSCHNEIDER.\fGeh zu ihm."),
      _SilphCo7FRivalText = p("{RIVAL}: You took\nyour time, {PLAYER}.", "{RIVAL}: Du hast dir\nZeit gelassen,\n{PLAYER}."),
      _SilphCo7FRivalWaitedHereText = p("{RIVAL}: I expected\nyou.\fShow me how much\nyou've improved.", "{RIVAL}: Ich habe mit\ndir gerechnet.\fZeig, wie viel\nbesser du bist."),
      _SilphCo7FRivalDefeatedText = p("You are ready.\fTEAM ROCKET is\nahead.", "Du bist bereit.\fTEAM ROCKET ist\nvoraus."),
      _SilphCo7FRivalVictoryText = p("{RIVAL}: Not yet.\nKeep training.", "{RIVAL}: Noch nicht.\nTrainiere weiter."),
      _ChampionsRoomRivalIntroText = p("{RIVAL}: {PLAYER}.\nI knew you'd come.\fI trained across\nKANTO for this.\fNow I'm the LEAGUE\nchampion.\fShow me your best.", "{RIVAL}: {PLAYER}.\nDu bist also da.\fDafür trainierte\nich in ganz KANTO.\fNun bin ich der\nLIGA-Meister.\fZeig dein Bestes."),
      _RivalDefeatedText = p("No... You won.\fYour bond was\nstronger. I see\vthat now.", "Nein... Du hast\ngewonnen.\fEure Bindung war\nstärker. Das sehe\vich jetzt."),
      _RivalVictoryText = p("I won.\fTrain more,\n{PLAYER}. I'll be\vwaiting.", "Ich habe gewonnen.\fTrainiere weiter,\n{PLAYER}. Ich warte."),
    },

    GREEN = {
      _OaksLabRivalFedUpWithWaitingText = p("{RIVAL}: Grandpa!\nI was waiting!", "{RIVAL}: Opa!\nIch habe gewartet!"),
      _OaksLabRivalGrampsIsntAroundText = p("{RIVAL}: Hey,\n{PLAYER}! Grandpa's\vnot here!", "{RIVAL}: Hey,\n{PLAYER}! Opa ist\vnicht hier!"),
      _OaksLabRivalGrampsText = p("{RIVAL}: Grandpa!", "{RIVAL}: Opa!"),
      _OaksLabRivalWhatAboutMeText = p("{RIVAL}: Hey! What\nabout me, Grandpa?", "{RIVAL}: Hey! Was ist\nmit mir, Opa?"),
      _OaksLabRivalWhatDidYouCallMeForText = p("{RIVAL}: You called,\nGrandpa?", "{RIVAL}: Du hast mich\ngerufen, Opa?"),
      _OaksLabRivalGoAheadAndChooseText = p("{RIVAL}: Go ahead!\nI'll still pick\vthe better one.", "{RIVAL}: Nur zu!\nIch wähle trotzdem\vdas bessere."),
      _OaksLabRivalIllTakeThisOneText = p("{RIVAL}: This one\nsuits me!", "{RIVAL}: Dieses passt\nzu mir!"),
      _OaksLabRivalIllTakeYouOnText = p("{RIVAL}: Wait,\n{PLAYER}!\fLet's see whose\nchoice was better!", "{RIVAL}: Warte,\n{PLAYER}!\fMal sehen, wer\nbesser gewählt hat!"),
      _OaksLabRivalLeaveItAllToMeText = p("{RIVAL}: Leave it to\nme, Grandpa!\fTry to keep up,\n{PLAYER}!", "{RIVAL}: Überlass das\nmir, Opa!\fVersuch mitzuhalten,\n{PLAYER}!"),
      _OaksLabRivalSmellYouLaterText = p("{RIVAL}: I'll train\nhard!\fCatch me if you\ncan, {PLAYER}!", "{RIVAL}: Ich trainiere\nhart!\fHol mich ein, wenn\ndu kannst, {PLAYER}!"),
      _OaksLabRivalMyPokemonLooksStrongerText = p("{RIVAL}: Mine looks\nstronger already!", "{RIVAL}: Meines sieht\njetzt schon stärker\vaus!"),
      _OaksLabRivalIPickedTheWrongPokemonText = p("What? Lucky pick,\n{PLAYER}!", "Was? Glück gehabt,\n{PLAYER}!"),
      _OaksLabRivalAmIGreatOrWhatText = p("{RIVAL}: Told you\nI'd win!", "{RIVAL}: Ich sagte doch,\ndass ich gewinne!"),
      _Rival1WinText = p("{RIVAL}: Told you\nI'd win!", "{RIVAL}: Ich sagte doch,\ndass ich gewinne!"),
      _CeruleanCityRivalPreBattleText = p("{RIVAL}: Hey,\n{PLAYER}! Still\vback here?\fLet's compare teams!", "{RIVAL}: Hey,\n{PLAYER}! Noch hier?\fVergleichen wir\nunsere Teams!"),
      _CeruleanCityRivalDefeatedText = p("Okay, you win!\fDon't get too\ncomfortable!", "Okay, du gewinnst!\fGewöhn dich nicht\ndaran!"),
      _CeruleanCityRivalIWentToBillsText = p("{RIVAL}: BILL showed\nme rare POKéMON!\fHis PC is clever.\nGo thank him!\fCatch you later!", "{RIVAL}: BILL zeigte\nmir seltene POKéMON!\fSein PC ist genial.\nBedank dich bei ihm!\fBis später!"),
      _PokemonTower2FRivalWhatBringsYouHereText = p("{RIVAL}: Hey,\n{PLAYER}!\fLet's see if your\nteam can keep up!", "{RIVAL}: Hey,\n{PLAYER}!\fMal sehen, ob dein\nTeam mithält!"),
      _PokemonTower2FRivalDefeatedText = p("You got me!\fNext time I won't\ngo easy!", "Du hast mich!\fNächstes Mal mache\nich es dir schwer!"),
      _PokemonTower2FRivalVictoryText = p("{RIVAL}: Not bad.\nTrain a little more!", "{RIVAL}: Nicht übel.\nTrainiere noch etwas!"),
      _Route22RivalBeforeBattleText1 = p("{RIVAL}: No BADGEs?\nThe guard says no!\fBut I'll say yes\nto a battle!", "{RIVAL}: Keine ORDEN?\nDie Wache sagt nein!\fZu einem Kampf\nsage ich aber ja!"),
      _Route22Rival1VictoryText = p("{RIVAL}: Catch more\nPOKéMON, then try\vagain!", "{RIVAL}: Fang mehr\nPOKéMON und versuch\ves noch mal!"),
      _Route22RivalBeforeBattleText2 = p("{RIVAL}: All BADGEs?\nNice!\fNow warm me up for\nthe LEAGUE!", "{RIVAL}: Alle ORDEN?\nNicht schlecht!\fWärm mich für die\nLIGA auf!"),
      _Route22Rival2VictoryText = p("{RIVAL}: So close!\nTrain more and try\vto catch me!", "{RIVAL}: Fast! Trainiere\nweiter und hol\vmich ein!"),
      _SSAnne2FRivalText = p("{RIVAL}: Bonjour,\n{PLAYER}!\fFancy meeting you\nhere!\fHow is your POKéDEX?", "{RIVAL}: Bonjour,\n{PLAYER}!\fDich trifft man auch\nüberall!\fWie steht dein POKéDEX?"),
      _SSAnne2FRivalDefeatedText = p("Not bad!\fYou're catching up!", "Nicht schlecht!\fDu holst auf!"),
      _SSAnne2FRivalCutMasterText = p("{RIVAL}: The captain\nknows CUT.\fTry not to get\nseasick!", "{RIVAL}: Der Kapitän\nkennt ZERSCHNEIDER.\fWerd nur nicht\nseekrank!"),
      _SilphCo7FRivalText = p("{RIVAL}: Finally,\n{PLAYER}!", "{RIVAL}: Endlich,\n{PLAYER}!"),
      _SilphCo7FRivalWaitedHereText = p("{RIVAL}: I knew you'd\nshow up!\fLet's see if TEAM\nROCKET slowed you\vdown!", "{RIVAL}: Ich wusste,\ndass du kommst!\fMal sehen, ob TEAM\nROCKET dich\vgebremst hat!"),
      _SilphCo7FRivalDefeatedText = p("Fine! You are\nready for ROCKET!\fNow catch up!", "Gut! Du bist bereit\nfür ROCKET!\fJetzt hol mich ein!"),
      _SilphCo7FRivalVictoryText = p("{RIVAL}: You can't\njoin the big league\vyet!", "{RIVAL}: Für die große\nLiga reicht es noch\vnicht!"),
      _ChampionsRoomRivalIntroText = p("{RIVAL}: There you\nare, {PLAYER}!\fI searched KANTO\nfor the best team.\fNow I'm the LEAGUE\nchampion!\fCome on! Try to take\nthe crown!", "{RIVAL}: Da bist du,\n{PLAYER}!\fIch suchte in KANTO\nnach dem besten Team.\fJetzt bin ich\nLIGA-Meisterin!\fLos! Hol dir die\nKrone, wenn du kannst!"),
      _RivalDefeatedText = p("You got me!\fEnjoy the crown.\nI'll win it back!", "Du hast mich!\fGenieß die Krone.\nIch hole sie zurück!"),
      _RivalVictoryText = p("I win!\fGood try, {PLAYER}.\nCome catch me!", "Ich gewinne!\fGut versucht,\n{PLAYER}. Hol mich ein!"),
    },
  },
}
