-- Identity-authored Red / Blue / Green dialogue.
-- Every value is { English, German }; callers select exactly one language
-- from the active game translation, never from a separate mod-language knob.

local function p(en, de) return { en, de } end

return {
  selection = {
    GREEN = { label = p("GREEN", "GRÜN"), relation = p("A GIRL FROM\nPALLET TOWN", "EIN MÄDCHEN AUS\nALABASTIA") },
    BLUE = { label = p("BLUE", "BLAU"), relation = p("MY GRANDSON", "MEIN ENKEL") },
    RED = { label = p("RED", "ROT"), relation = p("A BOY FROM\nPALLET TOWN", "EIN JUNGE AUS\nALABASTIA") },
  },

  introAsk = {
    BLUE = p("This is my grand-\nson.\fHe's been your\nrival for years.\f...What was his\nname again?",
      "Das ist mein\nEnkel.\fEr ist seit Jahren\ndein Rivale.\f...Wie hieß er\nnoch gleich?"),
    GREEN = p("This girl is from\nPALLET TOWN.\fShe's friendly, quick,\nand full of plans.\f...What was her\nname again?",
      "Dieses Mädchen ist\naus ALABASTIA.\fSie ist freundlich,\nlebhaft und voller Pläne.\f...Wie hieß sie\nnoch gleich?"),
    RED = p("This boy is from\nPALLET TOWN.\fHe says little, but\nlistens closely.\f...What was his\nname again?",
      "Dieser Junge ist\naus ALABASTIA.\fEr sagt wenig, hört\naber genau zu.\f...Wie hieß er\nnoch gleich?"),
  },
  introConfirm = {
    BLUE = p("That's right! His\nname is {RIVAL}!", "Natürlich! Er\nheißt {RIVAL}!"),
    GREEN = p("Of course! Her\nname is {RIVAL}!", "Natürlich! Sie\nheißt {RIVAL}!"),
    RED = p("Right! {RIVAL}!\fA trainer from\nPALLET TOWN.", "Richtig! {RIVAL}!\fEin Trainer aus\nALABASTIA."),
  },
  motherGreen = p(
    "MOM: Right.\nAll girls leave\vhome someday.\fPROF. OAK next\ndoor is looking\vfor you.",
    "MUTTER: Richtig.\nAlle Mädchen ziehen\veines Tages los.\fPROF. EICH von\nnebenan sucht dich."),
  oakFamilyHouse = p("OAK FAMILY HOUSE", "HAUS DER FAMILIE\nEICH"),
  daisyRedAtLab = p("Hi {PLAYER}!\n{RIVAL} is at\vPROF. OAK's lab.",
    "Hallo {PLAYER}!\n{RIVAL} ist im\vLabor von PROF.\nEICH."),
  lanceGreen = p("One challenge\nremains.\fHer name is...\n{RIVAL}!\fShe took a wrong turn,\nthen beat the ELITE\nFOUR before you!\fShe is the real\nLEAGUE champion!",
    "Eine Herausforderung\nbleibt noch.\fIhr Name ist...\n{RIVAL}!\fSie bog falsch ab und\nbesiegte dann vor dir\ndie TOP VIER!\fSie ist die wahre\nLIGA-Meisterin!"),

  rival = {
    RED = {
      _OaksLabRivalFedUpWithWaitingText = p("{RIVAL}: PROF. OAK.\nI'm here.", "{RIVAL}: PROF. EICH.\nIch bin da."),
      _OaksLabRivalGrampsIsntAroundText = p("{RIVAL}: {PLAYER}.\nPROF. OAK stepped out.\fWe should wait here.", "{RIVAL}: {PLAYER}.\nPROF. EICH ist fort.\fWir sollten hier\nwarten."),
      _OaksLabRivalGrampsText = p("{RIVAL}: PROF. OAK.\nYou wanted us?", "{RIVAL}: PROF. EICH.\nSie wollten uns\nsprechen?"),
      _OaksLabRivalWhatAboutMeText = p("{RIVAL}: And me,\nProfessor?", "{RIVAL}: Und ich,\nProfessor?"),
      _OaksLabRivalWhatDidYouCallMeForText = p("{RIVAL}: You called us,\nPROF. OAK?", "{RIVAL}: Sie riefen uns,\nPROF. EICH?"),
      _OaksLabRivalGoAheadAndChooseText = p("{RIVAL}: Good for you,\n{PLAYER}.\fI wonder which\npartner you'll choose.", "{RIVAL}: Freut mich für\ndich, {PLAYER}.\fIch bin gespannt,\nwen du wählst."),
      _OaksLabRivalIllGetABetterPokemonThanYou = p("{RIVAL}: I'll wait.\fA careful choice is\nworth the time.", "{RIVAL}: Ich warte.\fEine gute Wahl\nbraucht Zeit."),
      _OaksLabRivalIllTakeThisOneText = p("{RIVAL}: Then this one\nwill be my partner.", "{RIVAL}: Dann wird dieses\nmein Partner."),
      _OaksLabRivalReceivedMonText = p("{RIVAL} received\na {RAM:wNameBuffer}!", "{RIVAL} erhält\n{RAM:wNameBuffer}!"),
      _OaksLabRivalTakesText1 = p("{RIVAL}: {PLAYER},\nI took this one.\fI thought PROF. OAK\nset it aside for me.", "{RIVAL}: {PLAYER},\nich nahm dieses.\fIch dachte, PROF. EICH\nhätte es für mich\nvorgesehen."),
      _OaksLabRivalTakesText2 = p("{RIVAL} carefully\nholds the POKéMON.", "{RIVAL} hält das\nPOKéMON vorsichtig."),
      _OaksLabRivalTakesText3 = p("OAK: {RIVAL}!\nThat was not the\nplan.", "EICH: {RIVAL}!\nSo war das nicht\ngeplant."),
      _OaksLabRivalTakesText4 = p("{RIVAL}: I understand,\nProfessor.\fI should have asked\nfirst.", "{RIVAL}: Verstanden,\nProfessor.\fIch hätte zuerst\nfragen sollen."),
      _OaksLabRivalTakesText5 = p("OAK: Hmm...\nKeep that POKéMON.\fWe can still make\nthis work.\f{PLAYER}, come over\nhere.", "EICH: Hmm...\nBehalte das POKéMON.\fWir können es noch\nso lösen.\f{PLAYER}, komm bitte\nher."),
      _OaksLabRivalIllTakeYouOnText = p("{RIVAL}: Wait,\n{PLAYER}.\fBefore we leave,\nlet's learn how our\npartners think.", "{RIVAL}: Warte,\n{PLAYER}.\fBevor wir gehen,\nlernen wir, wie unsere\nPartner denken."),
      _OaksLabRivalLeaveItAllToMeText = p("{RIVAL}: Understood,\nPROF. OAK.\fI'll record what I\nobserve.\fWe'll both finish it,\n{PLAYER}.", "{RIVAL}: Verstanden,\nPROF. EICH.\fIch notiere, was ich\nbeobachte.\fWir schaffen es beide,\n{PLAYER}."),
      _OaksLabRivalSmellYouLaterText = p("{RIVAL}: I'll train\nwith this partner.\fUntil next time,\n{PLAYER}.", "{RIVAL}: Ich trainiere\nmit diesem Partner.\fBis zum nächsten Mal,\n{PLAYER}."),
      _OaksLabRivalMyPokemonHasGrownStrongerText = p("{RIVAL}: PROF. OAK,\nmy POKéMON has\ngrown stronger.\fWould you take a\nlook?", "{RIVAL}: PROF. EICH,\nmein POKéMON ist\nstärker geworden.\fWürden Sie es sich\nansehen?"),
      _OaksLabRivalMyPokemonLooksStrongerText = p("{RIVAL}: Yours looks\nready.\fMine does too.", "{RIVAL}: Deines wirkt\nbereit.\fMeines auch."),
      _OaksLabRivalIPickedTheWrongPokemonText = p("I rushed that choice.\fThank you, {PLAYER}.\nI learned something.", "Ich wählte zu hastig.\fDanke, {PLAYER}.\nIch habe gelernt."),
      _OaksLabRivalAmIGreatOrWhatText = p("{RIVAL}: A close battle.\fThank you.", "{RIVAL}: Ein knapper Kampf.\fDanke."),
      _Rival1WinText = p("{RIVAL}: A close battle.\fThank you.", "{RIVAL}: Ein knapper Kampf.\fDanke."),
      _CeruleanCityRivalPreBattleText = p("{RIVAL}: {PLAYER}.\nYou've come far.\fI'd like to see how\nour teams have grown.", "{RIVAL}: {PLAYER}.\nDu bist weit gekommen.\fIch möchte sehen, wie\nunsere Teams wuchsen."),
      _CeruleanCityRivalDefeatedText = p("You won.\fYour team trusted\nyour plan.", "Du hast gewonnen.\fDein Team vertraute\ndeinem Plan."),
      _CeruleanCityRivalIWentToBillsText = p("{RIVAL}: I met BILL.\fHis system is\nelegant.\fYou should see it too.\fUntil next time.", "{RIVAL}: Ich traf BILL.\fSein System ist\nelegant.\fDu solltest es sehen.\fBis zum nächsten Mal."),
      _PokemonTower2FRivalWhatBringsYouHereText = p("{RIVAL}: {PLAYER}.\fDid you come to pay\nrespects too?\fLet's test our teams\nwith care.", "{RIVAL}: {PLAYER}.\fBist du auch hier, um\nRespekt zu erweisen?\fPrüfen wir unsere\nTeams mit Bedacht."),
      _PokemonTower2FRivalDefeatedText = p("You won.\fI still have more\nto understand.", "Du hast gewonnen.\fIch muss noch mehr\nverstehen."),
      _PokemonTower2FRivalVictoryText = p("{RIVAL}: Take care of\nthem.\fThis tower reminds us\nwhy.", "{RIVAL}: Pass gut auf\nsie auf.\fDieser Turm zeigt uns,\nwarum."),
      _Route22RivalBeforeBattleText1 = p("{RIVAL}: The guard\nneeds BADGEs.\fBefore we turn back,\nwill you test me?", "{RIVAL}: Die Wache\nverlangt ORDEN.\fBevor wir umkehren,\nprüfst du mich?"),
      _Route22Rival1VictoryText = p("{RIVAL}: Your team\nneeds time.\fSo does mine.", "{RIVAL}: Dein Team\nbraucht Zeit.\fMeines auch."),
      _Route22RivalBeforeBattleText2 = p("{RIVAL}: All eight\nBADGEs.\fOne honest battle\nbefore the LEAGUE?", "{RIVAL}: Alle acht\nORDEN.\fEin ehrlicher Kampf\nvor der LIGA?"),
      _Route22Rival2VictoryText = p("{RIVAL}: We both know\nwhat to improve.\fI'll see you inside.", "{RIVAL}: Wir wissen beide,\nwas noch fehlt.\fWir sehen uns drinnen."),
      _SSAnne2FRivalText = p("{RIVAL}: {PLAYER}.\nYou made it aboard.\fThe sea is calmer\nthan the crowd.\fHow is your POKéDEX?", "{RIVAL}: {PLAYER}.\nDu bist an Bord.\fDas Meer ist ruhiger\nals die Menge.\fWie steht dein POKéDEX?"),
      _SSAnne2FRivalDefeatedText = p("You won.\fYour team stayed\ncalm.", "Du hast gewonnen.\fDein Team blieb\nruhig."),
      _SSAnne2FRivalCutMasterText = p("{RIVAL}: The captain\nknows CUT.\fHe may help you.\fTry not to trouble him.", "{RIVAL}: Der Kapitän\nkennt ZERSCHNEIDER.\fEr hilft dir sicher.\fStör ihn nicht zu sehr."),
      _SilphCo7FRivalText = p("{RIVAL}: You came,\n{PLAYER}.\fI was beginning to\nworry.", "{RIVAL}: Du bist da,\n{PLAYER}.\fIch begann, mir Sorgen\nzu machen."),
      _SilphCo7FRivalWaitedHereText = p("{RIVAL}: TEAM ROCKET\nis ahead.\fFirst, show me you're\nready to face them.", "{RIVAL}: TEAM ROCKET\nist voraus.\fZeig mir zuerst, dass\ndu bereit bist."),
      _SilphCo7FRivalDefeatedText = p("You are ready.\fDon't take needless\nrisks ahead.", "Du bist bereit.\fGeh dort vorn keine\nunnötigen Risiken ein."),
      _SilphCo7FRivalVictoryText = p("{RIVAL}: Not yet.\fA little more care.", "{RIVAL}: Noch nicht.\fEtwas mehr Bedacht."),
      _ChampionsRoomRivalIntroText = p("{RIVAL}: {PLAYER}.\nI knew you'd come.\fEvery road through\nKANTO led us here.\fI'm the LEAGUE\nchampion.\fPlease show me your\nbest.", "{RIVAL}: {PLAYER}.\nIch wusste, du kommst.\fJeder Weg durch KANTO\nführte uns hierher.\fIch bin der\nLIGA-Meister.\fZeig mir bitte dein\nBestes."),
      _RivalDefeatedText = p("You won.\fYour bond with your\nteam was stronger.\fI understand now.", "Du hast gewonnen.\fDeine Bindung zu\ndeinem Team war stärker.\fJetzt verstehe ich."),
      _RivalVictoryText = p("I won.\fWhen you're ready,\n{PLAYER}, I'll be here.", "Ich habe gewonnen.\fWenn du bereit bist,\n{PLAYER}, bin ich hier."),
    },

    GREEN = {
      _OaksLabRivalFedUpWithWaitingText = p("{RIVAL}: Professor!\fI brought my notes.\f...Most of them.", "{RIVAL}: Professor!\fIch habe meine Notizen.\f...Die meisten."),
      _OaksLabRivalGrampsIsntAroundText = p("{RIVAL}: Hey,\n{PLAYER}!\fPROF. OAK isn't here.\fI checked twice.\fWell... two rooms.", "{RIVAL}: Hey,\n{PLAYER}!\fPROF. EICH ist nicht hier.\fIch sah zweimal nach.\fAlso... in zwei Räumen."),
      _OaksLabRivalGrampsText = p("{RIVAL}: Professor!\fThere you are!", "{RIVAL}: Professor!\fDa sind Sie ja!"),
      _OaksLabRivalWhatAboutMeText = p("{RIVAL}: What about me,\nProfessor?\fI was very patient!\fMostly.", "{RIVAL}: Was ist mit mir,\nProfessor?\fIch war sehr geduldig!\fMeistens."),
      _OaksLabRivalWhatDidYouCallMeForText = p("{RIVAL}: You called,\nProfessor?\fI came right away.\fAfter one detour.", "{RIVAL}: Sie haben gerufen,\nProfessor?\fIch kam sofort.\fNach einem Umweg."),
      _OaksLabRivalGoAheadAndChooseText = p("{RIVAL}: You first,\n{PLAYER}!\fThen I'll choose\ncarefully.\fProbably.", "{RIVAL}: Du zuerst,\n{PLAYER}!\fDann wähle ich ganz\nklug.\fHoffentlich."),
      _OaksLabRivalIllGetABetterPokemonThanYou = p("{RIVAL}: I'll choose\ncarefully too!\fAs soon as I remember\nwhich one I liked.", "{RIVAL}: Ich wähle\nauch ganz sorgfältig!\fSobald mir einfällt,\nwelches mir gefiel."),
      _OaksLabRivalIllTakeThisOneText = p("{RIVAL}: This one!\fWe made eye contact.\fI think.", "{RIVAL}: Dieses hier!\fWir hatten Blickkontakt.\fGlaube ich."),
      _OaksLabRivalReceivedMonText = p("{RIVAL} received\na {RAM:wNameBuffer}!", "{RIVAL} erhält\n{RAM:wNameBuffer}!"),
      _OaksLabRivalTakesText1 = p("{RIVAL}: {PLAYER},\nI picked this one!\f...Wait. Was this yours?", "{RIVAL}: {PLAYER},\nich nahm dieses!\f...Moment. War das deins?"),
      _OaksLabRivalTakesText2 = p("{RIVAL} grabbed the\nPOKéMON by mistake!", "{RIVAL} griff aus\nVersehen zum POKéMON!"),
      _OaksLabRivalTakesText3 = p("OAK: {RIVAL}!\nThat one was for--", "EICH: {RIVAL}!\nDas war doch für--"),
      _OaksLabRivalTakesText4 = p("{RIVAL}: Oh!\nProfessor, I thought\nyou pointed here.\fSorry!", "{RIVAL}: Oh!\nProfessor, ich dachte,\nSie zeigten hierher.\fEntschuldigung!"),
      _OaksLabRivalTakesText5 = p("OAK: Well...\nIt chose you too,\nit seems.\fAll right. It is\nyours.\f{PLAYER}, come over\nhere.", "EICH: Nun...\nEs wählte offenbar\nauch dich.\fGut. Es gehört dir.\f{PLAYER}, komm bitte\nher."),
      _OaksLabRivalIllTakeYouOnText = p("{RIVAL}: Wait,\n{PLAYER}!\fA first battle!\fFor research.\fAnd because I really\nwant to win!", "{RIVAL}: Warte,\n{PLAYER}!\fEin erster Kampf!\fFür die Forschung.\fUnd weil ich wirklich\ngewinnen will!"),
      _OaksLabRivalLeaveItAllToMeText = p("{RIVAL}: Leave it to\nme, Professor!\fI have a filing system.\fIt's one big pile.\fKeep up, {PLAYER}!", "{RIVAL}: Überlassen Sie das\nmir, Professor!\fIch habe ein Ablagesystem.\fEs ist ein großer Stapel.\fBleib dran, {PLAYER}!"),
      _OaksLabRivalSmellYouLaterText = p("{RIVAL}: I'll train hard!\fAnd sort my notes!\fOne of those first.\fCatch me, {PLAYER}!", "{RIVAL}: Ich trainiere hart!\fUnd sortiere Notizen!\fEines davon zuerst.\fHol mich ein, {PLAYER}!"),
      _OaksLabRivalMyPokemonHasGrownStrongerText = p("{RIVAL}: Professor,\nmy POKéMON grew\nstronger!\fI wrote it down.\fThen misplaced it.", "{RIVAL}: Professor,\nmein POKéMON wurde\nstärker!\fIch schrieb es auf.\fDann verlegte ich es."),
      _OaksLabRivalMyPokemonLooksStrongerText = p("{RIVAL}: Mine looks\nstronger!\fOr taller.\fDefinitely something.", "{RIVAL}: Meines wirkt\nstärker!\fOder größer.\fGanz sicher irgendwas."),
      _OaksLabRivalIPickedTheWrongPokemonText = p("Okay, wrong theory!\fUseful result,\n{PLAYER}!", "Okay, falsche Theorie!\fNützliches Ergebnis,\n{PLAYER}!"),
      _OaksLabRivalAmIGreatOrWhatText = p("{RIVAL}: Great plan!\fI'll write it down\nbefore I forget.", "{RIVAL}: Toller Plan!\fIch schreibe ihn auf,\nbevor ich ihn vergesse."),
      _Rival1WinText = p("{RIVAL}: Great plan!\fI'll write it down\nbefore I forget.", "{RIVAL}: Toller Plan!\fIch schreibe ihn auf,\nbevor ich ihn vergesse."),
      _CeruleanCityRivalPreBattleText = p("{RIVAL}: Hey,\n{PLAYER}!\fI came from BILL's.\fOr the bridge.\fAnyway--team check!", "{RIVAL}: Hey,\n{PLAYER}!\fIch komme von BILL.\fOder von der Brücke.\fEgal--Teamtest!"),
      _CeruleanCityRivalDefeatedText = p("You win!\fMy plan was perfect\nuntil the battling\npart.", "Du gewinnst!\fMein Plan war perfekt,\nbis zum Kampfteil."),
      _CeruleanCityRivalIWentToBillsText = p("{RIVAL}: BILL showed me\nrare POKéMON!\fHis PC is brilliant.\fI asked twelve questions.\fHe answered eleven.\fGo thank him!", "{RIVAL}: BILL zeigte mir\nseltene POKéMON!\fSein PC ist genial.\fIch stellte zwölf Fragen.\fElf hat er beantwortet.\fBedank dich bei ihm!"),
      _PokemonTower2FRivalWhatBringsYouHereText = p("{RIVAL}: Hey,\n{PLAYER}.\fI came to pay respects.\fAnd got a little lost.\fA gentle battle?", "{RIVAL}: Hey,\n{PLAYER}.\fIch wollte Respekt zeigen.\fUnd verlief mich etwas.\fEin sanfter Kampf?"),
      _PokemonTower2FRivalDefeatedText = p("You got me.\fLet's keep our teams\nclose in here.", "Du hast mich.\fBehalten wir unsere\nTeams hier nah bei uns."),
      _PokemonTower2FRivalVictoryText = p("{RIVAL}: I won.\fNow let's both look\nafter our teams.", "{RIVAL}: Ich gewann.\fJetzt passen wir beide\nauf unsere Teams auf."),
      _Route22RivalBeforeBattleText1 = p("{RIVAL}: No BADGEs,\nno entry.\fI asked nicely.\fThen twice loudly.\fBattle while we wait?", "{RIVAL}: Keine ORDEN,\nkein Zutritt.\fIch fragte höflich.\fDann zweimal laut.\fKampf beim Warten?"),
      _Route22Rival1VictoryText = p("{RIVAL}: Catch more\nPOKéMON!\fOr befriend the ones\nyou have.", "{RIVAL}: Fang mehr\nPOKéMON!\fOder freunde dich mit\ndeinen an."),
      _Route22RivalBeforeBattleText2 = p("{RIVAL}: All BADGEs?\fMe too--I counted twice.\fOne warm-up before\nthe LEAGUE?", "{RIVAL}: Alle ORDEN?\fIch auch--zweimal gezählt.\fEin Aufwärmkampf vor\nder LIGA?"),
      _Route22Rival2VictoryText = p("{RIVAL}: So close!\fI mean you were.\fSee you at the top!", "{RIVAL}: So knapp!\fAlso für dich.\fWir sehen uns oben!"),
      _SSAnne2FRivalText = p("{RIVAL}: Bonjour,\n{PLAYER}!\fI practiced all morning.\fThen nearly boarded\nthe wrong ship.\fHow is your POKéDEX?", "{RIVAL}: Bonjour,\n{PLAYER}!\fIch übte den ganzen Morgen.\fDann nahm ich fast\ndas falsche Schiff.\fWie steht dein POKéDEX?"),
      _SSAnne2FRivalDefeatedText = p("You got me!\fMy sea legs were\napparently optional.", "Du hast mich!\fMeine Seebeine waren\nwohl optional."),
      _SSAnne2FRivalCutMasterText = p("{RIVAL}: The captain\nknows CUT.\fHe also looks seasick.\fMaybe knock first.", "{RIVAL}: Der Kapitän\nkennt ZERSCHNEIDER.\fEr wirkt auch seekrank.\fKlopf vielleicht erst."),
      _SilphCo7FRivalText = p("{RIVAL}: Finally,\n{PLAYER}!\fI mean--perfect timing.", "{RIVAL}: Endlich,\n{PLAYER}!\fAlso--perfektes Timing."),
      _SilphCo7FRivalWaitedHereText = p("{RIVAL}: I knew you'd\ncome!\fI made a shortcut map.\fIt became a long-cut.\fBattle before ROCKET?", "{RIVAL}: Ich wusste,\ndass du kommst!\fIch zeichnete eine Abkürzung.\fSie wurde ein Umweg.\fKampf vor ROCKET?"),
      _SilphCo7FRivalDefeatedText = p("You win!\fTEAM ROCKET is ahead.\fFollow the explosions.\fNot mine. Probably.", "Du gewinnst!\fTEAM ROCKET ist voraus.\fFolge den Explosionen.\fNicht meine. Hoffentlich."),
      _SilphCo7FRivalVictoryText = p("{RIVAL}: Not yet!\fI checked my plan\nthree times.\fDifferent every time.", "{RIVAL}: Noch nicht!\fIch prüfte meinen Plan\ndreimal.\fJedes Mal ein anderer."),
      _ChampionsRoomRivalIntroText = p("{RIVAL}: There you are,\n{PLAYER}!\fI found KANTO's\nbest team.\fSomehow they found\nme too.\fNow I'm the LEAGUE\nchampion!\fLet's make this one\nto remember!", "{RIVAL}: Da bist du,\n{PLAYER}!\fIch fand KANTOs\nbestes Team.\fIrgendwie fand es\nauch mich.\fJetzt bin ich\nLIGA-Meisterin!\fDiesen Kampf vergessen\nwir nicht!"),
      _RivalDefeatedText = p("You got me!\fThe crown suits you.\fI had it upside down\nanyway.", "Du hast mich!\fDie Krone steht dir.\fIch trug sie sowieso\nverkehrt herum."),
      _RivalVictoryText = p("I win!\fGood try, {PLAYER}.\fI nearly forgot what\nmy winning plan was.", "Ich gewinne!\fGut versucht, {PLAYER}.\fFast hätte ich meinen\nSiegesplan vergessen."),
    },
  },
}
