-- Kanto Ascendant 5.0: inspectable rosters for the Battle Factory and
-- S.S. Anne Grand Tour.  Every rental candidate is a fully evolved,
-- non-legendary species from the original 251-Pokemon roster.

local function text(en, de)
  return { en = en, de = de }
end

local function mon(species, moves)
  return { species = species, level = 100, moves = moves }
end

local function opponent(key, name, class, intro, win, team)
  return {
    key = key,
    name = text(name[1], name[2]),
    class = class,
    intro = text(intro[1], intro[2]),
    win = text(win[1], win[2]),
    team = team,
  }
end

return {
  version = 1,
  factory = {
    map = "INDIGO_PLATEAU_LOBBY",
    name = "KANTO_ASCENDANT_BATTLE_FACTORY",
    textId = "MOD_KANTO_ASCENDANT_BATTLE_FACTORY",
    sprite = "SPRITE_COOLTRAINER_F",
    preferred = { { 13, 5 }, { 12, 5 }, { 13, 6 }, { 12, 6 } },
    rounds = 3,
    candidates = {
      mon("VENUSAUR", { "RAZOR_LEAF", "SLEEP_POWDER", "BODY_SLAM", "REFLECT" }),
      mon("CHARIZARD", { "FIRE_BLAST", "FLY", "SLASH", "EARTHQUAKE" }),
      mon("BLASTOISE", { "HYDRO_PUMP", "BLIZZARD", "BODY_SLAM", "EARTHQUAKE" }),
      mon("RAICHU", { "THUNDERBOLT", "THUNDER_WAVE", "SURF", "BODY_SLAM" }),
      mon("NIDOQUEEN", { "EARTHQUAKE", "BLIZZARD", "THUNDERBOLT", "BODY_SLAM" }),
      mon("NIDOKING", { "EARTHQUAKE", "ROCK_SLIDE", "THUNDERBOLT", "BLIZZARD" }),
      mon("ALAKAZAM", { "PSYCHIC_M", "RECOVER", "REFLECT", "THUNDER_WAVE" }),
      mon("MACHAMP", { "SUBMISSION", "EARTHQUAKE", "ROCK_SLIDE", "BODY_SLAM" }),
      mon("GOLEM", { "EARTHQUAKE", "ROCK_SLIDE", "BODY_SLAM", "EXPLOSION" }),
      mon("SLOWBRO", { "SURF", "PSYCHIC_M", "AMNESIA", "REST" }),
      mon("MAGNETON", { "THUNDERBOLT", "THUNDER_WAVE", "SWIFT", "SCREECH" }),
      mon("CLOYSTER", { "BLIZZARD", "SURF", "CLAMP", "EXPLOSION" }),
      mon("GENGAR", { "PSYCHIC_M", "THUNDERBOLT", "HYPNOSIS", "EXPLOSION" }),
      mon("EXEGGUTOR", { "PSYCHIC_M", "SLEEP_POWDER", "GIGA_DRAIN", "EXPLOSION" }),
      mon("STARMIE", { "SURF", "PSYCHIC_M", "THUNDERBOLT", "RECOVER" }),
      mon("TAUROS", { "BODY_SLAM", "HYPER_BEAM", "EARTHQUAKE", "BLIZZARD" }),
      mon("GYARADOS", { "HYDRO_PUMP", "BLIZZARD", "THUNDERBOLT", "HYPER_BEAM" }),
      mon("LAPRAS", { "SURF", "BLIZZARD", "THUNDERBOLT", "BODY_SLAM" }),
      mon("SNORLAX", { "BODY_SLAM", "EARTHQUAKE", "REST", "HYPER_BEAM" }),
      mon("DRAGONITE", { "BLIZZARD", "THUNDER", "HYPER_BEAM", "AGILITY" }),
      mon("MEGANIUM", { "RAZOR_LEAF", "SLEEP_POWDER", "REFLECT", "BODY_SLAM" }),
      mon("TYPHLOSION", { "FIRE_BLAST", "THUNDERPUNCH", "EARTHQUAKE", "SMOKESCREEN" }),
      mon("FERALIGATR", { "HYDRO_PUMP", "BLIZZARD", "CRUNCH", "SLASH" }),
      mon("CROBAT", { "WING_ATTACK", "CONFUSE_RAY", "TOXIC", "HYPER_BEAM" }),
      mon("AMPHAROS", { "THUNDER", "THUNDER_WAVE", "FIRE_PUNCH", "LIGHT_SCREEN" }),
      mon("BELLOSSOM", { "GIGA_DRAIN", "SLEEP_POWDER", "REST", "SLUDGE_BOMB" }),
      mon("POLITOED", { "HYDRO_PUMP", "BLIZZARD", "HYPNOSIS", "BODY_SLAM" }),
      mon("ESPEON", { "PSYCHIC_M", "RECOVER", "REFLECT", "SWIFT" }),
      mon("UMBREON", { "CRUNCH", "TOXIC", "CONFUSE_RAY", "REST" }),
      mon("SLOWKING", { "PSYCHIC_M", "SURF", "AMNESIA", "REST" }),
      mon("STEELIX", { "IRON_TAIL", "EARTHQUAKE", "ROCK_SLIDE", "EXPLOSION" }),
      mon("SCIZOR", { "METAL_CLAW", "SLASH", "SWORDS_DANCE", "HYPER_BEAM" }),
      mon("HERACROSS", { "PIN_MISSILE", "SUBMISSION", "EARTHQUAKE", "SWORDS_DANCE" }),
      mon("KINGDRA", { "HYDRO_PUMP", "BLIZZARD", "SMOKESCREEN", "HYPER_BEAM" }),
      mon("PORYGON2", { "TRI_ATTACK", "PSYCHIC_M", "RECOVER", "THUNDER_WAVE" }),
      mon("BLISSEY", { "BODY_SLAM", "THUNDER_WAVE", "SOFTBOILED", "BLIZZARD" }),
      mon("TYRANITAR", { "CRUNCH", "ROCK_SLIDE", "EARTHQUAKE", "HYPER_BEAM" }),
    },
    opponents = {
      opponent("vector", { "DR. VECTOR", "DR. VEKTOR" }, "OPP_SCIENTIST",
        { "DR. VECTOR: A rental\nteam reveals its\ntrainer's true skill.",
          "DR. VEKTOR: Ein Leih-\nteam zeigt das wahre\nKönnen des Trainers." },
        { "The variables were\nperfectly chosen.", "Die Variablen waren\nperfekt gewählt." }, {
          mon("PORYGON2", { "TRI_ATTACK", "PSYCHIC_M", "RECOVER", "THUNDER_WAVE" }),
          mon("MAGNETON", { "THUNDERBOLT", "THUNDER_WAVE", "SWIFT", "SCREECH" }),
          mon("ALAKAZAM", { "PSYCHIC_M", "RECOVER", "REFLECT", "THUNDER_WAVE" }),
        }),
      opponent("marina", { "MARINA", "MARINA" }, "OPP_COOLTRAINER_F",
        { "MARINA: Three choices.\nThree battles.\nNo excuses.",
          "MARINA: Drei Wahlen.\nDrei Kämpfe.\nKeine Ausreden." },
        { "You made every slot\ncount!", "Jeder Platz in deinem\nTeam hat gezählt!" }, {
          mon("STARMIE", { "SURF", "PSYCHIC_M", "THUNDERBOLT", "RECOVER" }),
          mon("TAUROS", { "BODY_SLAM", "HYPER_BEAM", "EARTHQUAKE", "BLIZZARD" }),
          mon("EXEGGUTOR", { "PSYCHIC_M", "SLEEP_POWDER", "GIGA_DRAIN", "EXPLOSION" }),
        }),
      opponent("rex", { "REX", "REX" }, "OPP_TAMER",
        { "REX: I don't need six\nto corner you!",
          "REX: Ich brauche keine\nsechs, um dich zu\nstellen!" },
        { "You tamed the whole\nmatch.", "Du hast den ganzen\nKampf gezähmt." }, {
          mon("TYRANITAR", { "CRUNCH", "ROCK_SLIDE", "EARTHQUAKE", "HYPER_BEAM" }),
          mon("GYARADOS", { "HYDRO_PUMP", "BLIZZARD", "THUNDERBOLT", "HYPER_BEAM" }),
          mon("ARCANINE", { "FIRE_BLAST", "BODY_SLAM", "DIG", "AGILITY" }),
        }),
      opponent("maya", { "MAYA", "MAYA" }, "OPP_PSYCHIC_TR",
        { "MAYA: I saw your draft.\nI also saw its end.",
          "MAYA: Ich sah deine\nWahl. Auch ihr Ende." },
        { "The future changed\nwhen you battled.", "Im Kampf hast du die\nZukunft geändert." }, {
          mon("ESPEON", { "PSYCHIC_M", "RECOVER", "REFLECT", "SWIFT" }),
          mon("UMBREON", { "CRUNCH", "TOXIC", "CONFUSE_RAY", "REST" }),
          mon("MACHAMP", { "SUBMISSION", "EARTHQUAKE", "ROCK_SLIDE", "BODY_SLAM" }),
        }),
      opponent("ken", { "KEN", "KEN" }, "OPP_BLACKBELT",
        { "KEN: Borrowed partners\nstill need a strong\nleader!",
          "KEN: Auch Leihpartner\nbrauchen einen starken\nAnführer!" },
        { "Your bond formed in\nan instant.", "Eure Bindung entstand\nin einem Augenblick." }, {
          mon("HERACROSS", { "PIN_MISSILE", "SUBMISSION", "EARTHQUAKE", "SWORDS_DANCE" }),
          mon("STEELIX", { "IRON_TAIL", "EARTHQUAKE", "ROCK_SLIDE", "EXPLOSION" }),
          mon("CROBAT", { "WING_ATTACK", "CONFUSE_RAY", "TOXIC", "HYPER_BEAM" }),
        }),
      opponent("ivy", { "IVY", "IVY" }, "OPP_BEAUTY",
        { "IVY: A beautiful draft\nhas no wasted move.",
          "IVY: Eine schöne Wahl\nverschwendet keinen\nZug." },
        { "That finish was\nflawless.", "Dieses Finale war\nmakellos." }, {
          mon("BELLOSSOM", { "GIGA_DRAIN", "SLEEP_POWDER", "REST", "SLUDGE_BOMB" }),
          mon("LAPRAS", { "SURF", "BLIZZARD", "THUNDERBOLT", "BODY_SLAM" }),
          mon("NIDOKING", { "EARTHQUAKE", "ROCK_SLIDE", "THUNDERBOLT", "BLIZZARD" }),
        }),
      opponent("cal", { "CAL", "CAL" }, "OPP_COOLTRAINER_M",
        { "CAL: Your last test is\nadaptation itself!",
          "CAL: Deine letzte\nPrüfung ist Anpassung!" },
        { "That team became your\nown.", "Dieses Team wurde zu\ndeinem eigenen." }, {
          mon("SCIZOR", { "METAL_CLAW", "SLASH", "SWORDS_DANCE", "HYPER_BEAM" }),
          mon("KINGDRA", { "HYDRO_PUMP", "BLIZZARD", "SMOKESCREEN", "HYPER_BEAM" }),
          mon("SNORLAX", { "BODY_SLAM", "EARTHQUAKE", "REST", "HYPER_BEAM" }),
        }),
    },
  },
  cruise = {
    map = "VERMILION_CITY",
    name = "KANTO_ASCENDANT_SS_ANNE_HOST",
    textId = "MOD_KANTO_ASCENDANT_SS_ANNE_HOST",
    sprite = "SPRITE_SAILOR",
    preferred = { { 18, 30 }, { 19, 30 }, { 17, 30 }, { 20, 30 } },
    rounds = 5,
    cooldown = 4096,
    opponents = {
      opponent("deck", { "DECKHAND FINN", "MATROSE FINN" }, "OPP_SAILOR",
        { "FINN: The tide opens\nour Grand Tour!", "FINN: Die Flut eröffnet\nunsere Grosse Fahrt!" },
        { "You crossed the first\nwave!", "Du hast die erste\nWelle bezwungen!" }, {
          mon("POLITOED", { "HYDRO_PUMP", "BLIZZARD", "HYPNOSIS", "BODY_SLAM" }),
          mon("CLOYSTER", { "BLIZZARD", "SURF", "CLAMP", "EXPLOSION" }),
          mon("TENTACRUEL", { "SURF", "BLIZZARD", "TOXIC", "HYPER_BEAM" }),
          mon("LANTURN", { "SURF", "THUNDERBOLT", "CONFUSE_RAY", "THUNDER_WAVE" }),
          mon("KINGDRA", { "HYDRO_PUMP", "BLIZZARD", "SMOKESCREEN", "HYPER_BEAM" }),
          mon("GYARADOS", { "HYDRO_PUMP", "BLIZZARD", "THUNDERBOLT", "HYPER_BEAM" }),
        }),
      opponent("engine", { "CHIEF VOLT", "CHIEF VOLT" }, "OPP_ENGINEER",
        { "VOLT: Every deck plate\nis fully charged!", "VOLT: Jede Deckplatte\nsteht unter Strom!" },
        { "You grounded the whole\nsystem.", "Du hast das ganze\nSystem geerdet." }, {
          mon("RAICHU", { "THUNDERBOLT", "THUNDER_WAVE", "SURF", "BODY_SLAM" }),
          mon("MAGNETON", { "THUNDERBOLT", "THUNDER_WAVE", "SWIFT", "SCREECH" }),
          mon("ELECTRODE", { "THUNDERBOLT", "THUNDER_WAVE", "SWIFT", "EXPLOSION" }),
          mon("AMPHAROS", { "THUNDER", "THUNDER_WAVE", "FIRE_PUNCH", "LIGHT_SCREEN" }),
          mon("STEELIX", { "IRON_TAIL", "EARTHQUAKE", "ROCK_SLIDE", "EXPLOSION" }),
          mon("PORYGON2", { "TRI_ATTACK", "PSYCHIC_M", "RECOVER", "THUNDER_WAVE" }),
        }),
      opponent("garden", { "BOTANIST ROSE", "BOTANIKERIN ROSE" }, "OPP_BEAUTY",
        { "ROSE: Even at sea, my\ngarden keeps growing.", "ROSE: Selbst auf See\nwächst mein Garten." },
        { "Your victory is in\nfull bloom.", "Dein Sieg steht in\nvoller Blüte." }, {
          mon("VENUSAUR", { "RAZOR_LEAF", "SLEEP_POWDER", "BODY_SLAM", "REFLECT" }),
          mon("EXEGGUTOR", { "PSYCHIC_M", "SLEEP_POWDER", "GIGA_DRAIN", "EXPLOSION" }),
          mon("BELLOSSOM", { "GIGA_DRAIN", "SLEEP_POWDER", "REST", "SLUDGE_BOMB" }),
          mon("JUMPLUFF", { "SLEEP_POWDER", "GIGA_DRAIN", "LEECH_SEED", "TOXIC" }),
          mon("SCIZOR", { "METAL_CLAW", "SLASH", "SWORDS_DANCE", "HYPER_BEAM" }),
          mon("HERACROSS", { "PIN_MISSILE", "SUBMISSION", "EARTHQUAKE", "SWORDS_DANCE" }),
        }),
      opponent("stone", { "PORTER CRAG", "TRÄGER CRAG" }, "OPP_HIKER",
        { "CRAG: A steady footing\nwins on any ocean!", "CRAG: Fester Stand siegt\nauf jedem Ozean!" },
        { "You moved a mountain\nat sea.", "Du hast auf See einen\nBerg versetzt." }, {
          mon("GOLEM", { "EARTHQUAKE", "ROCK_SLIDE", "BODY_SLAM", "EXPLOSION" }),
          mon("RHYDON", { "EARTHQUAKE", "ROCK_SLIDE", "THUNDER", "SUBMISSION" }),
          mon("NIDOQUEEN", { "EARTHQUAKE", "BLIZZARD", "THUNDERBOLT", "BODY_SLAM" }),
          mon("DONPHAN", { "EARTHQUAKE", "ROCK_SLIDE", "BODY_SLAM", "DEFENSE_CURL" }),
          mon("STEELIX", { "IRON_TAIL", "EARTHQUAKE", "ROCK_SLIDE", "EXPLOSION" }),
          mon("TYRANITAR", { "CRUNCH", "ROCK_SLIDE", "EARTHQUAKE", "HYPER_BEAM" }),
        }),
      opponent("gale", { "PILOT GALE", "PILOT GALE" }, "OPP_BIRD_KEEPER",
        { "GALE: The upper deck\nbelongs to the wind!", "GALE: Das Oberdeck\ngehört dem Wind!" },
        { "You flew beyond my\nhorizon.", "Du flogst über meinen\nHorizont hinaus." }, {
          mon("CHARIZARD", { "FIRE_BLAST", "FLY", "SLASH", "EARTHQUAKE" }),
          mon("CROBAT", { "WING_ATTACK", "CONFUSE_RAY", "TOXIC", "HYPER_BEAM" }),
          mon("SKARMORY", { "SKY_ATTACK", "METAL_CLAW", "SAND_ATTACK", "AGILITY" }),
          mon("AERODACTYL", { "ROCK_SLIDE", "FLY", "HYPER_BEAM", "AGILITY" }),
          mon("PIDGEOT", { "SKY_ATTACK", "FLY", "SAND_ATTACK", "AGILITY" }),
          mon("DRAGONITE", { "BLIZZARD", "THUNDER", "HYPER_BEAM", "AGILITY" }),
        }),
      opponent("salon", { "SIR REGINALD", "SIR REGINALD" }, "OPP_GENTLEMAN",
        { "REGINALD: The salon\nexpects refined combat.", "REGINALD: Der Salon\nerwartet feinen Kampf." },
        { "An impeccable\nperformance!", "Eine tadellose\nVorstellung!" }, {
          mon("PERSIAN", { "SLASH", "BODY_SLAM", "THUNDERBOLT", "BUBBLEBEAM" }),
          mon("ARCANINE", { "FIRE_BLAST", "BODY_SLAM", "DIG", "AGILITY" }),
          mon("LAPRAS", { "SURF", "BLIZZARD", "THUNDERBOLT", "BODY_SLAM" }),
          mon("ESPEON", { "PSYCHIC_M", "RECOVER", "REFLECT", "SWIFT" }),
          mon("UMBREON", { "CRUNCH", "TOXIC", "CONFUSE_RAY", "REST" }),
          mon("SNORLAX", { "BODY_SLAM", "EARTHQUAKE", "REST", "HYPER_BEAM" }),
        }),
      opponent("stars", { "NAVIGATOR NOVA", "NAVIGATOR NOVA" }, "OPP_PSYCHIC_TR",
        { "NOVA: The stars already\ncharted this battle.", "NOVA: Die Sterne haben\ndiesen Kampf kartiert." },
        { "You found a route the\nstars missed.", "Du fandest eine Route,\ndie Sterne übersahen." }, {
          mon("ALAKAZAM", { "PSYCHIC_M", "RECOVER", "REFLECT", "THUNDER_WAVE" }),
          mon("STARMIE", { "SURF", "PSYCHIC_M", "THUNDERBOLT", "RECOVER" }),
          mon("SLOWKING", { "PSYCHIC_M", "SURF", "AMNESIA", "REST" }),
          mon("EXEGGUTOR", { "PSYCHIC_M", "SLEEP_POWDER", "GIGA_DRAIN", "EXPLOSION" }),
          mon("ESPEON", { "PSYCHIC_M", "RECOVER", "REFLECT", "SWIFT" }),
          mon("BLISSEY", { "BODY_SLAM", "THUNDER_WAVE", "SOFTBOILED", "BLIZZARD" }),
        }),
      opponent("captain", { "CAPTAIN ANNE", "KAPITÄN ANNE" }, "OPP_COOLTRAINER_F",
        { "ANNE: The Grand Tour\nanswers only to a\ncomplete Champion!", "ANNE: Die Grosse Fahrt\nfolgt nur einem\nvollkommenen Champ!" },
        { "Kanto's finest has\ncommand of the ship!", "Kantos Bester hat das\nKommando an Bord!" }, {
          mon("FERALIGATR", { "HYDRO_PUMP", "BLIZZARD", "CRUNCH", "SLASH" }),
          mon("TYPHLOSION", { "FIRE_BLAST", "THUNDERPUNCH", "EARTHQUAKE", "SMOKESCREEN" }),
          mon("MEGANIUM", { "RAZOR_LEAF", "SLEEP_POWDER", "REFLECT", "BODY_SLAM" }),
          mon("SCIZOR", { "METAL_CLAW", "SLASH", "SWORDS_DANCE", "HYPER_BEAM" }),
          mon("KINGDRA", { "HYDRO_PUMP", "BLIZZARD", "SMOKESCREEN", "HYPER_BEAM" }),
          mon("TYRANITAR", { "CRUNCH", "ROCK_SLIDE", "EARTHQUAKE", "HYPER_BEAM" }),
        }),
    },
  },
}
