-- Generated by tools/build_hoenn_runtime_67.py. DO NOT EDIT.
-- Offline runtime projection from pinned local source records.
return {
  _meta = {
    gameDataCommit = "4bf39fe6ce32d720a03964be4c24e22198ba8de8",
    pokeapiDataCommit = "cd40ffdf0f5c68fc81c39c2ebec256e128fe1966",
    heldTradeAdaptation = "explicit usable item; no silent trade bypass",
    wurmpleSplit = "stable Gen-I DV checksum parity",
  },
  breeding = {
    [252] = { species = "TREECKO", sourceDex = 252, gender = 1, hatch = 20, groups = { "monster", "dragon" } },
    [253] = { species = "GROVYLE", sourceDex = 253, gender = 1, hatch = 20, groups = { "monster", "dragon" } },
    [254] = { species = "SCEPTILE", sourceDex = 254, gender = 1, hatch = 20, groups = { "monster", "dragon" } },
    [255] = { species = "TORCHIC", sourceDex = 255, gender = 1, hatch = 20, groups = { "ground" } },
    [256] = { species = "COMBUSKEN", sourceDex = 256, gender = 1, hatch = 20, groups = { "ground" } },
    [257] = { species = "BLAZIKEN", sourceDex = 257, gender = 1, hatch = 20, groups = { "ground" } },
    [258] = { species = "MUDKIP", sourceDex = 258, gender = 1, hatch = 20, groups = { "monster", "water1" } },
    [259] = { species = "MARSHTOMP", sourceDex = 259, gender = 1, hatch = 20, groups = { "monster", "water1" } },
    [260] = { species = "SWAMPERT", sourceDex = 260, gender = 1, hatch = 20, groups = { "monster", "water1" } },
    [3261] = { species = "POOCHYENA", sourceDex = 261, gender = 4, hatch = 15, groups = { "ground" } },
    [3262] = { species = "MIGHTYENA", sourceDex = 262, gender = 4, hatch = 15, groups = { "ground" } },
    [3263] = { species = "ZIGZAGOON", sourceDex = 263, gender = 4, hatch = 15, groups = { "ground" } },
    [3264] = { species = "LINOONE", sourceDex = 264, gender = 4, hatch = 15, groups = { "ground" } },
    [3265] = { species = "WURMPLE", sourceDex = 265, gender = 4, hatch = 15, groups = { "bug" } },
    [3266] = { species = "SILCOON", sourceDex = 266, gender = 4, hatch = 15, groups = { "bug" } },
    [3267] = { species = "BEAUTIFLY", sourceDex = 267, gender = 4, hatch = 15, groups = { "bug" } },
    [3268] = { species = "CASCOON", sourceDex = 268, gender = 4, hatch = 15, groups = { "bug" } },
    [3269] = { species = "DUSTOX", sourceDex = 269, gender = 4, hatch = 15, groups = { "bug" } },
    [3270] = { species = "LOTAD", sourceDex = 270, gender = 4, hatch = 15, groups = { "water1", "plant" } },
    [3271] = { species = "LOMBRE", sourceDex = 271, gender = 4, hatch = 15, groups = { "water1", "plant" } },
    [3272] = { species = "LUDICOLO", sourceDex = 272, gender = 4, hatch = 15, groups = { "water1", "plant" } },
    [3273] = { species = "SEEDOT", sourceDex = 273, gender = 4, hatch = 15, groups = { "ground", "plant" } },
    [3274] = { species = "NUZLEAF", sourceDex = 274, gender = 4, hatch = 15, groups = { "ground", "plant" } },
    [3275] = { species = "SHIFTRY", sourceDex = 275, gender = 4, hatch = 15, groups = { "ground", "plant" } },
    [3276] = { species = "TAILLOW", sourceDex = 276, gender = 4, hatch = 15, groups = { "flying" } },
    [3277] = { species = "SWELLOW", sourceDex = 277, gender = 4, hatch = 15, groups = { "flying" } },
    [3278] = { species = "WINGULL", sourceDex = 278, gender = 4, hatch = 20, groups = { "water1", "flying" } },
    [3279] = { species = "PELIPPER", sourceDex = 279, gender = 4, hatch = 20, groups = { "water1", "flying" } },
    [280] = { species = "RALTS", sourceDex = 280, gender = 4, hatch = 20, groups = { "humanshape", "indeterminate" } },
    [281] = { species = "KIRLIA", sourceDex = 281, gender = 4, hatch = 20, groups = { "humanshape", "indeterminate" } },
    [282] = { species = "GARDEVOIR", sourceDex = 282, gender = 4, hatch = 20, groups = { "humanshape", "indeterminate" } },
    [283] = { species = "SURSKIT", sourceDex = 283, gender = 4, hatch = 15, groups = { "water1", "bug" } },
    [284] = { species = "MASQUERAIN", sourceDex = 284, gender = 4, hatch = 15, groups = { "water1", "bug" } },
    [285] = { species = "SHROOMISH", sourceDex = 285, gender = 4, hatch = 15, groups = { "fairy", "plant" } },
    [286] = { species = "BRELOOM", sourceDex = 286, gender = 4, hatch = 15, groups = { "fairy", "plant" } },
    [287] = { species = "SLAKOTH", sourceDex = 287, gender = 4, hatch = 15, groups = { "ground" } },
    [288] = { species = "VIGOROTH", sourceDex = 288, gender = 4, hatch = 15, groups = { "ground" } },
    [289] = { species = "SLAKING", sourceDex = 289, gender = 4, hatch = 15, groups = { "ground" } },
    [290] = { species = "NINCADA", sourceDex = 290, gender = 4, hatch = 15, groups = { "bug" } },
    [291] = { species = "NINJASK", sourceDex = 291, gender = 4, hatch = 15, groups = { "bug" } },
    [292] = { species = "SHEDINJA", sourceDex = 292, gender = -1, hatch = 15, groups = { "mineral" } },
    [293] = { species = "WHISMUR", sourceDex = 293, gender = 4, hatch = 20, groups = { "monster", "ground" } },
    [294] = { species = "LOUDRED", sourceDex = 294, gender = 4, hatch = 20, groups = { "monster", "ground" } },
    [295] = { species = "EXPLOUD", sourceDex = 295, gender = 4, hatch = 20, groups = { "monster", "ground" } },
    [296] = { species = "MAKUHITA", sourceDex = 296, gender = 2, hatch = 20, groups = { "humanshape" } },
    [297] = { species = "HARIYAMA", sourceDex = 297, gender = 2, hatch = 20, groups = { "humanshape" } },
    [278] = { species = "AZURILL", sourceDex = 298, gender = 6, hatch = 10, groups = { "no-eggs" } },
    [299] = { species = "NOSEPASS", sourceDex = 299, gender = 4, hatch = 20, groups = { "mineral" } },
    [300] = { species = "SKITTY", sourceDex = 300, gender = 6, hatch = 15, groups = { "ground", "fairy" } },
    [301] = { species = "DELCATTY", sourceDex = 301, gender = 6, hatch = 15, groups = { "ground", "fairy" } },
    [302] = { species = "SABLEYE", sourceDex = 302, gender = 4, hatch = 25, groups = { "humanshape" } },
    [303] = { species = "MAWILE", sourceDex = 303, gender = 4, hatch = 20, groups = { "ground", "fairy" } },
    [304] = { species = "ARON", sourceDex = 304, gender = 4, hatch = 35, groups = { "monster" } },
    [305] = { species = "LAIRON", sourceDex = 305, gender = 4, hatch = 35, groups = { "monster" } },
    [306] = { species = "AGGRON", sourceDex = 306, gender = 4, hatch = 35, groups = { "monster" } },
    [307] = { species = "MEDITITE", sourceDex = 307, gender = 4, hatch = 20, groups = { "humanshape" } },
    [308] = { species = "MEDICHAM", sourceDex = 308, gender = 4, hatch = 20, groups = { "humanshape" } },
    [309] = { species = "ELECTRIKE", sourceDex = 309, gender = 4, hatch = 20, groups = { "ground" } },
    [310] = { species = "MANECTRIC", sourceDex = 310, gender = 4, hatch = 20, groups = { "ground" } },
    [311] = { species = "PLUSLE", sourceDex = 311, gender = 4, hatch = 20, groups = { "fairy" } },
    [312] = { species = "MINUN", sourceDex = 312, gender = 4, hatch = 20, groups = { "fairy" } },
    [313] = { species = "VOLBEAT", sourceDex = 313, gender = 0, hatch = 15, groups = { "bug", "humanshape" } },
    [314] = { species = "ILLUMISE", sourceDex = 314, gender = 8, hatch = 15, groups = { "bug", "humanshape" } },
    [315] = { species = "ROSELIA", sourceDex = 315, gender = 4, hatch = 20, groups = { "fairy", "plant" } },
    [316] = { species = "GULPIN", sourceDex = 316, gender = 4, hatch = 20, groups = { "indeterminate" } },
    [317] = { species = "SWALOT", sourceDex = 317, gender = 4, hatch = 20, groups = { "indeterminate" } },
    [318] = { species = "CARVANHA", sourceDex = 318, gender = 4, hatch = 20, groups = { "water2" } },
    [319] = { species = "SHARPEDO", sourceDex = 319, gender = 4, hatch = 20, groups = { "water2" } },
    [320] = { species = "WAILMER", sourceDex = 320, gender = 4, hatch = 40, groups = { "ground", "water2" } },
    [321] = { species = "WAILORD", sourceDex = 321, gender = 4, hatch = 40, groups = { "ground", "water2" } },
    [322] = { species = "NUMEL", sourceDex = 322, gender = 4, hatch = 20, groups = { "ground" } },
    [323] = { species = "CAMERUPT", sourceDex = 323, gender = 4, hatch = 20, groups = { "ground" } },
    [324] = { species = "TORKOAL", sourceDex = 324, gender = 4, hatch = 20, groups = { "ground" } },
    [325] = { species = "SPOINK", sourceDex = 325, gender = 4, hatch = 20, groups = { "ground" } },
    [326] = { species = "GRUMPIG", sourceDex = 326, gender = 4, hatch = 20, groups = { "ground" } },
    [327] = { species = "SPINDA", sourceDex = 327, gender = 4, hatch = 15, groups = { "ground", "humanshape" } },
    [328] = { species = "TRAPINCH", sourceDex = 328, gender = 4, hatch = 20, groups = { "bug", "dragon" } },
    [329] = { species = "VIBRAVA", sourceDex = 329, gender = 4, hatch = 20, groups = { "bug", "dragon" } },
    [330] = { species = "FLYGON", sourceDex = 330, gender = 4, hatch = 20, groups = { "bug", "dragon" } },
    [331] = { species = "CACNEA", sourceDex = 331, gender = 4, hatch = 20, groups = { "plant", "humanshape" } },
    [332] = { species = "CACTURNE", sourceDex = 332, gender = 4, hatch = 20, groups = { "plant", "humanshape" } },
    [333] = { species = "SWABLU", sourceDex = 333, gender = 4, hatch = 20, groups = { "flying", "dragon" } },
    [334] = { species = "ALTARIA", sourceDex = 334, gender = 4, hatch = 20, groups = { "flying", "dragon" } },
    [335] = { species = "ZANGOOSE", sourceDex = 335, gender = 4, hatch = 20, groups = { "ground" } },
    [336] = { species = "SEVIPER", sourceDex = 336, gender = 4, hatch = 20, groups = { "ground", "dragon" } },
    [337] = { species = "LUNATONE", sourceDex = 337, gender = -1, hatch = 25, groups = { "mineral" } },
    [338] = { species = "SOLROCK", sourceDex = 338, gender = -1, hatch = 25, groups = { "mineral" } },
    [339] = { species = "BARBOACH", sourceDex = 339, gender = 4, hatch = 20, groups = { "water2" } },
    [340] = { species = "WHISCASH", sourceDex = 340, gender = 4, hatch = 20, groups = { "water2" } },
    [341] = { species = "CORPHISH", sourceDex = 341, gender = 4, hatch = 15, groups = { "water1", "water3" } },
    [342] = { species = "CRAWDAUNT", sourceDex = 342, gender = 4, hatch = 15, groups = { "water1", "water3" } },
    [343] = { species = "BALTOY", sourceDex = 343, gender = -1, hatch = 20, groups = { "mineral" } },
    [344] = { species = "CLAYDOL", sourceDex = 344, gender = -1, hatch = 20, groups = { "mineral" } },
    [345] = { species = "LILEEP", sourceDex = 345, gender = 1, hatch = 30, groups = { "water3" } },
    [346] = { species = "CRADILY", sourceDex = 346, gender = 1, hatch = 30, groups = { "water3" } },
    [347] = { species = "ANORITH", sourceDex = 347, gender = 1, hatch = 30, groups = { "water3" } },
    [348] = { species = "ARMALDO", sourceDex = 348, gender = 1, hatch = 30, groups = { "water3" } },
    [349] = { species = "FEEBAS", sourceDex = 349, gender = 4, hatch = 20, groups = { "water1", "dragon" } },
    [350] = { species = "MILOTIC", sourceDex = 350, gender = 4, hatch = 20, groups = { "water1", "dragon" } },
    [351] = { species = "CASTFORM", sourceDex = 351, gender = 4, hatch = 25, groups = { "fairy", "indeterminate" } },
    [352] = { species = "KECLEON", sourceDex = 352, gender = 4, hatch = 20, groups = { "ground" } },
    [353] = { species = "SHUPPET", sourceDex = 353, gender = 4, hatch = 25, groups = { "indeterminate" } },
    [354] = { species = "BANETTE", sourceDex = 354, gender = 4, hatch = 25, groups = { "indeterminate" } },
    [355] = { species = "DUSKULL", sourceDex = 355, gender = 4, hatch = 25, groups = { "indeterminate" } },
    [356] = { species = "DUSCLOPS", sourceDex = 356, gender = 4, hatch = 25, groups = { "indeterminate" } },
    [357] = { species = "TROPIUS", sourceDex = 357, gender = 4, hatch = 25, groups = { "monster", "plant" } },
    [358] = { species = "CHIMECHO", sourceDex = 358, gender = 4, hatch = 25, groups = { "indeterminate" } },
    [359] = { species = "ABSOL", sourceDex = 359, gender = 4, hatch = 25, groups = { "ground" } },
    [279] = { species = "WYNAUT", sourceDex = 360, gender = 4, hatch = 20, groups = { "no-eggs" } },
    [361] = { species = "SNORUNT", sourceDex = 361, gender = 4, hatch = 20, groups = { "fairy", "mineral" } },
    [362] = { species = "GLALIE", sourceDex = 362, gender = 4, hatch = 20, groups = { "fairy", "mineral" } },
    [363] = { species = "SPHEAL", sourceDex = 363, gender = 4, hatch = 20, groups = { "water1", "ground" } },
    [364] = { species = "SEALEO", sourceDex = 364, gender = 4, hatch = 20, groups = { "water1", "ground" } },
    [365] = { species = "WALREIN", sourceDex = 365, gender = 4, hatch = 20, groups = { "water1", "ground" } },
    [366] = { species = "CLAMPERL", sourceDex = 366, gender = 4, hatch = 20, groups = { "water1" } },
    [367] = { species = "HUNTAIL", sourceDex = 367, gender = 4, hatch = 20, groups = { "water1" } },
    [368] = { species = "GOREBYSS", sourceDex = 368, gender = 4, hatch = 20, groups = { "water1" } },
    [369] = { species = "RELICANTH", sourceDex = 369, gender = 1, hatch = 40, groups = { "water1", "water2" } },
    [370] = { species = "LUVDISC", sourceDex = 370, gender = 6, hatch = 20, groups = { "water2" } },
    [371] = { species = "BAGON", sourceDex = 371, gender = 4, hatch = 40, groups = { "dragon" } },
    [372] = { species = "SHELGON", sourceDex = 372, gender = 4, hatch = 40, groups = { "dragon" } },
    [373] = { species = "SALAMENCE", sourceDex = 373, gender = 4, hatch = 40, groups = { "dragon" } },
    [374] = { species = "BELDUM", sourceDex = 374, gender = -1, hatch = 40, groups = { "mineral" } },
    [375] = { species = "METANG", sourceDex = 375, gender = -1, hatch = 40, groups = { "mineral" } },
    [376] = { species = "METAGROSS", sourceDex = 376, gender = -1, hatch = 40, groups = { "mineral" } },
    [377] = { species = "REGIROCK", sourceDex = 377, gender = -1, hatch = 80, groups = { "no-eggs" } },
    [378] = { species = "REGICE", sourceDex = 378, gender = -1, hatch = 80, groups = { "no-eggs" } },
    [379] = { species = "REGISTEEL", sourceDex = 379, gender = -1, hatch = 80, groups = { "no-eggs" } },
    [380] = { species = "LATIAS", sourceDex = 380, gender = 8, hatch = 120, groups = { "no-eggs" } },
    [381] = { species = "LATIOS", sourceDex = 381, gender = 0, hatch = 120, groups = { "no-eggs" } },
    [382] = { species = "KYOGRE", sourceDex = 382, gender = -1, hatch = 120, groups = { "no-eggs" } },
    [383] = { species = "GROUDON", sourceDex = 383, gender = -1, hatch = 120, groups = { "no-eggs" } },
    [384] = { species = "RAYQUAZA", sourceDex = 384, gender = -1, hatch = 120, groups = { "no-eggs" } },
    [385] = { species = "JIRACHI", sourceDex = 385, gender = -1, hatch = 120, groups = { "no-eggs" } },
    [386] = { species = "DEOXYS", sourceDex = 386, gender = -1, hatch = 120, groups = { "no-eggs" } },
  },
  eggMoves = {
    [252] = { species = "TREECKO", moves = { "RAZOR_WIND", "DOUBLE_KICK", "LEECH_SEED", "DRAGON_BREATH", "SYNTHESIS", "CRUNCH", "ENDEAVOR", "MUD_SPORT", "CRUSH_CLAW", "GRASS_WHISTLE", "BULLET_SEED", "MAGICAL_LEAF", "NATURAL_GIFT", "WORRY_SEED", "LEAF_STORM", "GRASSY_TERRAIN" } },
    [253] = { species = "GROVYLE", moves = {  } },
    [254] = { species = "SCEPTILE", moves = {  } },
    [255] = { species = "TORCHIC", moves = { "LOW_KICK", "COUNTER", "AGILITY", "CURSE", "REVERSAL", "ENDURE", "BATON_PASS", "SMELLING_SALTS", "FEATHER_DANCE", "CRUSH_CLAW", "FEINT", "LAST_RESORT", "NIGHT_SLASH", "FLAME_BURST" } },
    [256] = { species = "COMBUSKEN", moves = {  } },
    [257] = { species = "BLAZIKEN", moves = {  } },
    [258] = { species = "MUDKIP", moves = { "STOMP", "DOUBLE_EDGE", "BITE", "COUNTER", "BARRIER", "SLUDGE", "CURSE", "MIRROR_COAT", "ANCIENTPOWER", "WHIRLPOOL", "UPROAR", "YAWN", "REFRESH", "ICE_BALL", "AVALANCHE", "MUD_BOMB", "WIDE_GUARD" } },
    [259] = { species = "MARSHTOMP", moves = {  } },
    [260] = { species = "SWAMPERT", moves = {  } },
    [3261] = { species = "POOCHYENA", moves = { "LEER", "SLEEP_TALK", "YAWN", "SNATCH", "POISON_FANG", "ASTONISH", "COVET", "ME_FIRST", "SUCKER_PUNCH", "THUNDER_FANG", "ICE_FANG", "FIRE_FANG", "PLAY_ROUGH" } },
    [3262] = { species = "MIGHTYENA", moves = {  } },
    [3263] = { species = "ZIGZAGOON", moves = { "MUD_SLAP", "CHARM", "SLEEP_TALK", "PURSUIT", "EXTREMESPEED", "HELPING_HAND", "TRICK", "TICKLE", "ROCK_CLIMB", "SIMPLE_BEAM" } },
    [3264] = { species = "LINOONE", moves = {  } },
    [3265] = { species = "WURMPLE", moves = {  } },
    [3266] = { species = "SILCOON", moves = {  } },
    [3267] = { species = "BEAUTIFLY", moves = {  } },
    [3268] = { species = "CASCOON", moves = {  } },
    [3269] = { species = "DUSTOX", moves = {  } },
    [3270] = { species = "LOTAD", moves = { "WATER_GUN", "COUNTER", "LEECH_SEED", "RAZOR_LEAF", "FLAIL", "GIGA_DRAIN", "SWEET_SCENT", "SYNTHESIS", "TEETER_DANCE", "TICKLE" } },
    [3271] = { species = "LOMBRE", moves = {  } },
    [3272] = { species = "LUDICOLO", moves = {  } },
    [3273] = { species = "SEEDOT", moves = { "RAZOR_WIND", "TAKE_DOWN", "LEECH_SEED", "QUICK_ATTACK", "AMNESIA", "BEAT_UP", "BULLET_SEED", "POWER_SWAP", "WORRY_SEED", "NASTY_PLOT", "DEFOG", "FOUL_PLAY", "GRASSY_TERRAIN" } },
    [3274] = { species = "NUZLEAF", moves = {  } },
    [3275] = { species = "SHIFTRY", moves = {  } },
    [3276] = { species = "TAILLOW", moves = { "WHIRLWIND", "SUPERSONIC", "RAGE", "MIRROR_MOVE", "SKY_ATTACK", "STEEL_WING", "PURSUIT", "REFRESH", "ROOST", "BRAVE_BIRD", "DEFOG", "HURRICANE", "BOOMBURST" } },
    [3277] = { species = "SWELLOW", moves = {  } },
    [3278] = { species = "WINGULL", moves = { "GUST", "MIST", "AGILITY", "TWISTER", "KNOCK_OFF", "WATER_SPORT", "ROOST", "BRINE", "AQUA_RING", "WIDE_GUARD", "SOAK" } },
    [3279] = { species = "PELIPPER", moves = {  } },
    [280] = { species = "RALTS", moves = { "DISABLE", "CONFUSE_RAY", "DESTINY_BOND", "MEAN_LOOK", "ENCORE", "MEMENTO", "SKILL_SWAP", "GRUDGE", "SHADOW_SNEAK", "SYNCHRONOISE", "ALLY_SWITCH", "MISTY_TERRAIN" } },
    [281] = { species = "KIRLIA", moves = {  } },
    [282] = { species = "GARDEVOIR", moves = {  } },
    [283] = { species = "SURSKIT", moves = { "HYDRO_PUMP", "PSYBEAM", "MIND_READER", "FORESIGHT", "ENDURE", "SIGNAL_BEAM", "MUD_SHOT", "BUG_BITE", "AQUA_JET", "POWER_SPLIT", "FELL_STINGER", "LUNGE" } },
    [284] = { species = "MASQUERAIN", moves = {  } },
    [285] = { species = "SHROOMISH", moves = { "CHARM", "FOCUS_PUNCH", "HELPING_HAND", "FAKE_TEARS", "BULLET_SEED", "WAKE_UP_SLAP", "NATURAL_GIFT", "WORRY_SEED", "SEED_BOMB", "DRAIN_PUNCH" } },
    [286] = { species = "BRELOOM", moves = {  } },
    [287] = { species = "SLAKOTH", moves = { "BODY_SLAM", "SLASH", "SNORE", "CURSE", "SLEEP_TALK", "PURSUIT", "CRUSH_CLAW", "TICKLE", "HAMMER_ARM", "NIGHT_SLASH", "AFTER_YOU" } },
    [288] = { species = "VIGOROTH", moves = {  } },
    [289] = { species = "SLAKING", moves = {  } },
    [290] = { species = "NINCADA", moves = { "GUST", "FEINT_ATTACK", "ENDURE", "SILVER_WIND", "NIGHT_SLASH", "BUG_BUZZ", "BUG_BITE", "FINAL_GAMBIT" } },
    [291] = { species = "NINJASK", moves = {  } },
    [292] = { species = "SHEDINJA", moves = {  } },
    [293] = { species = "WHISMUR", moves = { "WHIRLWIND", "TAKE_DOWN", "SMOKESCREEN", "SNORE", "SMELLING_SALTS", "ENDEAVOR", "FAKE_TEARS", "EXTRASENSORY", "HAMMER_ARM", "CIRCLE_THROW", "DISARMING_VOICE" } },
    [294] = { species = "LOUDRED", moves = {  } },
    [295] = { species = "EXPLOUD", moves = {  } },
    [296] = { species = "MAKUHITA", moves = { "COUNTER", "FEINT_ATTACK", "FORESIGHT", "DETECT", "DYNAMIC_PUNCH", "CROSS_CHOP", "FOCUS_PUNCH", "HELPING_HAND", "REVENGE", "WAKE_UP_SLAP", "FEINT", "BULLET_PUNCH", "WIDE_GUARD", "CHIP_AWAY" } },
    [297] = { species = "HARIYAMA", moves = {  } },
    [278] = { species = "AZURILL", moves = { "SLAM", "BODY_SLAM", "SING", "ENCORE", "REFRESH", "CAMOUFLAGE", "FAKE_TEARS", "TICKLE", "MUDDY_WATER", "WATER_SPORT", "COPYCAT", "SOAK" } },
    [299] = { species = "NOSEPASS", moves = { "DOUBLE_EDGE", "ENDURE", "ROLLOUT", "MAGNITUDE", "BLOCK", "STEALTH_ROCK", "WIDE_GUARD" } },
    [300] = { species = "SKITTY", moves = { "BATON_PASS", "FAKE_OUT", "UPROAR", "HELPING_HAND", "WISH", "FAKE_TEARS", "TICKLE", "COSMIC_POWER", "LAST_RESORT", "SUCKER_PUNCH", "MUD_BOMB", "ZEN_HEADBUTT", "CAPTIVATE", "SIMPLE_BEAM" } },
    [301] = { species = "DELCATTY", moves = {  } },
    [302] = { species = "SABLEYE", moves = { "RECOVER", "MEAN_LOOK", "MOONLIGHT", "FLATTER", "TRICK", "IMPRISON", "FEINT", "METAL_BURST", "SUCKER_PUNCH", "NASTY_PLOT", "CAPTIVATE" } },
    [303] = { species = "MAWILE", moves = { "SLAM", "SEISMIC_TOSS", "ANCIENTPOWER", "POISON_FANG", "TICKLE", "METAL_BURST", "GUARD_SWAP", "PUNISHMENT", "SUCKER_PUNCH", "THUNDER_FANG", "ICE_FANG", "FIRE_FANG", "CAPTIVATE", "MISTY_TERRAIN", "POWER_UP_PUNCH" } },
    [304] = { species = "ARON", moves = { "STOMP", "BODY_SLAM", "SCREECH", "CURSE", "REVERSAL", "SMELLING_SALTS", "SUPERPOWER", "ENDEAVOR", "DRAGON_RUSH", "IRON_HEAD", "STEALTH_ROCK", "HEAD_SMASH" } },
    [305] = { species = "LAIRON", moves = {  } },
    [306] = { species = "AGGRON", moves = {  } },
    [307] = { species = "MEDITITE", moves = { "FIRE_PUNCH", "ICE_PUNCH", "THUNDERPUNCH", "FORESIGHT", "DYNAMIC_PUNCH", "BATON_PASS", "FAKE_OUT", "SECRET_POWER", "POWER_SWAP", "GUARD_SWAP", "DRAIN_PUNCH", "BULLET_PUNCH", "PSYCHO_CUT", "QUICK_GUARD" } },
    [308] = { species = "MEDICHAM", moves = {  } },
    [309] = { species = "ELECTRIKE", moves = { "HEADBUTT", "SWIFT", "CURSE", "CRUNCH", "UPROAR", "SHOCK_WAVE", "SWITCHEROO", "THUNDER_FANG", "ICE_FANG", "FIRE_FANG", "DISCHARGE", "FLAME_BURST", "ELECTRO_BALL", "EERIE_IMPULSE" } },
    [310] = { species = "MANECTRIC", moves = {  } },
    [311] = { species = "PLUSLE", moves = { "SING", "SWEET_KISS", "CHARM", "WISH", "FAKE_TEARS", "LUCKY_CHANT", "DISCHARGE", "TEARFUL_LOOK" } },
    [312] = { species = "MINUN", moves = { "SING", "SWEET_KISS", "CHARM", "WISH", "FAKE_TEARS", "LUCKY_CHANT", "DISCHARGE", "TEARFUL_LOOK" } },
    [313] = { species = "VOLBEAT", moves = { "SEISMIC_TOSS", "DIZZY_PUNCH", "BATON_PASS", "ENCORE", "TRICK", "SILVER_WIND", "BUG_BUZZ", "LUNGE" } },
    [314] = { species = "ILLUMISE", moves = { "GROWTH", "CONFUSE_RAY", "BATON_PASS", "ENCORE", "AROMATHERAPY", "FAKE_TEARS", "SILVER_WIND", "BUG_BUZZ", "CAPTIVATE" } },
    [315] = { species = "ROSELIA", moves = { "PIN_MISSILE", "RAZOR_LEAF", "SLEEP_POWDER", "MIND_READER", "COTTON_SPORE", "SPIKES", "GIGA_DRAIN", "SYNTHESIS", "GRASS_WHISTLE", "BULLET_SEED", "NATURAL_GIFT", "SEED_BOMB", "LEAF_STORM", "POWER_WHIP" } },
    [316] = { species = "GULPIN", moves = { "SMOG", "ACID_ARMOR", "CURSE", "MUD_SLAP", "DESTINY_BOND", "PAIN_SPLIT", "GUNK_SHOT", "VENOM_DRENCH" } },
    [317] = { species = "SWALOT", moves = {  } },
    [318] = { species = "CARVANHA", moves = { "THRASH", "DOUBLE_EDGE", "HYDRO_PUMP", "SWIFT", "DESTINY_BOND", "ANCIENTPOWER", "BRINE", "PSYCHIC_FANGS" } },
    [319] = { species = "SHARPEDO", moves = {  } },
    [320] = { species = "WAILMER", moves = { "BODY_SLAM", "THRASH", "DOUBLE_EDGE", "FISSURE", "DEFENSE_CURL", "SNORE", "CURSE", "SLEEP_TALK", "TICKLE", "AQUA_RING", "ZEN_HEADBUTT", "SOAK", "CLEAR_SMOG" } },
    [321] = { species = "WAILORD", moves = {  } },
    [322] = { species = "NUMEL", moves = { "STOMP", "BODY_SLAM", "GROWTH", "DEFENSE_CURL", "SCARY_FACE", "ENDURE", "ROLLOUT", "ANCIENTPOWER", "STOCKPILE", "SPIT_UP", "SWALLOW", "HEAT_WAVE", "YAWN", "HOWL", "MUD_BOMB", "IRON_HEAD", "HEAVY_SLAM" } },
    [323] = { species = "CAMERUPT", moves = {  } },
    [324] = { species = "TORKOAL", moves = { "FISSURE", "SKULL_BASH", "ENDURE", "SLEEP_TALK", "SUPERPOWER", "YAWN", "ERUPTION", "FLAME_BURST", "CLEAR_SMOG" } },
    [325] = { species = "SPOINK", moves = { "WHIRLWIND", "AMNESIA", "ENDURE", "MIRROR_COAT", "FUTURE_SIGHT", "TRICK", "SKILL_SWAP", "EXTRASENSORY", "LUCKY_CHANT", "ZEN_HEADBUTT", "SIMPLE_BEAM" } },
    [326] = { species = "GRUMPIG", moves = {  } },
    [327] = { species = "SPINDA", moves = { "DISABLE", "ICY_WIND", "BATON_PASS", "ENCORE", "RAPID_SPIN", "FAKE_OUT", "SMELLING_SALTS", "TRICK", "ROLE_PLAY", "WISH", "ASSIST", "FAKE_TEARS", "WATER_PULSE", "PSYCHO_SHIFT", "PSYCHO_CUT", "GUARD_SPLIT", "SPOTLIGHT" } },
    [328] = { species = "TRAPINCH", moves = { "GUST", "QUICK_ATTACK", "FOCUS_ENERGY", "FLAIL", "ENDURE", "FURY_CUTTER", "SIGNAL_BEAM", "MUD_SHOT", "EARTH_POWER", "BUG_BITE" } },
    [329] = { species = "VIBRAVA", moves = {  } },
    [330] = { species = "FLYGON", moves = {  } },
    [331] = { species = "CACNEA", moves = { "DISABLE", "ACID", "LOW_KICK", "COUNTER", "DYNAMIC_PUNCH", "SMELLING_SALTS", "TEETER_DANCE", "GRASS_WHISTLE", "BLOCK", "MAGICAL_LEAF", "WORRY_SEED", "SEED_BOMB", "SWITCHEROO", "NASTY_PLOT", "BELCH", "ROTOTILLER", "FELL_STINGER", "POWER_UP_PUNCH" } },
    [332] = { species = "CACTURNE", moves = {  } },
    [333] = { species = "SWABLU", moves = { "AGILITY", "RAGE", "HAZE", "STEEL_WING", "PURSUIT", "FEATHER_DANCE", "HYPER_VOICE", "ROOST", "POWER_SWAP", "DRAGON_RUSH", "PLAY_ROUGH" } },
    [334] = { species = "ALTARIA", moves = {  } },
    [335] = { species = "ZANGOOSE", moves = { "RAZOR_WIND", "DOUBLE_KICK", "DISABLE", "COUNTER", "FURY_SWIPES", "CURSE", "FLAIL", "BELLY_DRUM", "IRON_TAIL", "METAL_CLAW", "FEINT", "NIGHT_SLASH", "DOUBLE_HIT", "QUICK_GUARD", "FINAL_GAMBIT" } },
    [336] = { species = "SEVIPER", moves = { "BODY_SLAM", "SCARY_FACE", "IRON_TAIL", "STOCKPILE", "SPIT_UP", "SWALLOW", "ASSURANCE", "WRING_OUT", "PUNISHMENT", "NIGHT_SLASH", "SWITCHEROO", "FINAL_GAMBIT" } },
    [337] = { species = "LUNATONE", moves = {  } },
    [338] = { species = "SOLROCK", moves = {  } },
    [339] = { species = "BARBOACH", moves = { "TAKE_DOWN", "THRASH", "HYDRO_PUMP", "FLAIL", "SPARK", "WHIRLPOOL", "MUDDY_WATER", "MUD_SHOT", "DRAGON_DANCE", "EARTH_POWER" } },
    [340] = { species = "WHISCASH", moves = {  } },
    [341] = { species = "CORPHISH", moves = { "BODY_SLAM", "DOUBLE_EDGE", "METAL_CLAW", "ANCIENTPOWER", "SUPERPOWER", "KNOCK_OFF", "ENDEAVOR", "MUD_SPORT", "DRAGON_DANCE", "TRUMP_CARD", "SWITCHEROO", "AQUA_JET", "CHIP_AWAY" } },
    [342] = { species = "CRAWDAUNT", moves = {  } },
    [343] = { species = "BALTOY", moves = {  } },
    [344] = { species = "CLAYDOL", moves = {  } },
    [345] = { species = "LILEEP", moves = { "MEGA_DRAIN", "RECOVER", "BARRIER", "CURSE", "ENDURE", "MIRROR_COAT", "TICKLE", "WRING_OUT", "STEALTH_ROCK" } },
    [346] = { species = "CRADILY", moves = {  } },
    [347] = { species = "ANORITH", moves = { "SAND_ATTACK", "SCREECH", "CURSE", "RAPID_SPIN", "KNOCK_OFF", "IRON_DEFENSE", "WATER_PULSE", "CROSS_POISON", "AQUA_JET" } },
    [348] = { species = "ARMALDO", moves = {  } },
    [349] = { species = "FEEBAS", moves = { "MIST", "HYPNOSIS", "CONFUSE_RAY", "HAZE", "DRAGON_BREATH", "IRON_TAIL", "MIRROR_COAT", "MUD_SPORT", "TICKLE", "BRINE", "DRAGON_PULSE", "CAPTIVATE" } },
    [350] = { species = "MILOTIC", moves = {  } },
    [351] = { species = "CASTFORM", moves = { "DISABLE", "AMNESIA", "FUTURE_SIGHT", "COSMIC_POWER", "LUCKY_CHANT", "GUARD_SWAP", "OMINOUS_WIND", "CLEAR_SMOG", "HEX", "REFLECT_TYPE" } },
    [352] = { species = "KECLEON", moves = { "DISABLE", "RECOVER", "DIZZY_PUNCH", "FAKE_OUT", "TRICK", "MAGIC_COAT", "SKILL_SWAP", "SNATCH", "CAMOUFLAGE", "NASTY_PLOT", "FOUL_PLAY", "POWER_UP_PUNCH" } },
    [353] = { species = "SHUPPET", moves = { "DISABLE", "CONFUSE_RAY", "FORESIGHT", "DESTINY_BOND", "PURSUIT", "IMPRISON", "ASTONISH", "SHADOW_SNEAK", "GUNK_SHOT", "OMINOUS_WIND", "PHANTOM_FORCE" } },
    [354] = { species = "BANETTE", moves = {  } },
    [355] = { species = "DUSKULL", moves = { "HAZE", "FEINT_ATTACK", "DESTINY_BOND", "PAIN_SPLIT", "MEMENTO", "SKILL_SWAP", "IMPRISON", "GRUDGE", "DARK_PULSE", "OMINOUS_WIND" } },
    [356] = { species = "DUSCLOPS", moves = {  } },
    [357] = { species = "TROPIUS", moves = { "RAZOR_WIND", "SLAM", "HEADBUTT", "LEECH_SEED", "CURSE", "SYNTHESIS", "NATURE_POWER", "BULLET_SEED", "LEAF_BLADE", "DRAGON_DANCE", "NATURAL_GIFT", "LEAF_STORM", "DRAGON_HAMMER" } },
    [358] = { species = "CHIMECHO", moves = { "DISABLE", "HYPNOSIS", "RECOVER", "CURSE", "PERISH_SONG", "FUTURE_SIGHT", "WISH", "SKILL_SWAP", "COSMIC_POWER", "STORED_POWER", "CRAFTY_SHIELD" } },
    [359] = { species = "ABSOL", moves = { "DOUBLE_EDGE", "CURSE", "FEINT_ATTACK", "PERISH_SONG", "MEAN_LOOK", "MEGAHORN", "BATON_PASS", "MAGIC_COAT", "ASSURANCE", "ME_FIRST", "PUNISHMENT", "SUCKER_PUNCH", "ZEN_HEADBUTT", "HEX", "PLAY_ROUGH" } },
    [279] = { species = "WYNAUT", moves = {  } },
    [361] = { species = "SNORUNT", moves = { "DISABLE", "BIDE", "SPIKES", "ROLLOUT", "WEATHER_BALL", "FAKE_TEARS", "BLOCK", "SWITCHEROO", "AVALANCHE", "HEX" } },
    [362] = { species = "GLALIE", moves = {  } },
    [363] = { species = "SPHEAL", moves = { "FISSURE", "CURSE", "BELLY_DRUM", "ROLLOUT", "SLEEP_TALK", "STOCKPILE", "SPIT_UP", "SWALLOW", "YAWN", "SIGNAL_BEAM", "WATER_SPORT", "WATER_PULSE", "AQUA_RING" } },
    [364] = { species = "SEALEO", moves = {  } },
    [365] = { species = "WALREIN", moves = {  } },
    [366] = { species = "CLAMPERL", moves = { "BODY_SLAM", "SUPERSONIC", "CONFUSE_RAY", "BARRIER", "ENDURE", "REFRESH", "MUD_SPORT", "MUDDY_WATER", "WATER_PULSE", "BRINE", "AQUA_RING" } },
    [367] = { species = "HUNTAIL", moves = {  } },
    [368] = { species = "GOREBYSS", moves = {  } },
    [369] = { species = "RELICANTH", moves = { "SKULL_BASH", "AMNESIA", "SNORE", "MUD_SLAP", "SLEEP_TALK", "MAGNITUDE", "MUDDY_WATER", "MUD_SHOT", "WATER_SPORT", "BRINE", "AQUA_TAIL", "ZEN_HEADBUTT" } },
    [370] = { species = "LUVDISC", moves = { "SUPERSONIC", "SPLASH", "MUD_SPORT", "WATER_SPORT", "BRINE", "AQUA_RING", "CAPTIVATE", "AQUA_JET", "ENTRAINMENT", "HEAL_PULSE" } },
    [371] = { species = "BAGON", moves = { "THRASH", "HYDRO_PUMP", "DRAGON_RAGE", "DEFENSE_CURL", "ENDURE", "TWISTER", "DRAGON_DANCE", "DRAGON_PULSE", "DRAGON_RUSH", "FIRE_FANG" } },
    [372] = { species = "SHELGON", moves = {  } },
    [373] = { species = "SALAMENCE", moves = {  } },
    [374] = { species = "BELDUM", moves = {  } },
    [375] = { species = "METANG", moves = {  } },
    [376] = { species = "METAGROSS", moves = {  } },
    [377] = { species = "REGIROCK", moves = {  } },
    [378] = { species = "REGICE", moves = {  } },
    [379] = { species = "REGISTEEL", moves = {  } },
    [380] = { species = "LATIAS", moves = {  } },
    [381] = { species = "LATIOS", moves = {  } },
    [382] = { species = "KYOGRE", moves = {  } },
    [383] = { species = "GROUDON", moves = {  } },
    [384] = { species = "RAYQUAZA", moves = {  } },
    [385] = { species = "JIRACHI", moves = {  } },
    [386] = { species = "DEOXYS", moves = {  } },
  },
  evolutions = {
    TREECKO = {
      { method = "LEVEL", level = 16, species = "GROVYLE" },
    },
    GROVYLE = {
      { method = "LEVEL", level = 36, species = "SCEPTILE" },
    },
    SCEPTILE = {
    },
    TORCHIC = {
      { method = "LEVEL", level = 16, species = "COMBUSKEN" },
    },
    COMBUSKEN = {
      { method = "LEVEL", level = 36, species = "BLAZIKEN" },
    },
    BLAZIKEN = {
    },
    MUDKIP = {
      { method = "LEVEL", level = 16, species = "MARSHTOMP" },
    },
    MARSHTOMP = {
      { method = "LEVEL", level = 36, species = "SWAMPERT" },
    },
    SWAMPERT = {
    },
    POOCHYENA = {
      { method = "LEVEL", level = 18, species = "MIGHTYENA" },
    },
    MIGHTYENA = {
    },
    ZIGZAGOON = {
      { method = "LEVEL", level = 20, species = "LINOONE" },
    },
    LINOONE = {
    },
    WURMPLE = {
      { method = "KA_HOENN_WURMPLE_SILCOON", level = 7, species = "SILCOON", sourceCondition = "elv_armulys" },
      { method = "KA_HOENN_WURMPLE_CASCOON", level = 7, species = "CASCOON", sourceCondition = "elv_blindalys" },
    },
    SILCOON = {
      { method = "LEVEL", level = 10, species = "BEAUTIFLY" },
    },
    BEAUTIFLY = {
    },
    CASCOON = {
      { method = "LEVEL", level = 10, species = "DUSTOX" },
    },
    DUSTOX = {
    },
    LOTAD = {
      { method = "LEVEL", level = 14, species = "LOMBRE" },
    },
    LOMBRE = {
      { method = "ITEM", item = "WATER_STONE", species = "LUDICOLO" },
    },
    LUDICOLO = {
    },
    SEEDOT = {
      { method = "LEVEL", level = 14, species = "NUZLEAF" },
    },
    NUZLEAF = {
      { method = "ITEM", item = "LEAF_STONE", species = "SHIFTRY" },
    },
    SHIFTRY = {
    },
    TAILLOW = {
      { method = "LEVEL", level = 22, species = "SWELLOW" },
    },
    SWELLOW = {
    },
    WINGULL = {
      { method = "LEVEL", level = 25, species = "PELIPPER" },
    },
    PELIPPER = {
    },
    RALTS = {
      { method = "LEVEL", level = 20, species = "KIRLIA" },
    },
    KIRLIA = {
      { method = "LEVEL", level = 30, species = "GARDEVOIR" },
      { species = "GALLADE", authority = "hevo_package" },
    },
    GARDEVOIR = {
    },
    SURSKIT = {
      { method = "LEVEL", level = 22, species = "MASQUERAIN" },
    },
    MASQUERAIN = {
    },
    SHROOMISH = {
      { method = "LEVEL", level = 23, species = "BRELOOM" },
    },
    BRELOOM = {
    },
    SLAKOTH = {
      { method = "LEVEL", level = 18, species = "VIGOROTH" },
    },
    VIGOROTH = {
      { method = "LEVEL", level = 36, species = "SLAKING" },
    },
    SLAKING = {
    },
    NINCADA = {
      { method = "LEVEL", level = 20, species = "NINJASK" },
    },
    NINJASK = {
    },
    SHEDINJA = {
    },
    WHISMUR = {
      { method = "LEVEL", level = 20, species = "LOUDRED" },
    },
    LOUDRED = {
      { method = "LEVEL", level = 40, species = "EXPLOUD" },
    },
    EXPLOUD = {
    },
    MAKUHITA = {
      { method = "LEVEL", level = 24, species = "HARIYAMA" },
    },
    HARIYAMA = {
    },
    AZURILL = {
      { method = "FRIENDSHIP", species = "MARILL", sourceLoyalty = 220 },
    },
    NOSEPASS = {
      { species = "PROBOPASS", authority = "hevo_package" },
    },
    SKITTY = {
      { method = "ITEM", item = "MOON_STONE", species = "DELCATTY" },
    },
    DELCATTY = {
    },
    SABLEYE = {
    },
    MAWILE = {
    },
    ARON = {
      { method = "LEVEL", level = 32, species = "LAIRON" },
    },
    LAIRON = {
      { method = "LEVEL", level = 42, species = "AGGRON" },
    },
    AGGRON = {
    },
    MEDITITE = {
      { method = "LEVEL", level = 37, species = "MEDICHAM" },
    },
    MEDICHAM = {
    },
    ELECTRIKE = {
      { method = "LEVEL", level = 26, species = "MANECTRIC" },
    },
    MANECTRIC = {
    },
    PLUSLE = {
    },
    MINUN = {
    },
    VOLBEAT = {
    },
    ILLUMISE = {
    },
    ROSELIA = {
      { species = "ROSERADE", authority = "hevo_package" },
    },
    GULPIN = {
      { method = "LEVEL", level = 26, species = "SWALOT" },
    },
    SWALOT = {
    },
    CARVANHA = {
      { method = "LEVEL", level = 30, species = "SHARPEDO" },
    },
    SHARPEDO = {
    },
    WAILMER = {
      { method = "LEVEL", level = 40, species = "WAILORD" },
    },
    WAILORD = {
    },
    NUMEL = {
      { method = "LEVEL", level = 33, species = "CAMERUPT" },
    },
    CAMERUPT = {
    },
    TORKOAL = {
    },
    SPOINK = {
      { method = "LEVEL", level = 32, species = "GRUMPIG" },
    },
    GRUMPIG = {
    },
    SPINDA = {
    },
    TRAPINCH = {
      { method = "LEVEL", level = 35, species = "VIBRAVA" },
    },
    VIBRAVA = {
      { method = "LEVEL", level = 45, species = "FLYGON" },
    },
    FLYGON = {
    },
    CACNEA = {
      { method = "LEVEL", level = 32, species = "CACTURNE" },
    },
    CACTURNE = {
    },
    SWABLU = {
      { method = "LEVEL", level = 35, species = "ALTARIA" },
    },
    ALTARIA = {
    },
    ZANGOOSE = {
    },
    SEVIPER = {
    },
    LUNATONE = {
    },
    SOLROCK = {
    },
    BARBOACH = {
      { method = "LEVEL", level = 30, species = "WHISCASH" },
    },
    WHISCASH = {
    },
    CORPHISH = {
      { method = "LEVEL", level = 30, species = "CRAWDAUNT" },
    },
    CRAWDAUNT = {
    },
    BALTOY = {
      { method = "LEVEL", level = 36, species = "CLAYDOL" },
    },
    CLAYDOL = {
    },
    LILEEP = {
      { method = "LEVEL", level = 40, species = "CRADILY" },
    },
    CRADILY = {
    },
    ANORITH = {
      { method = "LEVEL", level = 40, species = "ARMALDO" },
    },
    ARMALDO = {
    },
    FEEBAS = {
      { method = "ITEM", item = "PRISM_SCALE", species = "MILOTIC", adaptedFrom = "trade_with_held_item" },
    },
    MILOTIC = {
    },
    CASTFORM = {
    },
    KECLEON = {
    },
    SHUPPET = {
      { method = "LEVEL", level = 37, species = "BANETTE" },
    },
    BANETTE = {
    },
    DUSKULL = {
      { method = "LEVEL", level = 37, species = "DUSCLOPS" },
    },
    DUSCLOPS = {
      { species = "DUSKNOIR", authority = "hevo_package" },
    },
    TROPIUS = {
    },
    CHIMECHO = {
    },
    ABSOL = {
    },
    WYNAUT = {
      { method = "LEVEL", level = 15, species = "WOBBUFFET" },
    },
    SNORUNT = {
      { method = "LEVEL", level = 42, species = "GLALIE" },
      { species = "FROSLASS", authority = "hevo_package" },
    },
    GLALIE = {
    },
    SPHEAL = {
      { method = "LEVEL", level = 32, species = "SEALEO" },
    },
    SEALEO = {
      { method = "LEVEL", level = 44, species = "WALREIN" },
    },
    WALREIN = {
    },
    CLAMPERL = {
      { method = "ITEM", item = "DEEP_SEA_TOOTH", species = "HUNTAIL", adaptedFrom = "trade_with_held_item" },
      { method = "ITEM", item = "DEEP_SEA_SCALE", species = "GOREBYSS", adaptedFrom = "trade_with_held_item" },
    },
    HUNTAIL = {
    },
    GOREBYSS = {
    },
    RELICANTH = {
    },
    LUVDISC = {
    },
    BAGON = {
      { method = "LEVEL", level = 30, species = "SHELGON" },
    },
    SHELGON = {
      { method = "LEVEL", level = 50, species = "SALAMENCE" },
    },
    SALAMENCE = {
    },
    BELDUM = {
      { method = "LEVEL", level = 20, species = "METANG" },
    },
    METANG = {
      { method = "LEVEL", level = 45, species = "METAGROSS" },
    },
    METAGROSS = {
    },
    REGIROCK = {
    },
    REGICE = {
    },
    REGISTEEL = {
    },
    LATIAS = {
    },
    LATIOS = {
    },
    KYOGRE = {
    },
    GROUDON = {
    },
    RAYQUAZA = {
    },
    JIRACHI = {
    },
    DEOXYS = {
    },
  },
  shedinja = { source = "NINCADA", evolved = "NINJASK",
    bonus = "SHEDINJA", level = 20, ball = "POKE_BALL" },
}
