-- KASC 6.7: later-generation baby forms whose complete evolution family
-- returns to a Generation-I--III species.  No Generation-V or -VI baby form
-- satisfies that rule; the supported ceiling remains explicit so a future
-- data import cannot silently widen ZUFALL GLOBAL.

return {
  generationCeiling = 6,
  order = {
    "BUDEW", "CHINGLING", "BONSLY", "MIME_JR",
    "HAPPINY", "MUNCHLAX", "MANTYKE",
  },
  species = {
    BUDEW = {
      id="BUDEW", sourceDex=406, originGeneration=4,
      names={ en="BUDEW", de="KNOSPI" }, parent="ROSELIA",
      evolution={ method="KA_BABY_FRIENDSHIP_DAY", species="ROSELIA" },
      types={ "GRASS", "POISON" },
      baseStats={ hp=40, attack=30, defense=35, speed=55, special=70 },
      catchRate=255, baseExp=56, growthRate="MEDIUM_SLOW",
      level1Moves={ "ABSORB", "GROWTH" },
      learnset={ {level=4,move="WATER_SPORT"}, {level=7,move="STUN_SPORE"},
        {level=10,move="MEGA_DRAIN"}, {level=13,move="SYNTHESIS"} },
      tmhm={ "TOXIC", "MEGA_DRAIN", "SOLARBEAM", "MIMIC", "REST", "CUT" },
      heightM=0.2, weightKg=1.2,
    },
    CHINGLING = {
      id="CHINGLING", sourceDex=433, originGeneration=4,
      names={ en="CHINGLING", de="KLINGPLIM" }, parent="CHIMECHO",
      evolution={ method="KA_BABY_FRIENDSHIP_NIGHT", species="CHIMECHO" },
      types={ "PSYCHIC_TYPE" },
      baseStats={ hp=45, attack=30, defense=50, speed=45, special=65 },
      catchRate=120, baseExp=57, growthRate="FAST",
      level1Moves={ "WRAP", "GROWL" },
      learnset={ {level=6,move="ASTONISH"}, {level=9,move="CONFUSION"},
        {level=14,move="UPROAR"} },
      tmhm={ "TOXIC", "PSYCHIC_M", "MIMIC", "REFLECT", "REST", "FLASH" },
      heightM=0.2, weightKg=0.6,
    },
    BONSLY = {
      id="BONSLY", sourceDex=438, originGeneration=4,
      names={ en="BONSLY", de="MOBAI" }, parent="SUDOWOODO",
      evolution={ method="KA_BABY_MIMIC", species="SUDOWOODO" },
      types={ "ROCK" },
      baseStats={ hp=50, attack=80, defense=95, speed=10, special=45 },
      catchRate=255, baseExp=58, growthRate="MEDIUM_FAST",
      level1Moves={ "TACKLE", "HARDEN" },
      learnset={ {level=8,move="ROCK_THROW"}, {level=16,move="MIMIC"} },
      tmhm={ "TOXIC", "BODY_SLAM", "DIG", "MIMIC", "REST", "ROCK_SLIDE" },
      heightM=0.5, weightKg=15.0,
    },
    MIME_JR = {
      id="MIME_JR", sourceDex=439, originGeneration=4,
      names={ en="MIME JR.", de="PANTIMIMI" }, parent="MR_MIME",
      evolution={ method="KA_BABY_MIMIC", species="MR_MIME" },
      types={ "PSYCHIC_TYPE", "FAIRY" },
      baseStats={ hp=20, attack=25, defense=45, speed=60, special=90 },
      catchRate=145, baseExp=62, growthRate="MEDIUM_FAST",
      level1Moves={ "BARRIER", "CONFUSION" },
      learnset={ {level=8,move="MEDITATE"}, {level=16,move="MIMIC"} },
      tmhm={ "TOXIC", "PSYCHIC_M", "MIMIC", "REFLECT", "REST", "FLASH" },
      heightM=0.6, weightKg=13.0,
    },
    HAPPINY = {
      id="HAPPINY", sourceDex=440, originGeneration=4,
      names={ en="HAPPINY", de="WONNEIRA" }, parent="CHANSEY",
      evolution={ method="KA_HAPPINY_OVAL_DAY", species="CHANSEY" },
      types={ "NORMAL" },
      baseStats={ hp=100, attack=5, defense=5, speed=30, special=35 },
      catchRate=130, baseExp=110, growthRate="FAST",
      level1Moves={ "POUND", "GROWL" },
      learnset={ {level=8,move="CHARM"}, {level=16,move="REFRESH"} },
      tmhm={ "TOXIC", "BODY_SLAM", "PSYCHIC_M", "MIMIC", "REST" },
      heightM=0.6, weightKg=24.4,
    },
    MUNCHLAX = {
      id="MUNCHLAX", sourceDex=446, originGeneration=4,
      names={ en="MUNCHLAX", de="MAMPFAXO" }, parent="SNORLAX",
      evolution={ method="KA_BABY_FRIENDSHIP", species="SNORLAX" },
      types={ "NORMAL" },
      baseStats={ hp=135, attack=85, defense=40, speed=5, special=85 },
      catchRate=50, baseExp=78, growthRate="SLOW",
      level1Moves={ "TACKLE", "METRONOME" },
      learnset={ {level=9,move="AMNESIA"}, {level=17,move="BODY_SLAM"} },
      tmhm={ "TOXIC", "BODY_SLAM", "EARTHQUAKE", "PSYCHIC_M", "MIMIC", "REST" },
      heightM=0.6, weightKg=105.0,
    },
    MANTYKE = {
      id="MANTYKE", sourceDex=458, originGeneration=4,
      names={ en="MANTYKE", de="MANTIRPS" }, parent="MANTINE",
      evolution={ method="KA_BABY_REMORAID", species="MANTINE" },
      types={ "WATER", "FLYING" },
      baseStats={ hp=45, attack=20, defense=50, speed=50, special=120 },
      catchRate=25, baseExp=69, growthRate="SLOW",
      level1Moves={ "TACKLE", "BUBBLE" },
      learnset={ {level=10,move="SUPERSONIC"}, {level=16,move="WING_ATTACK"} },
      tmhm={ "TOXIC", "ICE_BEAM", "BLIZZARD", "MIMIC", "REST", "SURF" },
      heightM=1.0, weightKg=65.0,
    },
  },
}
