-- Generated by tools/install_mega_crystal_animations.py.
-- Durations are milliseconds after Crystal-style frame reduction.
return {
  ["CHARIZARD_X"] = {
    normal = { 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200 },
    shiny = { 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 150 },
  },
}
