-- Generated by tools/install_non_crystal_hd_animations.py.
-- Gen-II-Neo VASC fronts only; classic 2D, #001-251, backs,
-- Mega forms and Gorochu remain under their existing owners.
return {
  ["252"] = {
    species="TREECKO", sourceDex=252,
    root="assets/non_crystal_hd_67/front/normal/252",
    scale=1.5, durations={ 20, 40, 80, 80, 220, 80, 100, 100, 60, 60, 60, 60, 60, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/252",
        scale=1.5, durations={ 20, 40, 80, 80, 220, 80, 100, 100, 60, 60, 60, 60, 60, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/252",
        scale=1.5, durations={ 20, 40, 80, 80, 220, 80, 100, 100, 60, 60, 60, 60, 60, 60, 1000 },
      },
    },
  },
  ["253"] = {
    species="GROVYLE", sourceDex=253,
    root="assets/non_crystal_hd_67/front/normal/253",
    scale=1.5, durations={ 20, 140, 100, 190, 100, 40, 60, 60, 80, 40, 60, 80, 80, 60, 60, 60, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/253",
        scale=1.5, durations={ 20, 140, 100, 190, 100, 40, 60, 60, 80, 40, 60, 80, 80, 60, 60, 60, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/253",
        scale=1.5, durations={ 20, 140, 100, 190, 100, 40, 60, 60, 80, 40, 60, 80, 80, 60, 60, 60, 60, 1000 },
      },
    },
  },
  ["254"] = {
    species="SCEPTILE", sourceDex=254,
    root="assets/non_crystal_hd_67/front/normal/254",
    scale=1.5, durations={ 20, 50, 160, 80, 60, 60, 60, 60, 80, 60, 60, 60, 60, 60, 60, 60, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/254",
        scale=1.5, durations={ 20, 50, 160, 80, 60, 60, 60, 60, 80, 60, 60, 60, 60, 60, 60, 60, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/254",
        scale=1.5, durations={ 20, 50, 160, 80, 60, 60, 60, 60, 80, 60, 60, 60, 60, 60, 60, 60, 60, 1000 },
      },
    },
  },
  ["255"] = {
    species="TORCHIC", sourceDex=255,
    root="assets/non_crystal_hd_67/front/normal/255",
    scale=1.5, durations={ 20, 80, 60, 300, 60, 60, 80, 80, 80, 80, 80, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/255",
        scale=1.5, durations={ 20, 80, 60, 300, 60, 60, 80, 80, 80, 80, 80, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/255",
        scale=1.5, durations={ 20, 80, 60, 300, 60, 60, 80, 80, 80, 80, 80, 1000 },
      },
    },
  },
  ["256"] = {
    species="COMBUSKEN", sourceDex=256,
    root="assets/non_crystal_hd_67/front/normal/256",
    scale=1.5, durations={ 20, 40, 60, 300, 60, 60, 40, 80, 80, 80, 60, 80, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/256",
        scale=1.5, durations={ 20, 40, 60, 300, 60, 60, 40, 80, 80, 80, 60, 80, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/256",
        scale=1.5, durations={ 20, 40, 60, 300, 60, 60, 40, 80, 80, 80, 60, 80, 60, 1000 },
      },
    },
  },
  ["257"] = {
    species="BLAZIKEN", sourceDex=257,
    root="assets/non_crystal_hd_67/front/normal/257",
    scale=1.5, durations={ 20, 80, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 60, 60, 60, 60, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/257",
        scale=1.5, durations={ 20, 80, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 60, 60, 60, 60, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/257",
        scale=1.5, durations={ 20, 80, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 60, 60, 60, 60, 60, 1000 },
      },
    },
  },
  ["258"] = {
    species="MUDKIP", sourceDex=258,
    root="assets/non_crystal_hd_67/front/normal/258",
    scale=1.5, durations={ 20, 100, 80, 80, 80, 80, 80, 80, 70, 70, 70, 70, 70, 70, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/258",
        scale=1.5, durations={ 20, 100, 80, 80, 80, 80, 80, 80, 70, 70, 70, 70, 70, 70, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/258",
        scale=1.5, durations={ 20, 100, 80, 80, 80, 80, 80, 80, 70, 70, 70, 70, 70, 70, 1000 },
      },
    },
  },
  ["259"] = {
    species="MARSHTOMP", sourceDex=259,
    root="assets/non_crystal_hd_67/front/normal/259",
    scale=1.5, durations={ 20, 80, 220, 140, 80, 80, 100, 100, 80, 80, 80, 60, 80, 60, 60, 60, 60, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/259",
        scale=1.5, durations={ 20, 80, 220, 140, 80, 80, 100, 100, 80, 80, 80, 60, 80, 60, 60, 60, 60, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/259",
        scale=1.5, durations={ 20, 80, 220, 140, 80, 80, 100, 100, 80, 80, 80, 60, 80, 60, 60, 60, 60, 60, 1000 },
      },
    },
  },
  ["260"] = {
    species="SWAMPERT", sourceDex=260,
    root="assets/non_crystal_hd_67/front/normal/260",
    scale=1.5, durations={ 20, 100, 160, 320, 60, 60, 60, 60, 120, 60, 60, 60, 60, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/260",
        scale=1.5, durations={ 20, 100, 160, 320, 60, 60, 60, 60, 120, 60, 60, 60, 60, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/260",
        scale=1.5, durations={ 20, 100, 160, 320, 60, 60, 60, 60, 120, 60, 60, 60, 60, 60, 1000 },
      },
    },
  },
  ["278"] = {
    species="AZURILL", sourceDex=298,
    root="assets/non_crystal_hd_67/front/normal/278",
    scale=1.5, durations={ 20, 40, 160, 240, 160, 140, 100, 100, 60, 60, 60, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/278",
        scale=1.5, durations={ 20, 40, 160, 240, 160, 140, 100, 100, 60, 60, 60, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/278",
        scale=1.5, durations={ 50, 160, 240, 160, 140, 100, 100, 60, 60, 60, 60, 1000 },
      },
    },
  },
  ["280"] = {
    species="RALTS", sourceDex=280,
    root="assets/non_crystal_hd_67/front/normal/280",
    scale=1.5, durations={ 20, 40, 100, 50, 200, 30, 160, 60, 100, 80, 80, 80, 80, 80, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/280",
        scale=1.5, durations={ 20, 40, 100, 50, 200, 30, 160, 60, 100, 80, 80, 80, 80, 80, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/280",
        scale=1.5, durations={ 20, 40, 100, 50, 200, 30, 160, 60, 100, 80, 80, 80, 80, 80, 1000 },
      },
    },
  },
  ["281"] = {
    species="KIRLIA", sourceDex=281,
    root="assets/non_crystal_hd_67/front/normal/281",
    scale=1.5, durations={ 20, 60, 80, 80, 100, 100, 100, 100, 80, 80, 80, 80, 60, 100, 60, 50, 50, 50, 50, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/281",
        scale=1.5, durations={ 20, 60, 80, 80, 100, 100, 100, 100, 80, 80, 80, 80, 60, 100, 60, 50, 50, 50, 50, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/281",
        scale=1.5, durations={ 20, 60, 80, 80, 100, 100, 100, 100, 80, 80, 80, 80, 60, 100, 60, 50, 50, 50, 50, 1000 },
      },
    },
  },
  ["282"] = {
    species="GARDEVOIR", sourceDex=282,
    root="assets/non_crystal_hd_67/front/normal/282",
    scale=1.5, durations={ 20, 60, 80, 140, 100, 120, 100, 140, 100, 120, 100, 120, 80, 100, 80, 40, 60, 60, 60, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/282",
        scale=1.5, durations={ 20, 60, 80, 140, 100, 120, 100, 140, 100, 120, 100, 120, 80, 100, 80, 40, 60, 60, 60, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/282",
        scale=1.5, durations={ 20, 60, 80, 140, 100, 120, 100, 140, 100, 120, 100, 120, 80, 100, 80, 40, 60, 60, 60, 60, 1000 },
      },
    },
  },
  ["283"] = {
    species="SURSKIT", sourceDex=283,
    root="assets/non_crystal_hd_67/front/normal/283",
    scale=1.5, durations={ 20, 60, 120, 80, 120, 80, 100, 60, 120, 80, 60, 60, 60, 60, 60, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/283",
        scale=1.5, durations={ 20, 60, 120, 80, 120, 80, 100, 60, 120, 80, 60, 60, 60, 60, 60, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/283",
        scale=1.5, durations={ 20, 60, 120, 80, 120, 80, 100, 60, 120, 80, 60, 60, 60, 60, 60, 60, 1000 },
      },
    },
  },
  ["284"] = {
    species="MASQUERAIN", sourceDex=284,
    root="assets/non_crystal_hd_67/front/normal/284",
    scale=1.5, durations={ 20, 60, 60, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 50, 50, 50, 50, 80, 60, 50, 50, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/284",
        scale=1.5, durations={ 20, 60, 60, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 50, 50, 50, 50, 80, 60, 50, 50, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/284",
        scale=1.5, durations={ 20, 60, 60, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 50, 50, 50, 50, 80, 60, 50, 50, 1000 },
      },
    },
  },
  ["285"] = {
    species="SHROOMISH", sourceDex=285,
    root="assets/non_crystal_hd_67/front/normal/285",
    scale=1.5, durations={ 20, 60, 220, 120, 60, 100, 60, 50, 50, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/285",
        scale=1.5, durations={ 20, 60, 220, 120, 60, 100, 60, 50, 50, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/285",
        scale=1.5, durations={ 20, 60, 220, 120, 60, 100, 60, 50, 50, 1000 },
      },
    },
  },
  ["286"] = {
    species="BRELOOM", sourceDex=286,
    root="assets/non_crystal_hd_67/front/normal/286",
    scale=1.5, durations={ 20, 40, 120, 40, 80, 80, 20, 80, 60, 20, 100, 60, 20, 100, 120, 40, 120, 50, 50, 50, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/286",
        scale=1.5, durations={ 20, 40, 120, 40, 80, 80, 20, 80, 60, 20, 100, 60, 20, 100, 120, 40, 120, 50, 50, 50, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/286",
        scale=1.5, durations={ 20, 40, 120, 40, 80, 80, 20, 80, 60, 20, 100, 60, 20, 100, 120, 40, 120, 50, 50, 50, 1000 },
      },
    },
  },
  ["287"] = {
    species="SLAKOTH", sourceDex=287,
    root="assets/non_crystal_hd_67/front/normal/287",
    scale=1.5, durations={ 20, 150, 120, 120, 120, 120, 120, 100, 100, 150, 80, 80, 80, 80, 100, 100, 80, 80, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/287",
        scale=1.5, durations={ 20, 150, 120, 120, 120, 120, 120, 100, 100, 150, 80, 80, 80, 80, 100, 100, 80, 80, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/287",
        scale=1.5, durations={ 20, 150, 120, 120, 120, 120, 120, 100, 100, 150, 80, 80, 80, 80, 100, 100, 80, 80, 1000 },
      },
    },
  },
  ["288"] = {
    species="VIGOROTH", sourceDex=288,
    root="assets/non_crystal_hd_67/front/normal/288",
    scale=1.5, durations={ 20, 40, 160, 120, 280, 80, 60, 100, 50, 50, 50, 50, 50, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/288",
        scale=1.5, durations={ 20, 40, 160, 120, 280, 80, 60, 100, 50, 50, 50, 50, 50, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/288",
        scale=1.5, durations={ 50, 160, 120, 280, 80, 60, 100, 50, 50, 50, 50, 50, 1000 },
      },
    },
  },
  ["289"] = {
    species="SLAKING", sourceDex=289,
    root="assets/non_crystal_hd_67/front/normal/289",
    scale=1.5, durations={ 20, 120, 240, 180, 140, 140, 120, 120, 120, 80, 100, 100, 80, 80, 160, 160, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/289",
        scale=1.5, durations={ 20, 120, 240, 180, 140, 140, 120, 120, 120, 80, 100, 100, 80, 80, 160, 160, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/289",
        scale=1.5, durations={ 20, 120, 240, 180, 140, 140, 120, 120, 120, 80, 100, 100, 80, 80, 160, 160, 1000 },
      },
    },
  },
  ["290"] = {
    species="NINCADA", sourceDex=290,
    root="assets/non_crystal_hd_67/front/normal/290",
    scale=1.5, durations={ 20, 80, 100, 140, 140, 120, 120, 120, 80, 60, 60, 60, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/290",
        scale=1.5, durations={ 20, 80, 100, 140, 140, 120, 120, 120, 80, 60, 60, 60, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/290",
        scale=1.5, durations={ 90, 100, 140, 140, 120, 120, 120, 80, 60, 60, 60, 60, 1000 },
      },
    },
  },
  ["291"] = {
    species="NINJASK", sourceDex=291,
    root="assets/non_crystal_hd_67/front/normal/291",
    scale=1.5, durations={ 20, 80, 40, 40, 40, 40, 30, 30, 30, 30, 30, 60, 80, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/291",
        scale=1.5, durations={ 20, 80, 40, 40, 40, 40, 30, 30, 30, 30, 30, 60, 80, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/291",
        scale=1.5, durations={ 20, 80, 40, 40, 40, 40, 30, 30, 30, 30, 30, 60, 80, 60, 1000 },
      },
    },
  },
  ["292"] = {
    species="SHEDINJA", sourceDex=292,
    root="assets/non_crystal_hd_67/front/normal/292",
    scale=1.5, durations={ 20, 200, 120, 200, 200, 120, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/292",
        scale=1.5, durations={ 20, 200, 120, 200, 200, 120, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/292",
        scale=1.5, durations={ 20, 200, 120, 200, 200, 120, 1000 },
      },
    },
  },
  ["293"] = {
    species="WHISMUR", sourceDex=293,
    root="assets/non_crystal_hd_67/front/normal/293",
    scale=1.5, durations={ 20, 60, 80, 180, 240, 120, 180, 80, 140, 80, 80, 80, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/293",
        scale=1.5, durations={ 20, 60, 80, 180, 240, 120, 180, 80, 140, 80, 80, 80, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/293",
        scale=1.5, durations={ 70, 80, 180, 240, 120, 180, 80, 140, 80, 80, 80, 1000 },
      },
    },
  },
  ["294"] = {
    species="LOUDRED", sourceDex=294,
    root="assets/non_crystal_hd_67/front/normal/294",
    scale=1.5, durations={ 20, 80, 140, 100, 20, 220, 160, 180, 120, 60, 60, 60, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/294",
        scale=1.5, durations={ 20, 80, 140, 100, 20, 220, 160, 180, 120, 60, 60, 60, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/294",
        scale=1.5, durations={ 20, 80, 140, 100, 20, 220, 160, 180, 120, 60, 60, 60, 60, 1000 },
      },
    },
  },
  ["295"] = {
    species="EXPLOUD", sourceDex=295,
    root="assets/non_crystal_hd_67/front/normal/295",
    scale=1.5, durations={ 20, 60, 120, 40, 180, 120, 280, 160, 100, 60, 60, 60, 60, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/295",
        scale=1.5, durations={ 20, 60, 120, 40, 180, 120, 280, 160, 100, 60, 60, 60, 60, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/295",
        scale=1.5, durations={ 20, 60, 120, 40, 180, 120, 280, 160, 100, 60, 60, 60, 60, 1060 },
      },
    },
  },
  ["296"] = {
    species="MAKUHITA", sourceDex=296,
    root="assets/non_crystal_hd_67/front/normal/296",
    scale=1.5, durations={ 20, 80, 180, 160, 120, 80, 160, 120, 120, 80, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/296",
        scale=1.5, durations={ 20, 80, 180, 160, 120, 80, 160, 120, 120, 80, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/296",
        scale=1.5, durations={ 20, 80, 180, 160, 120, 80, 160, 120, 120, 80, 1000 },
      },
    },
  },
  ["297"] = {
    species="HARIYAMA", sourceDex=297,
    root="assets/non_crystal_hd_67/front/normal/297",
    scale=1.5, durations={ 20, 80, 40, 120, 140, 280, 20, 200, 80, 40, 60, 60, 60, 60, 60, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/297",
        scale=1.5, durations={ 20, 80, 40, 120, 140, 280, 20, 200, 80, 40, 60, 60, 60, 60, 60, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/297",
        scale=1.5, durations={ 90, 40, 120, 140, 280, 20, 200, 80, 40, 60, 60, 60, 60, 60, 60, 1000 },
      },
    },
  },
  ["299"] = {
    species="NOSEPASS", sourceDex=299,
    root="assets/non_crystal_hd_67/front/normal/299",
    scale=1.5, durations={ 20, 160, 120, 120, 160, 160, 80, 80, 80, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/299",
        scale=1.5, durations={ 20, 160, 120, 120, 160, 160, 80, 80, 80, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/299",
        scale=1.5, durations={ 170, 120, 120, 160, 160, 80, 80, 80, 1000 },
      },
    },
  },
  ["300"] = {
    species="SKITTY", sourceDex=300,
    root="assets/non_crystal_hd_67/front/normal/300",
    scale=1.5, durations={ 20, 60, 260, 60, 60, 80, 100, 60, 80, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/300",
        scale=1.5, durations={ 20, 60, 260, 60, 60, 80, 100, 60, 80, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/300",
        scale=1.5, durations={ 20, 60, 260, 60, 60, 80, 100, 60, 80, 1000 },
      },
    },
  },
  ["301"] = {
    species="DELCATTY", sourceDex=301,
    root="assets/non_crystal_hd_67/front/normal/301",
    scale=1.5, durations={ 20, 60, 80, 120, 120, 120, 120, 80, 80, 100, 60, 60, 60, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/301",
        scale=1.5, durations={ 20, 60, 80, 120, 120, 120, 120, 80, 80, 100, 60, 60, 60, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/301",
        scale=1.5, durations={ 20, 60, 80, 120, 120, 120, 120, 80, 80, 100, 60, 60, 60, 60, 1000 },
      },
    },
  },
  ["302"] = {
    species="SABLEYE", sourceDex=302,
    root="assets/non_crystal_hd_67/front/normal/302",
    scale=1.5, durations={ 20, 80, 60, 60, 60, 60, 50, 50, 50, 50, 60, 120, 80, 80, 120, 80, 80, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/302",
        scale=1.5, durations={ 20, 80, 60, 60, 60, 60, 50, 50, 50, 50, 60, 120, 80, 80, 120, 80, 80, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/302",
        scale=1.5, durations={ 20, 80, 60, 60, 60, 60, 50, 50, 50, 50, 60, 120, 80, 80, 120, 80, 80, 1000 },
      },
    },
  },
  ["303"] = {
    species="MAWILE", sourceDex=303,
    root="assets/non_crystal_hd_67/front/normal/303",
    scale=1.5, durations={ 20, 80, 120, 140, 100, 100, 80, 60, 60, 60, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/303",
        scale=1.5, durations={ 20, 80, 120, 140, 100, 100, 80, 60, 60, 60, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/303",
        scale=1.5, durations={ 20, 80, 120, 140, 100, 100, 80, 60, 60, 60, 60, 1000 },
      },
    },
  },
  ["304"] = {
    species="ARON", sourceDex=304,
    root="assets/non_crystal_hd_67/front/normal/304",
    scale=1.5, durations={ 20, 120, 220, 220, 180, 180, 80, 80, 60, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/304",
        scale=1.5, durations={ 20, 120, 220, 220, 180, 180, 80, 80, 60, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/304",
        scale=1.5, durations={ 20, 120, 220, 220, 180, 180, 80, 80, 60, 60, 1000 },
      },
    },
  },
  ["305"] = {
    species="LAIRON", sourceDex=305,
    root="assets/non_crystal_hd_67/front/normal/305",
    scale=1.5, durations={ 20, 80, 220, 120, 300, 100, 80, 80, 80, 80, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/305",
        scale=1.5, durations={ 20, 80, 220, 120, 300, 100, 80, 80, 80, 80, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/305",
        scale=1.5, durations={ 20, 80, 220, 120, 300, 100, 80, 80, 80, 80, 1000 },
      },
    },
  },
  ["306"] = {
    species="AGGRON", sourceDex=306,
    root="assets/non_crystal_hd_67/front/normal/306",
    scale=1.5, durations={ 20, 60, 240, 80, 300, 80, 60, 60, 60, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/306",
        scale=1.5, durations={ 20, 60, 240, 80, 300, 80, 60, 60, 60, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/306",
        scale=1.5, durations={ 20, 60, 240, 80, 300, 80, 60, 60, 60, 60, 1000 },
      },
    },
  },
  ["307"] = {
    species="MEDITITE", sourceDex=307,
    root="assets/non_crystal_hd_67/front/normal/307",
    scale=1.5, durations={ 20, 60, 120, 240, 70, 180, 100, 60, 60, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/307",
        scale=1.5, durations={ 20, 60, 120, 240, 70, 180, 100, 60, 60, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/307",
        scale=1.5, durations={ 20, 60, 120, 240, 70, 180, 100, 60, 60, 60, 1000 },
      },
    },
  },
  ["308"] = {
    species="MEDICHAM", sourceDex=308,
    root="assets/non_crystal_hd_67/front/normal/308",
    scale=1.5, durations={ 20, 80, 320, 80, 120, 120, 120, 100, 100, 100, 100, 80, 60, 60, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/308",
        scale=1.5, durations={ 20, 80, 320, 80, 120, 120, 120, 100, 100, 100, 100, 80, 60, 60, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/308",
        scale=1.5, durations={ 90, 320, 80, 120, 120, 120, 100, 100, 100, 100, 80, 60, 60, 60, 1000 },
      },
    },
  },
  ["309"] = {
    species="ELECTRIKE", sourceDex=309,
    root="assets/non_crystal_hd_67/front/normal/309",
    scale=1.5, durations={ 600, 80, 80, 80, 800, 80, 80, 80, 80, 80, 80, 120, 120, 120, 120 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/309",
        scale=1.5, durations={ 600, 80, 80, 80, 800, 80, 80, 80, 80, 80, 80, 120, 120, 120, 120 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/309",
        scale=1.5, durations={ 600, 80, 80, 80, 800, 80, 80, 80, 80, 80, 80, 120, 120, 120, 120 },
      },
    },
  },
  ["310"] = {
    species="MANECTRIC", sourceDex=310,
    root="assets/non_crystal_hd_67/front/normal/310",
    scale=1.5, durations={ 300, 500, 100, 100, 100, 100, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 100, 100, 100, 100, 200, 100, 150, 150, 150, 150 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/310",
        scale=1.5, durations={ 300, 500, 100, 100, 100, 100, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 100, 100, 100, 100, 200, 100, 150, 150, 150, 150 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/310",
        scale=1.5, durations={ 300, 500, 100, 100, 100, 100, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 100, 100, 100, 100, 200, 100, 150, 150, 150, 150 },
      },
    },
  },
  ["311"] = {
    species="PLUSLE", sourceDex=311,
    root="assets/non_crystal_hd_67/front/normal/311",
    scale=1.5, durations={ 20, 80, 150, 200, 140, 100, 60, 60, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/311",
        scale=1.5, durations={ 20, 80, 150, 200, 140, 100, 60, 60, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/311",
        scale=1.5, durations={ 90, 150, 200, 140, 100, 60, 60, 60, 1000 },
      },
    },
  },
  ["312"] = {
    species="MINUN", sourceDex=312,
    root="assets/non_crystal_hd_67/front/normal/312",
    scale=1.5, durations={ 20, 80, 150, 200, 140, 100, 60, 60, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/312",
        scale=1.5, durations={ 20, 80, 150, 200, 140, 100, 60, 60, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/312",
        scale=1.5, durations={ 90, 150, 200, 140, 100, 60, 60, 60, 1000 },
      },
    },
  },
  ["313"] = {
    species="VOLBEAT", sourceDex=313,
    root="assets/non_crystal_hd_67/front/normal/313",
    scale=1.5, durations={ 20, 180, 100, 140, 100, 120, 80, 120, 60, 60, 60, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/313",
        scale=1.5, durations={ 20, 180, 100, 140, 100, 120, 80, 120, 60, 60, 60, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/313",
        scale=1.5, durations={ 20, 180, 100, 140, 100, 120, 80, 120, 60, 60, 60, 60, 1000 },
      },
    },
  },
  ["314"] = {
    species="ILLUMISE", sourceDex=314,
    root="assets/non_crystal_hd_67/front/normal/314",
    scale=1.5, durations={ 20, 140, 100, 240, 60, 60, 60, 60, 60, 60, 60, 120, 60, 60, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/314",
        scale=1.5, durations={ 20, 140, 100, 240, 60, 60, 60, 60, 60, 60, 60, 120, 60, 60, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/314",
        scale=1.5, durations={ 20, 140, 100, 240, 60, 60, 60, 60, 60, 60, 60, 120, 60, 60, 60, 1000 },
      },
    },
  },
  ["315"] = {
    species="ROSELIA", sourceDex=315,
    root="assets/non_crystal_hd_67/front/normal/315",
    scale=1.5, durations={ 20, 180, 260, 220, 80, 80, 80, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/315",
        scale=1.5, durations={ 20, 180, 260, 220, 80, 80, 80, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/315",
        scale=1.5, durations={ 20, 180, 260, 220, 80, 80, 80, 1000 },
      },
    },
  },
  ["316"] = {
    species="GULPIN", sourceDex=316,
    root="assets/non_crystal_hd_67/front/normal/316",
    scale=1.5, durations={ 20, 80, 120, 220, 60, 100, 80, 80, 80, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/316",
        scale=1.5, durations={ 20, 80, 120, 220, 60, 100, 80, 80, 80, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/316",
        scale=1.5, durations={ 90, 120, 220, 60, 100, 80, 80, 80, 1000 },
      },
    },
  },
  ["317"] = {
    species="SWALOT", sourceDex=317,
    root="assets/non_crystal_hd_67/front/normal/317",
    scale=1.5, durations={ 20, 140, 140, 120, 120, 120, 120, 60, 60, 80, 80, 80, 80, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/317",
        scale=1.5, durations={ 20, 140, 140, 120, 120, 120, 120, 60, 60, 80, 80, 80, 80, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/317",
        scale=1.5, durations={ 20, 140, 140, 120, 120, 120, 120, 60, 60, 80, 80, 80, 80, 1000 },
      },
    },
  },
  ["318"] = {
    species="CARVANHA", sourceDex=318,
    root="assets/non_crystal_hd_67/front/normal/318",
    scale=1.5, durations={ 20, 80, 80, 160, 80, 80, 80, 80, 80, 120, 100, 100, 100, 100, 120, 160, 120, 160, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/318",
        scale=1.5, durations={ 20, 80, 80, 160, 80, 80, 80, 80, 80, 120, 100, 100, 100, 100, 120, 160, 120, 160, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/318",
        scale=1.5, durations={ 20, 80, 80, 160, 80, 80, 80, 80, 80, 120, 100, 100, 100, 100, 120, 160, 120, 160, 1000 },
      },
    },
  },
  ["319"] = {
    species="SHARPEDO", sourceDex=319,
    root="assets/non_crystal_hd_67/front/normal/319",
    scale=1.5, durations={ 20, 120, 200, 80, 120, 80, 120, 80, 180, 80, 120, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/319",
        scale=1.5, durations={ 20, 120, 200, 80, 120, 80, 120, 80, 180, 80, 120, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/319",
        scale=1.5, durations={ 20, 120, 200, 80, 120, 80, 120, 80, 180, 80, 120, 1000 },
      },
    },
  },
  ["320"] = {
    species="WAILMER", sourceDex=320,
    root="assets/non_crystal_hd_67/front/normal/320",
    scale=1.5, durations={ 120, 110, 90, 80, 90, 80, 80, 90, 80, 80, 90, 80, 550, 120, 80, 120, 2010 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/320",
        scale=1.5, durations={ 120, 110, 90, 80, 90, 80, 80, 90, 80, 80, 90, 80, 550, 120, 80, 120, 2010 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/320",
        scale=1.5, durations={ 120, 110, 90, 80, 90, 80, 80, 90, 80, 80, 90, 80, 550, 120, 80, 120, 2010 },
      },
    },
  },
  ["321"] = {
    species="WAILORD", sourceDex=321,
    root="assets/non_crystal_hd_67/front/normal/321",
    scale=1.5, durations={ 80, 40, 250, 30, 50, 90, 80, 80, 90, 80, 80, 90, 80, 90, 80, 80, 90, 80, 80, 90, 420, 300, 50, 200, 50, 100, 100, 100, 100, 100, 100, 2110 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/321",
        scale=1.5, durations={ 80, 40, 250, 30, 50, 90, 80, 80, 90, 80, 80, 90, 80, 90, 80, 80, 90, 80, 80, 90, 420, 300, 50, 200, 50, 100, 100, 100, 100, 100, 100, 2110 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/321",
        scale=1.5, durations={ 80, 40, 250, 30, 50, 90, 80, 80, 90, 80, 80, 90, 80, 90, 80, 80, 90, 80, 80, 90, 420, 300, 50, 200, 50, 100, 100, 100, 100, 100, 100, 2110 },
      },
    },
  },
  ["322"] = {
    species="NUMEL", sourceDex=322,
    root="assets/non_crystal_hd_67/front/normal/322",
    scale=1.5, durations={ 200, 200, 200, 200, 200, 200, 200, 200, 100, 100, 100, 100, 100, 100, 100, 100, 200, 80, 100, 80, 500 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/322",
        scale=1.5, durations={ 200, 200, 200, 200, 200, 200, 200, 200, 100, 100, 100, 100, 100, 100, 100, 100, 200, 80, 100, 80, 500 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/322",
        scale=1.5, durations={ 200, 200, 200, 200, 200, 200, 200, 200, 100, 100, 100, 100, 100, 100, 100, 100, 200, 80, 100, 80, 500 },
      },
    },
  },
  ["323"] = {
    species="CAMERUPT", sourceDex=323,
    root="assets/non_crystal_hd_67/front/normal/323",
    scale=1.5, durations={ 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 400, 200, 300, 200 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/323",
        scale=1.5, durations={ 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 400, 200, 300, 200 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/323",
        scale=1.5, durations={ 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 400, 200, 300, 200 },
      },
    },
  },
  ["324"] = {
    species="TORKOAL", sourceDex=324,
    root="assets/non_crystal_hd_67/front/normal/324",
    scale=1.5, durations={ 600, 600, 600, 600, 600, 200, 200, 200, 600, 200, 200, 200 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/324",
        scale=1.5, durations={ 600, 600, 600, 600, 600, 200, 200, 200, 600, 200, 200, 200 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/324",
        scale=1.5, durations={ 600, 600, 600, 600, 600, 200, 200, 200, 600, 200, 200, 200 },
      },
    },
  },
  ["325"] = {
    species="SPOINK", sourceDex=325,
    root="assets/non_crystal_hd_67/front/normal/325",
    scale=1.5, durations={ 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/325",
        scale=1.5, durations={ 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/325",
        scale=1.5, durations={ 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200 },
      },
    },
  },
  ["326"] = {
    species="GRUMPIG", sourceDex=326,
    root="assets/non_crystal_hd_67/front/normal/326",
    scale=1.5, durations={ 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/326",
        scale=1.5, durations={ 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/326",
        scale=1.5, durations={ 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200 },
      },
    },
  },
  ["327"] = {
    species="SPINDA", sourceDex=327,
    root="assets/non_crystal_hd_67/front/normal/327",
    scale=1.5, durations={ 570, 570, 570, 570, 570, 570, 570, 570, 280, 420, 140, 570 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/327",
        scale=1.5, durations={ 570, 570, 570, 570, 570, 570, 570, 570, 280, 420, 140, 570 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/327",
        scale=1.5, durations={ 560, 560, 560, 560, 560, 560, 560, 560, 280, 420, 140, 560 },
      },
    },
  },
  ["328"] = {
    species="TRAPINCH", sourceDex=328,
    root="assets/non_crystal_hd_67/front/normal/328",
    scale=1.5, durations={ 500, 100, 200, 200, 500, 200, 200, 500, 200, 200, 500, 100, 200, 200 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/328",
        scale=1.5, durations={ 500, 100, 200, 200, 500, 200, 200, 500, 200, 200, 500, 100, 200, 200 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/328",
        scale=1.5, durations={ 500, 100, 200, 200, 500, 200, 200, 500, 200, 200, 500, 100, 200, 200 },
      },
    },
  },
  ["329"] = {
    species="VIBRAVA", sourceDex=329,
    root="assets/non_crystal_hd_67/front/normal/329",
    scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/329",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/329",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100 },
      },
    },
  },
  ["330"] = {
    species="FLYGON", sourceDex=330,
    root="assets/non_crystal_hd_67/front/normal/330",
    scale=1.5, durations={ 250, 250, 250, 250, 250, 250, 250, 250, 250, 250, 250, 250, 250, 250 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/330",
        scale=1.5, durations={ 250, 250, 250, 250, 250, 250, 250, 250, 250, 250, 250, 250, 250, 250 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/330",
        scale=1.5, durations={ 250, 250, 250, 250, 250, 250, 250, 250, 250, 250, 250, 250, 250, 250 },
      },
    },
  },
  ["331"] = {
    species="CACNEA", sourceDex=331,
    root="assets/non_crystal_hd_67/front/normal/331",
    scale=1.5, durations={ 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/331",
        scale=1.5, durations={ 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/331",
        scale=1.5, durations={ 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200 },
      },
    },
  },
  ["332"] = {
    species="CACTURNE", sourceDex=332,
    root="assets/non_crystal_hd_67/front/normal/332",
    scale=1.5, durations={ 400, 200, 400, 200, 200, 200, 200, 200, 200, 200, 200, 200 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/332",
        scale=1.5, durations={ 400, 200, 400, 200, 200, 200, 200, 200, 200, 200, 200, 200 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/332",
        scale=1.5, durations={ 400, 200, 400, 200, 200, 200, 200, 200, 200, 200, 200, 200 },
      },
    },
  },
  ["333"] = {
    species="SWABLU", sourceDex=333,
    root="assets/non_crystal_hd_67/front/normal/333",
    scale=1.5, durations={ 500, 150, 150, 150, 150, 150, 200, 100, 100, 100, 100, 400, 200, 80, 100, 80 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/333",
        scale=1.5, durations={ 500, 150, 150, 150, 150, 150, 200, 100, 100, 100, 100, 400, 200, 80, 100, 80 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/333",
        scale=1.5, durations={ 500, 150, 150, 150, 150, 150, 200, 100, 100, 100, 100, 400, 200, 80, 100, 80 },
      },
    },
  },
  ["334"] = {
    species="ALTARIA", sourceDex=334,
    root="assets/non_crystal_hd_67/front/normal/334",
    scale=1.5, durations={ 120, 130, 120, 130, 120, 130, 120, 130, 120, 130 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/334",
        scale=1.5, durations={ 120, 130, 120, 130, 120, 130, 120, 130, 120, 130 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/334",
        scale=1.5, durations={ 120, 130, 120, 130, 120, 130, 120, 130, 120, 130 },
      },
    },
  },
  ["335"] = {
    species="ZANGOOSE", sourceDex=335,
    root="assets/non_crystal_hd_67/front/normal/335",
    scale=1.5, durations={ 100, 100, 100, 100, 50, 50, 80, 200, 100, 120, 80, 120, 80, 600 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/335",
        scale=1.5, durations={ 100, 100, 100, 100, 50, 50, 80, 200, 100, 120, 80, 120, 80, 600 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/335",
        scale=1.5, durations={ 100, 100, 100, 100, 50, 50, 80, 200, 100, 120, 80, 120, 80, 600 },
      },
    },
  },
  ["336"] = {
    species="SEVIPER", sourceDex=336,
    root="assets/non_crystal_hd_67/front/normal/336",
    scale=1.5, durations={ 120, 120, 120, 120, 120, 120, 120, 120, 120, 80, 80, 80, 80, 80, 80, 80, 80, 120, 600 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/336",
        scale=1.5, durations={ 120, 120, 120, 120, 120, 120, 120, 120, 120, 80, 80, 80, 80, 80, 80, 80, 80, 120, 600 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/336",
        scale=1.5, durations={ 120, 120, 120, 120, 120, 120, 120, 120, 120, 80, 80, 80, 80, 80, 80, 80, 80, 120, 600 },
      },
    },
  },
  ["337"] = {
    species="LUNATONE", sourceDex=337,
    root="assets/non_crystal_hd_67/front/normal/337",
    scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 300 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/337",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 300 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/337",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 300 },
      },
    },
  },
  ["338"] = {
    species="SOLROCK", sourceDex=338,
    root="assets/non_crystal_hd_67/front/normal/338",
    scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 200, 200, 200, 300 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/338",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 200, 200, 200, 300 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/338",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 200, 200, 200, 300 },
      },
    },
  },
  ["339"] = {
    species="BARBOACH", sourceDex=339,
    root="assets/non_crystal_hd_67/front/normal/339",
    scale=1.5, durations={ 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 120, 120, 120, 80, 80, 80, 80, 500 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/339",
        scale=1.5, durations={ 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 120, 120, 120, 80, 80, 80, 80, 500 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/339",
        scale=1.5, durations={ 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 120, 120, 120, 80, 80, 80, 80, 500 },
      },
    },
  },
  ["340"] = {
    species="WHISCASH", sourceDex=340,
    root="assets/non_crystal_hd_67/front/normal/340",
    scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 80, 80, 80, 500 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/340",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 80, 80, 80, 500 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/340",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 80, 80, 80, 500 },
      },
    },
  },
  ["341"] = {
    species="CORPHISH", sourceDex=341,
    root="assets/non_crystal_hd_67/front/normal/341",
    scale=1.5, durations={ 100, 100, 50, 100, 50, 100, 50, 100, 50, 100, 50, 100, 100, 150, 100, 150, 400, 150, 600 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/341",
        scale=1.5, durations={ 100, 100, 50, 100, 50, 100, 50, 100, 50, 100, 50, 100, 100, 150, 100, 150, 400, 150, 600 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/341",
        scale=1.5, durations={ 100, 100, 50, 100, 50, 100, 50, 100, 50, 100, 50, 100, 100, 150, 100, 150, 400, 150, 600 },
      },
    },
  },
  ["342"] = {
    species="CRAWDAUNT", sourceDex=342,
    root="assets/non_crystal_hd_67/front/normal/342",
    scale=1.5, durations={ 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/342",
        scale=1.5, durations={ 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/342",
        scale=1.5, durations={ 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200 },
      },
    },
  },
  ["343"] = {
    species="BALTOY", sourceDex=343,
    root="assets/non_crystal_hd_67/front/normal/343",
    scale=1.5, durations={ 110, 110, 110, 110, 110, 110, 110, 110, 110 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/343",
        scale=1.5, durations={ 110, 110, 110, 110, 110, 110, 110, 110, 110 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/343",
        scale=1.5, durations={ 110, 110, 110, 110, 110, 110, 110, 110, 110 },
      },
    },
  },
  ["344"] = {
    species="CLAYDOL", sourceDex=344,
    root="assets/non_crystal_hd_67/front/normal/344",
    scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 600 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/344",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 600 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/344",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 600 },
      },
    },
  },
  ["345"] = {
    species="LILEEP", sourceDex=345,
    root="assets/non_crystal_hd_67/front/normal/345",
    scale=1.5, durations={ 100, 50, 50, 50, 50, 50, 50, 50, 50, 40, 330, 80, 90, 80, 2010 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/345",
        scale=1.5, durations={ 100, 50, 50, 50, 50, 50, 50, 50, 50, 40, 330, 80, 90, 80, 2010 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/345",
        scale=1.5, durations={ 100, 50, 50, 50, 50, 50, 50, 50, 50, 40, 330, 80, 90, 80, 2010 },
      },
    },
  },
  ["346"] = {
    species="CRADILY", sourceDex=346,
    root="assets/non_crystal_hd_67/front/normal/346",
    scale=1.5, durations={ 100, 80, 70, 80, 70, 90, 60, 90, 60, 90, 60, 100, 100, 90, 80, 90, 80, 80, 90, 1050, 90, 80, 80, 2010 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/346",
        scale=1.5, durations={ 100, 80, 70, 80, 70, 90, 60, 90, 60, 90, 60, 100, 100, 90, 80, 90, 80, 80, 90, 1050, 90, 80, 80, 2010 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/346",
        scale=1.5, durations={ 100, 80, 70, 80, 70, 90, 60, 90, 60, 90, 60, 100, 100, 90, 80, 90, 80, 80, 90, 1050, 90, 80, 80, 2010 },
      },
    },
  },
  ["347"] = {
    species="ANORITH", sourceDex=347,
    root="assets/non_crystal_hd_67/front/normal/347",
    scale=1.5, durations={ 200, 200, 200, 200, 200 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/347",
        scale=1.5, durations={ 200, 200, 200, 200, 200 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/347",
        scale=1.5, durations={ 200, 200, 200, 200, 200 },
      },
    },
  },
  ["348"] = {
    species="ARMALDO", sourceDex=348,
    root="assets/non_crystal_hd_67/front/normal/348",
    scale=1.5, durations={ 400, 200, 200, 200, 200, 400 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/348",
        scale=1.5, durations={ 400, 200, 200, 200, 200, 400 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/348",
        scale=1.5, durations={ 400, 200, 200, 200, 200, 400 },
      },
    },
  },
  ["349"] = {
    species="FEEBAS", sourceDex=349,
    root="assets/non_crystal_hd_67/front/normal/349",
    scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 300 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/349",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 300 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/349",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 300 },
      },
    },
  },
  ["350"] = {
    species="MILOTIC", sourceDex=350,
    root="assets/non_crystal_hd_67/front/normal/350",
    scale=1.5, durations={ 200, 300, 300, 300, 300, 300, 100, 200, 300, 300, 300, 100 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/350",
        scale=1.5, durations={ 200, 300, 300, 300, 300, 300, 100, 200, 300, 300, 300, 100 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/350",
        scale=1.5, durations={ 200, 300, 300, 300, 300, 300, 100, 200, 300, 300, 300, 100 },
      },
    },
  },
  ["351"] = {
    species="CASTFORM", sourceDex=351,
    root="assets/non_crystal_hd_67/front/normal/351",
    scale=1.5, durations={ 600, 200, 200, 200, 400, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/351",
        scale=1.5, durations={ 600, 200, 200, 200, 400, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/351",
        scale=1.5, durations={ 600, 200, 200, 200, 400, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200 },
      },
    },
  },
  ["353"] = {
    species="SHUPPET", sourceDex=353,
    root="assets/non_crystal_hd_67/front/normal/353",
    scale=1.5, durations={ 140, 140, 140, 140, 140, 140, 140, 140, 140 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/353",
        scale=1.5, durations={ 140, 140, 140, 140, 140, 140, 140, 140, 140 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/353",
        scale=1.5, durations={ 140, 140, 140, 140, 140, 140, 140, 140 },
      },
    },
  },
  ["354"] = {
    species="BANETTE", sourceDex=354,
    root="assets/non_crystal_hd_67/front/normal/354",
    scale=1.5, durations={ 400, 200, 200, 200, 200, 200, 200, 200 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/354",
        scale=1.5, durations={ 400, 200, 200, 200, 200, 200, 200, 200 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/354",
        scale=1.5, durations={ 400, 200, 200, 200, 200, 200, 200, 200 },
      },
    },
  },
  ["355"] = {
    species="DUSKULL", sourceDex=355,
    root="assets/non_crystal_hd_67/front/normal/355",
    scale=1.5, durations={ 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/355",
        scale=1.5, durations={ 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/355",
        scale=1.5, durations={ 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200 },
      },
    },
  },
  ["356"] = {
    species="DUSCLOPS", sourceDex=356,
    root="assets/non_crystal_hd_67/front/normal/356",
    scale=1.5, durations={ 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/356",
        scale=1.5, durations={ 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/356",
        scale=1.5, durations={ 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200 },
      },
    },
  },
  ["358"] = {
    species="CHIMECHO", sourceDex=358,
    root="assets/non_crystal_hd_67/front/normal/358",
    scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 200, 100, 300, 300 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/358",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 200, 100, 300, 300 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/358",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 200, 100, 300, 300 },
      },
    },
  },
  ["359"] = {
    species="ABSOL", sourceDex=359,
    root="assets/non_crystal_hd_67/front/normal/359",
    scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 300 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/359",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 300 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/359",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 300 },
      },
    },
  },
  ["361"] = {
    species="SNORUNT", sourceDex=361,
    root="assets/non_crystal_hd_67/front/normal/361",
    scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 700, 300 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/361",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 700, 300 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/361",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 700, 300 },
      },
    },
  },
  ["362"] = {
    species="GLALIE", sourceDex=362,
    root="assets/non_crystal_hd_67/front/normal/362",
    scale=1.5, durations={ 100, 100, 500, 100, 100, 100, 100, 100, 100, 400 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/362",
        scale=1.5, durations={ 100, 100, 500, 100, 100, 100, 100, 100, 100, 400 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/362",
        scale=1.5, durations={ 100, 100, 500, 100, 100, 100, 100, 100, 100, 400 },
      },
    },
  },
  ["363"] = {
    species="SPHEAL", sourceDex=363,
    root="assets/non_crystal_hd_67/front/normal/363",
    scale=1.5, durations={ 200, 200, 200, 200, 300, 300, 300, 300, 100 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/363",
        scale=1.5, durations={ 200, 200, 200, 200, 300, 300, 300, 300, 100 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/363",
        scale=1.5, durations={ 200, 200, 200, 200, 300, 300, 300, 300, 100 },
      },
    },
  },
  ["364"] = {
    species="SEALEO", sourceDex=364,
    root="assets/non_crystal_hd_67/front/normal/364",
    scale=1.5, durations={ 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/364",
        scale=1.5, durations={ 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/364",
        scale=1.5, durations={ 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200 },
      },
    },
  },
  ["365"] = {
    species="WALREIN", sourceDex=365,
    root="assets/non_crystal_hd_67/front/normal/365",
    scale=1.5, durations={ 200, 400, 200, 200, 200, 200, 400 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/365",
        scale=1.5, durations={ 200, 400, 200, 200, 200, 200, 400 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/365",
        scale=1.5, durations={ 200, 400, 200, 200, 200, 200, 400 },
      },
    },
  },
  ["369"] = {
    species="RELICANTH", sourceDex=369,
    root="assets/non_crystal_hd_67/front/normal/369",
    scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 1000, 100, 100, 100 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/369",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 1000, 100, 100, 100 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/369",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 1000, 100, 100, 100 },
      },
    },
  },
  ["370"] = {
    species="LUVDISC", sourceDex=370,
    root="assets/non_crystal_hd_67/front/normal/370",
    scale=1.5, durations={ 200, 150, 200, 150, 600, 150, 200, 150, 200, 100, 100, 200, 150, 600, 150, 200, 150, 1200 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/370",
        scale=1.5, durations={ 200, 150, 200, 150, 600, 150, 200, 150, 200, 100, 100, 200, 150, 600, 150, 200, 150, 1200 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/370",
        scale=1.5, durations={ 200, 150, 200, 150, 600, 150, 200, 150, 200, 100, 100, 200, 150, 600, 150, 200, 150, 1200 },
      },
    },
  },
  ["371"] = {
    species="BAGON", sourceDex=371,
    root="assets/non_crystal_hd_67/front/normal/371",
    scale=1.5, durations={ 100, 100, 700, 100, 100, 100, 100, 300 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/371",
        scale=1.5, durations={ 100, 100, 700, 100, 100, 100, 100, 300 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/371",
        scale=1.5, durations={ 100, 100, 700, 100, 100, 100, 100, 300 },
      },
    },
  },
  ["372"] = {
    species="SHELGON", sourceDex=372,
    root="assets/non_crystal_hd_67/front/normal/372",
    scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 300 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/372",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 300 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/372",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 300 },
      },
    },
  },
  ["373"] = {
    species="SALAMENCE", sourceDex=373,
    root="assets/non_crystal_hd_67/front/normal/373",
    scale=1.5, durations={ 300, 300, 100, 100, 100, 100, 100, 100, 300, 100, 100, 100, 100, 100, 100, 200, 80, 100, 80, 120, 120, 120, 120 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/373",
        scale=1.5, durations={ 300, 300, 100, 100, 100, 100, 100, 100, 300, 100, 100, 100, 100, 100, 100, 200, 80, 100, 80, 120, 120, 120, 120 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/373",
        scale=1.5, durations={ 300, 300, 100, 100, 100, 100, 100, 100, 300, 100, 100, 100, 100, 100, 100, 200, 80, 100, 80, 120, 120, 120, 120 },
      },
    },
  },
  ["374"] = {
    species="BELDUM", sourceDex=374,
    root="assets/non_crystal_hd_67/front/normal/374",
    scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 300 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/374",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 300 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/374",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 300 },
      },
    },
  },
  ["375"] = {
    species="METANG", sourceDex=375,
    root="assets/non_crystal_hd_67/front/normal/375",
    scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 300 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/375",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 300 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/375",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 300 },
      },
    },
  },
  ["376"] = {
    species="METAGROSS", sourceDex=376,
    root="assets/non_crystal_hd_67/front/normal/376",
    scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 200, 100, 100, 100, 200, 100, 100, 100, 400 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/376",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 200, 100, 100, 100, 200, 100, 100, 100, 400 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/376",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 200, 100, 100, 100, 200, 100, 100, 100, 400 },
      },
    },
  },
  ["377"] = {
    species="REGIROCK", sourceDex=377,
    root="assets/non_crystal_hd_67/front/normal/377",
    scale=1.5, durations={ 120, 120, 120, 120, 120, 120, 120, 120, 120, 600 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/377",
        scale=1.5, durations={ 120, 120, 120, 120, 120, 120, 120, 120, 120, 600 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/377",
        scale=1.5, durations={ 120, 120, 120, 120, 120, 120, 120, 120, 120, 600 },
      },
    },
  },
  ["378"] = {
    species="REGICE", sourceDex=378,
    root="assets/non_crystal_hd_67/front/normal/378",
    scale=1.5, durations={ 120, 120, 120, 120, 120, 120, 120, 120, 600 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/378",
        scale=1.5, durations={ 120, 120, 120, 120, 120, 120, 120, 120, 600 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/378",
        scale=1.5, durations={ 120, 120, 120, 120, 120, 120, 120, 120, 600 },
      },
    },
  },
  ["379"] = {
    species="REGISTEEL", sourceDex=379,
    root="assets/non_crystal_hd_67/front/normal/379",
    scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 120, 120, 120, 600 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/379",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 120, 120, 120, 600 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/379",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 120, 120, 120, 600 },
      },
    },
  },
  ["382"] = {
    species="KYOGRE", sourceDex=382,
    root="assets/non_crystal_hd_67/front/normal/382",
    scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 700, 100, 300 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/382",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 700, 100, 300 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/382",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 700, 100, 300 },
      },
    },
  },
  ["383"] = {
    species="GROUDON", sourceDex=383,
    root="assets/non_crystal_hd_67/front/normal/383",
    scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 300 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/383",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 300 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/383",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 300 },
      },
    },
  },
  ["384"] = {
    species="RAYQUAZA", sourceDex=384,
    root="assets/non_crystal_hd_67/front/normal/384",
    scale=1.5, durations={ 400, 250, 400, 250, 400, 600, 1200 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/384",
        scale=1.5, durations={ 400, 250, 400, 250, 400, 600, 1200 },
      },
    },
  },
  ["385"] = {
    species="JIRACHI", sourceDex=385,
    root="assets/non_crystal_hd_67/front/normal/385",
    scale=1.5, durations={ 600, 200, 400, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 500, 200 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/385",
        scale=1.5, durations={ 600, 200, 400, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 500, 200 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/385",
        scale=1.5, durations={ 600, 200, 400, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 500, 200 },
      },
    },
  },
  ["387"] = {
    species="TURTWIG", sourceDex=387,
    root="assets/non_crystal_hd_67/front/normal/387",
    scale=1.5, durations={ 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 600, 150, 150, 100, 600, 150, 600 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/387",
        scale=1.5, durations={ 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 600, 150, 150, 100, 600, 150, 600 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/387",
        scale=1.5, durations={ 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 600, 150, 150, 100, 600, 150, 600 },
      },
    },
  },
  ["388"] = {
    species="GROTLE", sourceDex=388,
    root="assets/non_crystal_hd_67/front/normal/388",
    scale=1.5, durations={ 150, 150, 100, 200, 100, 150, 150, 150, 150, 450, 150, 100, 150, 100, 150, 150, 150, 150, 100, 150, 100, 200, 100, 150, 100, 600 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/388",
        scale=1.5, durations={ 150, 150, 100, 200, 100, 150, 150, 150, 150, 450, 150, 100, 150, 100, 150, 150, 150, 150, 100, 150, 100, 200, 100, 150, 100, 600 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/388",
        scale=1.5, durations={ 150, 150, 100, 200, 100, 150, 150, 150, 150, 450, 150, 100, 150, 100, 150, 150, 150, 150, 100, 150, 100, 200, 100, 150, 100, 600 },
      },
    },
  },
  ["389"] = {
    species="TORTERRA", sourceDex=389,
    root="assets/non_crystal_hd_67/front/normal/389",
    scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 700 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/389",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 700 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/389",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 700 },
      },
    },
  },
  ["390"] = {
    species="CHIMCHAR", sourceDex=390,
    root="assets/non_crystal_hd_67/front/normal/390",
    scale=1.5, durations={ 260, 120, 120, 120, 120, 120, 260, 120, 120, 120, 260, 120 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/390",
        scale=1.5, durations={ 260, 120, 120, 120, 120, 120, 260, 120, 120, 120, 260, 120 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/390",
        scale=1.5, durations={ 260, 120, 120, 120, 120, 120, 260, 120, 120, 120, 260, 120 },
      },
    },
  },
  ["393"] = {
    species="PIPLUP", sourceDex=393,
    root="assets/non_crystal_hd_67/front/normal/393",
    scale=1.5, durations={ 400, 200, 200, 200, 200, 200, 200, 600, 150, 150, 150, 150, 150, 150, 600 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/393",
        scale=1.5, durations={ 400, 200, 200, 200, 200, 200, 200, 600, 150, 150, 150, 150, 150, 150, 600 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/393",
        scale=1.5, durations={ 400, 200, 200, 200, 200, 200, 200, 600, 150, 150, 150, 150, 150, 150, 600 },
      },
    },
  },
  ["394"] = {
    species="PRINPLUP", sourceDex=394,
    root="assets/non_crystal_hd_67/front/normal/394",
    scale=1.5, durations={ 150, 150, 150, 150, 150, 150, 200, 1000, 150, 150, 150, 150, 150, 150, 80, 120, 150 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/394",
        scale=1.5, durations={ 150, 150, 150, 150, 150, 150, 200, 1000, 150, 150, 150, 150, 150, 150, 80, 120, 150 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/394",
        scale=1.5, durations={ 150, 150, 150, 150, 150, 150, 200, 1000, 150, 150, 150, 150, 150, 150, 80, 120, 150 },
      },
    },
  },
  ["433"] = {
    species="CHINGLING", sourceDex=433,
    root="assets/non_crystal_hd_67/front/normal/433",
    scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 300, 200 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/433",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 300, 200 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/433",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 300, 200 },
      },
    },
  },
  ["439"] = {
    species="MIME_JR", sourceDex=439,
    root="assets/non_crystal_hd_67/front/normal/439",
    scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 500 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/439",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 500 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/439",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 500 },
      },
    },
  },
  ["440"] = {
    species="HAPPINY", sourceDex=440,
    root="assets/non_crystal_hd_67/front/normal/440",
    scale=1.5, durations={ 100, 100, 100, 100, 600 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/440",
        scale=1.5, durations={ 100, 100, 100, 100, 600 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/440",
        scale=1.5, durations={ 100, 100, 100, 100, 600 },
      },
    },
  },
  ["446"] = {
    species="MUNCHLAX", sourceDex=446,
    root="assets/non_crystal_hd_67/front/normal/446",
    scale=1.5, durations={ 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 600 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/446",
        scale=1.5, durations={ 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 600 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/446",
        scale=1.5, durations={ 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 600 },
      },
    },
  },
  ["475"] = {
    species="GALLADE", sourceDex=475,
    root="assets/non_crystal_hd_67/front/normal/475",
    scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 300, 100, 100, 100, 100, 100, 400, 300 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/475",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 300, 100, 100, 100, 100, 100, 400, 300 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/475",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 100, 100, 300, 100, 100, 100, 100, 100, 400, 300 },
      },
    },
  },
  ["476"] = {
    species="PROBOPASS", sourceDex=476,
    root="assets/non_crystal_hd_67/front/normal/476",
    scale=1.5, durations={ 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 600 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/476",
        scale=1.5, durations={ 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 600 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/476",
        scale=1.5, durations={ 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 600 },
      },
    },
  },
  ["477"] = {
    species="DUSKNOIR", sourceDex=477,
    root="assets/non_crystal_hd_67/front/normal/477",
    scale=1.5, durations={ 200, 200, 200, 200, 400, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/477",
        scale=1.5, durations={ 200, 200, 200, 200, 400, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/477",
        scale=1.5, durations={ 200, 200, 200, 200, 400, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200 },
      },
    },
  },
  ["478"] = {
    species="FROSLASS", sourceDex=478,
    root="assets/non_crystal_hd_67/front/normal/478",
    scale=1.5, durations={ 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/478",
        scale=1.5, durations={ 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/478",
        scale=1.5, durations={ 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200 },
      },
    },
  },
  ["486"] = {
    species="REGIGIGAS", sourceDex=486,
    root="assets/non_crystal_hd_67/front/normal/486",
    scale=1.5, durations={ 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/486",
        scale=1.5, durations={ 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/486",
        scale=1.5, durations={ 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170, 170 },
      },
    },
  },
  ["495"] = {
    species="SNIVY", sourceDex=495,
    root="assets/non_crystal_hd_67/front/normal/495",
    scale=1.5, durations={ 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 200, 100, 600 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/495",
        scale=1.5, durations={ 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 200, 100, 600 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/495",
        scale=1.5, durations={ 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 200, 100, 600 },
      },
    },
  },
  ["498"] = {
    species="TEPIG", sourceDex=498,
    root="assets/non_crystal_hd_67/front/normal/498",
    scale=1.5, durations={ 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/498",
        scale=1.5, durations={ 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/498",
        scale=1.5, durations={ 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110 },
      },
    },
  },
  ["501"] = {
    species="OSHAWOTT", sourceDex=501,
    root="assets/non_crystal_hd_67/front/normal/501",
    scale=1.5, durations={ 100, 100, 100, 200, 100, 100, 100, 100, 100, 100, 100, 600 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/501",
        scale=1.5, durations={ 100, 100, 100, 200, 100, 100, 100, 100, 100, 100, 100, 600 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/501",
        scale=1.5, durations={ 100, 100, 100, 200, 100, 100, 100, 100, 100, 100, 100, 600 },
      },
    },
  },
  ["3261"] = {
    species="POOCHYENA", sourceDex=261,
    root="assets/non_crystal_hd_67/front/normal/3261",
    scale=1.5, durations={ 20, 60, 200, 60, 80, 80, 80, 80, 80, 60, 60, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/3261",
        scale=1.5, durations={ 20, 60, 200, 60, 80, 80, 80, 80, 80, 60, 60, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/3261",
        scale=1.5, durations={ 20, 60, 200, 60, 80, 80, 80, 80, 80, 60, 60, 60, 1000 },
      },
    },
  },
  ["3262"] = {
    species="MIGHTYENA", sourceDex=262,
    root="assets/non_crystal_hd_67/front/normal/3262",
    scale=1.5, durations={ 20, 80, 60, 230, 80, 180, 60, 60, 60, 60, 60, 60, 150, 60, 200, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/3262",
        scale=1.5, durations={ 20, 80, 60, 230, 80, 180, 60, 60, 60, 60, 60, 60, 150, 60, 200, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/3262",
        scale=1.5, durations={ 20, 80, 60, 230, 80, 180, 60, 60, 60, 60, 60, 60, 150, 60, 200, 1000 },
      },
    },
  },
  ["3263"] = {
    species="ZIGZAGOON", sourceDex=263,
    root="assets/non_crystal_hd_67/front/normal/3263",
    scale=1.5, durations={ 50, 60, 160, 120, 90, 90, 90, 90, 90, 120, 60, 60, 60, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/3263",
        scale=1.5, durations={ 50, 60, 160, 120, 90, 90, 90, 90, 90, 120, 60, 60, 60, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/3263",
        scale=1.5, durations={ 50, 60, 160, 120, 90, 90, 90, 90, 90, 120, 60, 60, 60, 60, 1000 },
      },
    },
  },
  ["3264"] = {
    species="LINOONE", sourceDex=264,
    root="assets/non_crystal_hd_67/front/normal/3264",
    scale=1.5, durations={ 20, 60, 80, 80, 70, 80, 80, 70, 70, 80, 70, 70, 60, 60, 60, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/3264",
        scale=1.5, durations={ 20, 60, 80, 80, 70, 80, 80, 70, 70, 80, 70, 70, 60, 60, 60, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/3264",
        scale=1.5, durations={ 20, 60, 80, 80, 70, 80, 80, 70, 70, 80, 70, 70, 60, 60, 60, 60, 1000 },
      },
    },
  },
  ["3265"] = {
    species="WURMPLE", sourceDex=265,
    root="assets/non_crystal_hd_67/front/normal/3265",
    scale=1.5, durations={ 20, 60, 60, 60, 120, 60, 60, 120, 60, 60, 60, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/3265",
        scale=1.5, durations={ 20, 60, 60, 60, 120, 60, 60, 120, 60, 60, 60, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/3265",
        scale=1.5, durations={ 70, 60, 60, 120, 60, 60, 120, 60, 60, 60, 60, 1000 },
      },
    },
  },
  ["3266"] = {
    species="SILCOON", sourceDex=266,
    root="assets/non_crystal_hd_67/front/normal/3266",
    scale=1.5, durations={ 20, 120, 120, 120, 120, 120, 120, 160, 60, 60, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/3266",
        scale=1.5, durations={ 20, 120, 120, 120, 120, 120, 120, 160, 60, 60, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/3266",
        scale=1.5, durations={ 20, 120, 120, 120, 120, 120, 120, 160, 60, 60, 60, 1000 },
      },
    },
  },
  ["3267"] = {
    species="BEAUTIFLY", sourceDex=267,
    root="assets/non_crystal_hd_67/front/normal/3267",
    scale=1.5, durations={ 20, 80, 20, 160, 80, 60, 60, 60, 60, 100, 100, 100, 100, 100, 100, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/3267",
        scale=1.5, durations={ 20, 80, 20, 160, 80, 60, 60, 60, 60, 100, 100, 100, 100, 100, 100, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/3267",
        scale=1.5, durations={ 20, 80, 20, 160, 80, 60, 60, 60, 60, 100, 100, 100, 100, 100, 100, 1000 },
      },
    },
  },
  ["3268"] = {
    species="CASCOON", sourceDex=268,
    root="assets/non_crystal_hd_67/front/normal/3268",
    scale=1.5, durations={ 20, 120, 120, 120, 120, 120, 160, 60, 60, 60, 60, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/3268",
        scale=1.5, durations={ 20, 120, 120, 120, 120, 120, 160, 60, 60, 60, 60, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/3268",
        scale=1.5, durations={ 20, 120, 120, 120, 120, 120, 160, 60, 60, 60, 60, 60, 1000 },
      },
    },
  },
  ["3269"] = {
    species="DUSTOX", sourceDex=269,
    root="assets/non_crystal_hd_67/front/normal/3269",
    scale=1.5, durations={ 20, 40, 200, 100, 100, 60, 60, 60, 60, 60, 60, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/3269",
        scale=1.5, durations={ 20, 40, 200, 100, 100, 60, 60, 60, 60, 60, 60, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/3269",
        scale=1.5, durations={ 20, 40, 200, 100, 100, 60, 60, 60, 60, 60, 60, 60, 1000 },
      },
    },
  },
  ["3270"] = {
    species="LOTAD", sourceDex=270,
    root="assets/non_crystal_hd_67/front/normal/3270",
    scale=1.5, durations={ 20, 40, 160, 80, 80, 80, 60, 60, 60, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/3270",
        scale=1.5, durations={ 20, 40, 160, 80, 80, 80, 60, 60, 60, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/3270",
        scale=1.5, durations={ 20, 40, 160, 80, 80, 80, 60, 60, 60, 60, 1000 },
      },
    },
  },
  ["3271"] = {
    species="LOMBRE", sourceDex=271,
    root="assets/non_crystal_hd_67/front/normal/3271",
    scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 300 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/3271",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 300 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/3271",
        scale=1.5, durations={ 100, 100, 100, 100, 100, 100, 100, 300 },
      },
    },
  },
  ["3272"] = {
    species="LUDICOLO", sourceDex=272,
    root="assets/non_crystal_hd_67/front/normal/3272",
    scale=1.5, durations={ 20, 60, 40, 80, 80, 80, 100, 100, 100, 100, 60, 60, 60, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/3272",
        scale=1.5, durations={ 20, 60, 40, 80, 80, 80, 100, 100, 100, 100, 60, 60, 60, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/3272",
        scale=1.5, durations={ 20, 60, 40, 80, 80, 80, 100, 100, 100, 100, 60, 60, 60, 60, 1000 },
      },
    },
  },
  ["3273"] = {
    species="SEEDOT", sourceDex=273,
    root="assets/non_crystal_hd_67/front/normal/3273",
    scale=1.5, durations={ 20, 120, 20, 20, 20, 20, 20, 20, 20, 20, 20, 40, 40, 40, 40, 80, 80, 80, 80, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/3273",
        scale=1.5, durations={ 20, 120, 20, 20, 20, 20, 20, 20, 20, 20, 20, 40, 40, 40, 40, 80, 80, 80, 80, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/3273",
        scale=1.5, durations={ 20, 120, 20, 20, 20, 20, 20, 20, 20, 20, 20, 40, 40, 40, 40, 80, 80, 80, 80, 1000 },
      },
    },
  },
  ["3274"] = {
    species="NUZLEAF", sourceDex=274,
    root="assets/non_crystal_hd_67/front/normal/3274",
    scale=1.5, durations={ 20, 40, 80, 80, 80, 120, 120, 120, 120, 40, 120, 60, 60, 80, 80, 80, 90, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/3274",
        scale=1.5, durations={ 20, 40, 80, 80, 80, 120, 120, 120, 120, 40, 120, 60, 60, 80, 80, 80, 90, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/3274",
        scale=1.5, durations={ 20, 40, 80, 80, 80, 120, 120, 120, 120, 40, 120, 60, 60, 80, 80, 80, 90, 1000 },
      },
    },
  },
  ["3275"] = {
    species="SHIFTRY", sourceDex=275,
    root="assets/non_crystal_hd_67/front/normal/3275",
    scale=1.5, durations={ 20, 60, 80, 60, 160, 80, 120, 120, 80, 120, 60, 60, 60, 60, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/3275",
        scale=1.5, durations={ 20, 60, 80, 60, 160, 80, 120, 120, 80, 120, 60, 60, 60, 60, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/3275",
        scale=1.5, durations={ 20, 60, 80, 60, 160, 80, 120, 120, 80, 120, 60, 60, 60, 60, 60, 1000 },
      },
    },
  },
  ["3276"] = {
    species="TAILLOW", sourceDex=276,
    root="assets/non_crystal_hd_67/front/normal/3276",
    scale=1.5, durations={ 20, 120, 120, 80, 80, 60, 160, 60, 60, 60, 60, 60, 60, 80, 40, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/3276",
        scale=1.5, durations={ 20, 120, 120, 80, 80, 60, 160, 60, 60, 60, 60, 60, 60, 80, 40, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/3276",
        scale=1.5, durations={ 20, 120, 120, 80, 80, 60, 160, 60, 60, 60, 60, 60, 60, 80, 40, 1000 },
      },
    },
  },
  ["3277"] = {
    species="SWELLOW", sourceDex=277,
    root="assets/non_crystal_hd_67/front/normal/3277",
    scale=1.5, durations={ 20, 60, 120, 80, 160, 80, 80, 120, 60, 80, 50, 60, 80, 60, 60, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/3277",
        scale=1.5, durations={ 20, 60, 120, 80, 160, 80, 80, 120, 60, 80, 50, 60, 80, 60, 60, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/3277",
        scale=1.5, durations={ 20, 60, 120, 80, 160, 80, 80, 120, 60, 80, 50, 60, 80, 60, 60, 60, 1000 },
      },
    },
  },
  ["3278"] = {
    species="WINGULL", sourceDex=278,
    root="assets/non_crystal_hd_67/front/normal/3278",
    scale=1.5, durations={ 20, 90, 50, 140, 40, 70, 50, 130, 60, 50, 50, 50, 50, 40, 40, 40, 40, 120, 30, 80, 60, 100, 50, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/3278",
        scale=1.5, durations={ 20, 90, 50, 140, 40, 70, 50, 130, 60, 50, 50, 50, 50, 40, 40, 40, 40, 120, 30, 80, 60, 100, 50, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/3278",
        scale=1.5, durations={ 20, 90, 50, 140, 40, 70, 50, 130, 60, 50, 50, 50, 50, 40, 40, 40, 40, 120, 30, 80, 60, 100, 50, 1000 },
      },
    },
  },
  ["3279"] = {
    species="PELIPPER", sourceDex=279,
    root="assets/non_crystal_hd_67/front/normal/3279",
    scale=1.5, durations={ 20, 80, 150, 240, 120, 100, 100, 80, 80, 60, 60, 60, 60, 60, 60, 1000 },
    variants={
      normal={
        root="assets/non_crystal_hd_67/front/normal/3279",
        scale=1.5, durations={ 20, 80, 150, 240, 120, 100, 100, 80, 80, 60, 60, 60, 60, 60, 60, 1000 },
      },
      shiny={
        root="assets/non_crystal_hd_67/front/shiny/3279",
        scale=1.5, durations={ 20, 80, 150, 240, 120, 100, 100, 80, 80, 60, 60, 60, 60, 60, 60, 1000 },
      },
    },
  },
}
