-- Kanto Ascendant 6.7 Surprise Trainer title catalogue.
--
-- Every row is authored deliberately.  This is not the rejected adjective /
-- noun combiner from the early 6.7 scratch work: ids, translations, rarity,
-- tone and contextual category are all stable save data.

local DEFAULT_MIN_WINS = {
  common = 0, uncommon = 3, rare = 8, epic = 15, legendary = 25,
}

local HINTS = {
  route = {
    en = "Meet Surprise Trainers while exploring Kanto's routes.",
    de = "Triff Überraschungstrainer auf Kantos Routen.",
  },
  city = {
    en = "Meet Surprise Trainers in Kanto's towns and cities.",
    de = "Triff Überraschungstrainer in Kantos Städten.",
  },
  trainer = {
    en = "Defeat many different Surprise Trainer classes.",
    de = "Besiege viele Klassen von Überraschungstrainern.",
  },
  type = {
    en = "Win Surprise battles with a varied, type-aware team.",
    de = "Gewinne Überraschungskämpfe mit vielfältigen Typen.",
  },
  tactics = {
    en = "Build a longer Surprise Trainer winning record.",
    de = "Baue eine längere Überraschungssieg-Serie auf.",
  },
  discovery = {
    en = "Advance Kanto, Johto and Hoenn field research.",
    de = "Bringe Kanto-, Johto- und Hoenn-Forschung voran.",
  },
  journey = {
    en = "Continue a Legacy Journey through Kanto.",
    de = "Setze eine Vermächtnisreise durch Kanto fort.",
  },
  legacy = {
    en = "Complete character paths and preserve their seals.",
    de = "Vollende Figurenpfade und bewahre ihre Siegel.",
  },
  humour = {
    en = "Surprise Trainers remember Kanto's less glorious moments.",
    de = "Überraschungstrainer merken sich Kantos kleine Pannen.",
  },
  mythic = {
    en = "Reach Kanto Ascendant's rarest discoveries and trials.",
    de = "Erreiche die seltensten Entdeckungen und Prüfungen.",
  },
}

local function title(id, en, de, rarity, tone, category, extra)
  extra = extra or {}
  local row = {
    id = "surprise_" .. id,
    en = en,
    de = de,
    rarity = rarity,
    tone = tone,
    category = category,
    minWins = extra.minWins or DEFAULT_MIN_WINS[rarity],
    hint = extra.hint or HINTS[category],
  }
  for key, value in pairs(extra) do
    if key ~= "minWins" and key ~= "hint" then row[key] = value end
  end
  return row
end

local titles = {
  -- Routes and natural boundaries (01-20)
  title("route_scout", "ROUTE SCOUT", "ROUTENSPÄHER", "common", "neutral", "route"),
  title("ledge_runner", "LEDGE RUNNER", "KLIPPENLÄUFER", "common", "proud", "route"),
  title("moon_passer", "MT. MOON PILGRIM", "MONDBERG-PILGER", "common", "neutral", "route"),
  title("bridge_walker", "BRIDGE WALKER", "BRÜCKENWANDERER", "common", "neutral", "route"),
  title("coast_hopper", "COAST HOPPER", "KÜSTENSPRINGER", "common", "proud", "route"),
  title("forest_wayfinder", "FOREST WAYFINDER", "WALDWEISER", "common", "neutral", "route"),
  title("tunnel_lantern", "TUNNEL LANTERN", "TUNNELLATERNE", "uncommon", "neutral", "route"),
  title("cycling_road_ace", "CYCLING ROAD ACE", "RADWEG-ASS", "uncommon", "proud", "route"),
  title("seafoam_pathfinder", "SEAFOAM PATHFINDER", "SEESCHAUM-SPÄHER", "uncommon", "neutral", "route"),
  title("victory_road_veteran", "VICTORY ROAD VETERAN", "SIEGESSTRASSEN-PROFI", "uncommon", "proud", "route", {
    maps = { "VICTORY_ROAD_1F", "VICTORY_ROAD_2F", "VICTORY_ROAD_3F" },
  }),
  title("kanto_cartographer", "KANTO CARTOGRAPHER", "KANTO-KARTOGRAF", "uncommon", "neutral", "route"),
  title("hidden_pathfinder", "HIDDEN PATHFINDER", "GEHEIMPFAD-FINDER", "rare", "proud", "route"),
  title("riverbank_ranger", "RIVERBANK RANGER", "UFERWÄCHTER", "rare", "neutral", "route"),
  title("ridge_whisperer", "RIDGE WHISPERER", "KLIPPENFLÜSTERER", "rare", "neutral", "route"),
  title("crossroad_champ", "CROSSROAD CHAMP", "KREUZWEG-CHAMP", "rare", "proud", "route"),
  title("twilight_trekker", "TWILIGHT TREKKER", "DÄMMERWANDERER", "epic", "neutral", "route"),
  title("border_breaker", "BORDER BREAKER", "GRENZBRECHER", "epic", "proud", "route"),
  title("twenty_five_trails", "TWENTY-FIVE TRAILS", "25-PFADE-WANDERER", "epic", "proud", "route"),
  title("edge_of_kanto", "EDGE OF KANTO", "KANTOS RANDGÄNGER", "epic", "neutral", "route"),
  title("master_of_milestones", "MASTER OF MILESTONES", "MEILENSTEIN-MEISTER", "legendary", "proud", "route"),

  -- Towns and cities (21-40)
  title("pallet_promise", "PALLET PROMISE", "ALABASTIA-VERSPRECHEN", "common", "neutral", "city"),
  title("viridian_vanguard", "VIRIDIAN VANGUARD", "VERTANIA-VORHUT", "common", "proud", "city"),
  title("pewter_pillar", "PEWTER PILLAR", "MARMORIA-SÄULE", "common", "proud", "city"),
  title("cerulean_current", "CERULEAN CURRENT", "AZURIA-STRÖMUNG", "common", "neutral", "city"),
  title("vermilion_volt", "VERMILION VOLT", "ORANIA-BLITZ", "common", "proud", "city"),
  title("lavender_listener", "LAVENDER LISTENER", "LAVANDIA-LAUSCHER", "common", "neutral", "city"),
  title("celadon_style", "CELADON STYLE", "PRISMANIA-STIL", "uncommon", "proud", "city"),
  title("fuchsia_tracker", "FUCHSIA TRACKER", "FUCHSANIA-SPÜRER", "uncommon", "neutral", "city"),
  title("saffron_signal", "SAFFRON SIGNAL", "SAFFRONIA-SIGNAL", "uncommon", "neutral", "city"),
  title("cinnabar_ember", "CINNABAR EMBER", "ZINNOBER-FUNKE", "uncommon", "proud", "city"),
  title("indigo_arrival", "INDIGO ARRIVAL", "INDIGO-ANKUNFT", "uncommon", "proud", "city"),
  title("kanto_commuter", "KANTO COMMUTER", "KANTO-PENDLER", "rare", "neutral", "city"),
  title("city_circuit", "CITY CIRCUIT", "STÄDTE-RUNDE", "rare", "proud", "city"),
  title("market_regular", "MARKET REGULAR", "MARKT-STAMMGAST", "rare", "neutral", "city"),
  title("dojo_guest", "DOJO GUEST", "DOJO-GAST", "rare", "neutral", "city"),
  title("mansion_visitor", "MANSION VISITOR", "VILLA-BESUCHER", "epic", "neutral", "city"),
  title("harbor_hero", "HARBOR HERO", "HAFEN-HELD", "epic", "proud", "city"),
  title("rooftop_dreamer", "ROOFTOP DREAMER", "DACH-TRÄUMER", "epic", "neutral", "city"),
  title("ten_town_triumph", "TEN-TOWN TRIUMPH", "ZEHN-STÄDTE-SIEG", "epic", "proud", "city"),
  title("kanto_homecoming", "KANTO HOMECOMING", "KANTOS HEIMKEHR", "legendary", "proud", "city"),

  -- Trainer classes (41-60)
  title("youngster_measure", "YOUNGSTER'S RESPECT", "KNIRPS-RESPEKT", "common", "neutral", "trainer"),
  title("bug_net_rival", "BUG NET RIVAL", "KÄFERNETZ-RIVALE", "common", "proud", "trainer"),
  title("lass_challenge", "LASS'S CHALLENGE", "GÖREN-PRÜFUNG", "common", "neutral", "trainer"),
  title("hiker_handshake", "HIKER'S HANDSHAKE", "WANDERER-HANDSCHLAG", "common", "neutral", "trainer"),
  title("sailor_salute", "SAILOR'S SALUTE", "MATROSEN-GRUSS", "common", "proud", "trainer", {
    classes = { "OPP_SAILOR" },
  }),
  title("science_sparring", "SCIENCE SPARRING", "FORSCHER-DUELL", "common", "neutral", "trainer"),
  title("psychic_proof", "PSYCHIC TRIAL", "PSYCHO-PRÜFUNG", "uncommon", "proud", "trainer"),
  title("black_belt_test", "BLACK BELT TEST", "SCHWARZGURT-TEST", "uncommon", "proud", "trainer"),
  title("bird_keeper_eye", "BIRD KEEPER'S EYE", "VOGELHÜTER-BLICK", "uncommon", "neutral", "trainer"),
  title("biker_respect", "BIKER'S RESPECT", "BIKER-RESPEKT", "uncommon", "proud", "trainer"),
  title("beauty_verdict", "BEAUTY'S VERDICT", "SCHÖNHEITS-URTEIL", "uncommon", "neutral", "trainer"),
  title("gambler_tell", "GAMBLER'S TELL", "SPIELER-POKERBLICK", "rare", "neutral", "trainer"),
  title("tamer_nod", "TAMER'S NOD", "DOMPTEUR-NICKEN", "rare", "proud", "trainer"),
  title("juggler_rhythm", "JUGGLER'S RHYTHM", "JONGLEUR-RHYTHMUS", "rare", "neutral", "trainer"),
  title("engineer_spark", "ENGINEER'S SPARK", "TECHNIKER-FUNKE", "rare", "proud", "trainer"),
  title("cooltrainer_standard", "COOLTRAINER STANDARD", "ASS-TRAINER-MASS", "epic", "proud", "trainer"),
  title("class_collector", "CLASS COLLECTOR", "KLASSEN-KENNER", "epic", "neutral", "trainer"),
  title("road_duelist", "ROAD DUELIST", "STRASSEN-DUELLANT", "epic", "proud", "trainer"),
  title("every_trainer_test", "TRAINER CLASS TRIAL", "TRAINERKLASSEN-PRÜFUNG", "epic", "proud", "trainer"),
  title("trainers_trainer", "TRAINERS' TRAINER", "TRAINER DER TRAINER", "legendary", "proud", "trainer"),

  -- Type awareness (61-80)
  title("normal_natural", "NORMAL NATURAL", "NORMAL-NATURTALENT", "common", "neutral", "type", { partyType = "NORMAL" }),
  title("flame_tactician", "FLAME TACTICIAN", "FEUER-TAKTIKER", "common", "proud", "type", { partyType = "FIRE" }),
  title("waterline_warden", "WATERLINE WARDEN", "WASSER-WÄCHTER", "common", "neutral", "type", { partyType = "WATER" }),
  title("volt_virtuoso", "VOLT VIRTUOSO", "ELEKTRO-VIRTUOSE", "common", "proud", "type", { partyType = "ELECTRIC" }),
  title("grassroot_champ", "GRASS-TYPE CHAMP", "PFLANZEN-CHAMP", "common", "proud", "type", { partyType = "GRASS" }),
  title("frost_reader", "FROST READER", "EIS-LESER", "common", "neutral", "type", { partyType = "ICE" }),
  title("fighting_spirit", "FIGHTING SPIRIT", "KAMPFGEIST", "uncommon", "proud", "type", { partyType = "FIGHTING" }),
  title("venom_handler", "VENOM HANDLER", "GIFT-BÄNDIGER", "uncommon", "neutral", "type", { partyType = "POISON" }),
  title("earth_anchor", "EARTH ANCHOR", "BODEN-ANKER", "uncommon", "neutral", "type", { partyType = "GROUND" }),
  title("sky_formation", "SKY FORMATION", "FLUG-FORMATION", "uncommon", "proud", "type", { partyType = "FLYING" }),
  title("mind_over_match", "MIND OVER MATCH", "PSYCHO-TAKTIK", "uncommon", "proud", "type", { partyType = "PSYCHIC" }),
  title("swarm_captain", "SWARM CAPTAIN", "KÄFER-KAPITÄN", "rare", "proud", "type", { partyType = "BUG" }),
  title("stone_standard", "STONE STANDARD", "GESTEINS-STANDARTE", "rare", "neutral", "type", { partyType = "ROCK" }),
  title("phantom_nerve", "PHANTOM COURAGE", "GEISTER-MUT", "rare", "neutral", "type", { partyType = "GHOST" }),
  title("dragon_temper", "DRAGON TEMPER", "DRACHEN-TEMPERAMENT", "rare", "proud", "type", { partyType = "DRAGON" }),
  title("night_strategist", "NIGHT STRATEGIST", "UNLICHT-STRATEGE", "epic", "neutral", "type", { partyType = "DARK" }),
  title("steel_resolve", "STEEL RESOLVE", "STAHL-WILLE", "epic", "proud", "type", { partyType = "STEEL" }),
  title("fairy_footwork", "FAIRY FOOTWORK", "FEEN-FINESSE", "epic", "neutral", "type", { partyType = "FAIRY" }),
  title("type_polyglot", "TYPE POLYGLOT", "TYPEN-POLYGLOTT", "epic", "proud", "type", { minPartyTypes = 4 }),
  title("elemental_crown", "ELEMENTAL CROWN", "TYPEN-KRONE", "legendary", "proud", "type", { minPartyTypes = 6 }),

  -- Battle craft (81-100)
  title("clean_switch", "CLEAN SWITCH", "SAUBERER WECHSEL", "common", "neutral", "tactics"),
  title("status_scholar", "STATUS SCHOLAR", "STATUS-GELEHRTER", "common", "neutral", "tactics"),
  title("critical_thinker", "CRITICAL THINKER", "VOLLTREFFER-DENKER", "common", "teasing", "tactics"),
  title("pp_planner", "PP PLANNER", "AP-PLANER", "common", "neutral", "tactics"),
  title("setup_breaker", "SETUP BREAKER", "SETUP-BRECHER", "common", "proud", "tactics"),
  title("weather_reader", "WEATHER READER", "WETTER-LESER", "common", "neutral", "tactics"),
  title("screen_shatterer", "SCREEN SHATTERER", "SCHIRM-ZERSTÖRER", "uncommon", "proud", "tactics"),
  title("priority_pilot", "PRIORITY PILOT", "PRIORITÄTS-PILOT", "uncommon", "neutral", "tactics"),
  title("switch_predictor", "SWITCH PREDICTOR", "WECHSEL-PROPHET", "uncommon", "proud", "tactics"),
  title("endgame_closer", "ENDGAME CLOSER", "ENDSPIEL-VOLLSTRECKER", "uncommon", "proud", "tactics"),
  title("four_mon_finish", "FOUR-MON VICTORY", "VIER-MON-SIEG", "uncommon", "neutral", "tactics"),
  title("no_item_victor", "NO-ITEM VICTOR", "OHNE-ITEM-SIEGER", "rare", "proud", "tactics"),
  title("comeback_engine", "COMEBACK ENGINE", "COMEBACK-MOTOR", "rare", "proud", "tactics"),
  title("streak_keeper", "STREAK KEEPER", "SERIEN-HÜTER", "rare", "neutral", "tactics"),
  title("perfect_pressure", "PERFECT PRESSURE", "PERFEKTER DRUCK", "rare", "proud", "tactics"),
  title("one_hp_wonder", "ONE-HP WONDER", "EIN-KP-WUNDER", "epic", "teasing", "tactics"),
  title("read_the_lead", "READ THE LEAD", "LEAD DURCHSCHAUT", "epic", "proud", "tactics"),
  title("safe_sacrifice", "SAFE SACRIFICE", "KLUGES OPFER", "epic", "neutral", "tactics"),
  title("checkmate_turn", "CHECKMATE TURN", "SCHACHMATT-ZUG", "epic", "proud", "tactics"),
  title("battle_architect", "BATTLE ARCHITECT", "KAMPF-ARCHITEKT", "legendary", "proud", "tactics"),

  -- Discovery and habitats (101-120)
  title("signal_seeker", "SIGNAL SEEKER", "SIGNAL-SUCHER", "common", "neutral", "discovery"),
  title("trace_finder", "TRACE FINDER", "SPUREN-FINDER", "common", "neutral", "discovery"),
  title("habitat_guest", "HABITAT GUEST", "HABITAT-GAST", "common", "neutral", "discovery"),
  title("research_partner", "RESEARCH PARTNER", "FORSCHUNGS-PARTNER", "common", "proud", "discovery"),
  title("rare_sighting", "RARE SIGHTING", "SELTENE SICHTUNG", "common", "neutral", "discovery"),
  title("footprint_reader", "FOOTPRINT READER", "SPURENLESER", "common", "neutral", "discovery"),
  title("hidden_grove_guest", "HIDDEN GROVE GUEST", "HAIN-BESUCHER", "uncommon", "neutral", "discovery"),
  title("caldera_witness", "CALDERA WITNESS", "CALDERA-ZEUGE", "uncommon", "proud", "discovery", { proof = "groudonCaught" }),
  title("abyss_witness", "ABYSS WITNESS", "ABGRUND-ZEUGE", "uncommon", "proud", "discovery", { proof = "kyogreCaught" }),
  title("sky_pillar_witness", "SKY PILLAR WITNESS", "HIMMELTURM-ZEUGE", "uncommon", "proud", "discovery", { proof = "rayquazaCaught" }),
  title("wish_chamber_guest", "WISH CHAMBER GUEST", "WUNSCHKAMMER-GAST", "uncommon", "neutral", "discovery", { proof = "jirachiCaught" }),
  title("twelve_habitats", "TWELVE HABITATS", "ZWÖLF HABITATE", "rare", "proud", "discovery"),
  title("starter_naturalist", "STARTER NATURALIST", "STARTER-NATURKUNDLER", "rare", "neutral", "discovery"),
  title("hoenn_echo", "HOENN ECHO", "HOENN-ECHO", "rare", "neutral", "discovery"),
  title("johto_frequency", "JOHTO FREQUENCY", "JOHTO-FREQUENZ", "rare", "neutral", "discovery"),
  title("kanto_completionist", "KANTO COMPLETIONIST", "KANTO-KOMPLETTIST", "epic", "proud", "discovery"),
  title("shiny_footprint", "SHINY FOOTPRINT", "SCHILLERNDE SPUR", "epic", "neutral", "discovery"),
  title("field_note_master", "FIELD NOTE MASTER", "FELDNOTIZ-MEISTER", "epic", "proud", "discovery"),
  title("discovery_ascendant", "DISCOVERY ASCENDANT", "ENTDECKER-ASCENDANT", "epic", "proud", "discovery"),
  title("living_pokedex", "LIVING POKEDEX", "LEBENDER POKEDEX", "legendary", "proud", "discovery", { proof = "livingPokedex" }),

  -- Legacy Journey cadence (121-140)
  title("first_badge_forward", "FIRST BADGE RECLAIMED", "ERSTER ORDEN ZURÜCK", "common", "neutral", "journey"),
  title("eight_badge_return", "EIGHT-BADGE RETURN", "ACHT-ORDEN-RÜCKKEHR", "common", "proud", "journey"),
  title("league_again", "LEAGUE AGAIN", "LIGA NOCH EINMAL", "common", "teasing", "journey"),
  title("fresh_start_veteran", "FRESH START VETERAN", "NEUSTART-VETERAN", "common", "proud", "journey"),
  title("empty_bag_brave", "EMPTY-BAG COURAGE", "MUT TROTZ LEEREM BEUTEL", "common", "teasing", "journey"),
  title("sealed_bank", "SEALED BANK", "VERSIEGELTE BANK", "common", "neutral", "journey"),
  title("legacy_partner", "LEGACY PARTNER", "VERMÄCHTNIS-PARTNER", "uncommon", "proud", "journey"),
  title("second_journey", "SECOND JOURNEY", "ZWEITE REISE", "uncommon", "neutral", "journey"),
  title("third_journey", "THIRD JOURNEY", "DRITTE REISE", "uncommon", "proud", "journey"),
  title("road_remembers", "THE ROAD REMEMBERS", "DER WEG ERINNERT SICH", "uncommon", "neutral", "journey"),
  title("badge_rebuilder", "BADGE REBUILDER", "ORDENS-ERNEUERER", "uncommon", "proud", "journey"),
  title("old_team_new_road", "OLD TEAM, NEW ROAD", "ALTES TEAM, NEUER WEG", "rare", "neutral", "journey"),
  title("oak_returning_ace", "OAK'S RETURNING ACE", "EICHS HEIMKEHR-ASS", "rare", "proud", "journey"),
  title("journey_pact", "JOURNEY PACT", "REISE-PAKT", "rare", "neutral", "journey"),
  title("trainer_pact", "TRAINER PACT", "TRAINER-PAKT", "rare", "proud", "journey"),
  title("legacy_pact", "LEGACY PACT", "VERMÄCHTNIS-PAKT", "epic", "proud", "journey"),
  title("ascendant_pact", "ASCENDANT PACT", "ASCENDANT-PAKT", "epic", "proud", "journey"),
  title("fourth_dawn", "FOURTH DAWN", "VIERTER MORGEN", "epic", "neutral", "journey"),
  title("cycle_keeper", "CYCLE KEEPER", "ZYKLUS-HÜTER", "epic", "neutral", "journey"),
  title("endless_kanto", "ENDLESS KANTO", "ENDLOSES KANTO", "legendary", "proud", "journey"),

  -- Character paths and durable legacy (141-160)
  title("red_seal_bearer", "RED SEAL BEARER", "ROTSIEGEL-TRÄGER", "common", "proud", "legacy"),
  title("blue_seal_bearer", "BLUE SEAL BEARER", "BLAUSIEGEL-TRÄGER", "common", "proud", "legacy"),
  title("green_seal_bearer", "GREEN SEAL BEARER", "GRÜNSIEGEL-TRÄGER", "common", "proud", "legacy"),
  title("three_seals", "THREE SEALS", "DREI SIEGEL", "common", "neutral", "legacy"),
  title("legacy_pass", "LEGACY PASS", "VERMÄCHTNIS-PASS", "common", "proud", "legacy"),
  title("groudon_equal", "GROUDON'S EQUAL", "GROUDON EBENBÜRTIG", "common", "proud", "legacy", { proof = "groudonCaught" }),
  title("kyogre_equal", "KYOGRE'S EQUAL", "KYOGRE EBENBÜRTIG", "uncommon", "proud", "legacy", { proof = "kyogreCaught" }),
  title("rayquaza_equal", "RAYQUAZA'S EQUAL", "RAYQUAZA EBENBÜRTIG", "uncommon", "proud", "legacy", { proof = "rayquazaCaught" }),
  title("jirachi_wish", "JIRACHI'S WISH", "JIRACHIS WUNSCH", "uncommon", "neutral", "legacy", { proof = "jirachiCaught" }),
  title("crown_archivist", "CROWN ARCHIVIST", "KRONEN-ARCHIVAR", "uncommon", "neutral", "legacy"),
  title("heir_to_kanto", "HEIR TO KANTO", "KANTOS ERBE", "uncommon", "proud", "legacy"),
  title("red_afterimage", "RED'S AFTERIMAGE", "ROTS NACHBILD", "rare", "neutral", "legacy"),
  title("blue_blueprint", "BLUE'S BLUEPRINT", "BLAUS BLAUPAUSE", "rare", "neutral", "legacy"),
  title("green_bond", "GREEN'S BOND", "GRÜNS BUND", "rare", "proud", "legacy"),
  title("four_heroes", "FOUR HEROES", "VIER HELDEN", "rare", "proud", "legacy"),
  title("old_legacy_new_legend", "OLD LEGACY, NEW LEGEND", "ALTES ERBE, NEUE SAGE", "epic", "neutral", "legacy"),
  title("archive_keeper", "ARCHIVE KEEPER", "ARCHIV-HÜTER", "epic", "neutral", "legacy"),
  title("timeline_walker", "TIMELINE WALKER", "ZEITLINIEN-WANDERER", "epic", "neutral", "legacy"),
  title("kanto_everlasting", "KANTO EVERLASTING", "KANTO UNVERGÄNGLICH", "epic", "proud", "legacy"),
  title("ascendant_legacy", "ASCENDANT LEGACY", "ASCENDANT-VERMÄCHTNIS", "legendary", "proud", "legacy"),

  -- Good-natured teasing (161-180)
  title("ledge_misjudge", "LEDGE MISJUDGE", "KLIPPEN-PATZER", "common", "teasing", "humour"),
  title("potion_panic", "POTION PANIC", "TRANK-PANIK", "common", "teasing", "humour"),
  title("switch_too_late", "SWITCH TOO LATE", "ZU SPÄT GEWECHSELT", "common", "teasing", "humour"),
  title("bag_full_again", "BAG FULL AGAIN", "BEUTEL WIEDER VOLL", "common", "teasing", "humour"),
  title("route_wrong_way", "WRONG ROUTE AGAIN", "WIEDER FALSCHE ROUTE", "common", "teasing", "humour"),
  title("critical_magnet", "CRITICAL MAGNET", "VOLLTREFFER-MAGNET", "common", "teasing", "humour"),
  title("one_more_repel", "ONE MORE REPEL", "NOCH EIN SCHUTZ", "uncommon", "teasing", "humour"),
  title("pc_box_shuffler", "PC BOX SHUFFLER", "BOXEN-SORTIERER", "uncommon", "teasing", "humour"),
  title("save_before_it", "SAVED BEFORE BATTLE", "VORM KAMPF GESPEICHERT", "uncommon", "teasing", "humour"),
  title("talked_to_everyone", "TALKED TO EVERYONE", "ALLE ANGEQUATSCHT", "uncommon", "teasing", "humour"),
  title("splash_expert", "SPLASH EXPERT", "PLATSCH-EXPERTE", "uncommon", "teasing", "humour"),
  title("missed_the_turn", "MISSED THE TURN", "ABBIEGUNG VERPASST", "rare", "teasing", "humour"),
  title("ran_from_shiny", "FLED FROM A SHINY", "VORM SHINY GEFLOHEN", "rare", "teasing", "humour"),
  title("no_room_for_items", "NO ROOM FOR ITEMS", "KEIN PLATZ FÜR ITEMS", "rare", "teasing", "humour"),
  title("lost_with_style", "LOST WITH STYLE", "STILVOLL VERLOREN", "rare", "teasing", "humour"),
  title("wrong_lead_again", "WRONG LEAD AGAIN", "WIEDER FALSCHER LEAD", "epic", "teasing", "humour"),
  title("master_ball_nerves", "MASTER BALL NERVES", "MEISTERBALL-NERVEN", "epic", "teasing", "humour"),
  title("which_badge", "BADGE? WHICH BADGE?", "ORDEN? WELCHER ORDEN?", "epic", "teasing", "humour"),
  title("professional_detour", "PROFESSIONAL DETOUR", "PROFI-UMWEG", "epic", "teasing", "humour"),
  title("kanto_good_loser", "KANTO'S GOOD LOSER", "KANTOS GUTER VERLIERER", "legendary", "teasing", "humour"),

  -- Mythic endgame (181-200)
  title("legend_listener", "LEGEND LISTENER", "LEGENDEN-LAUSCHER", "common", "neutral", "mythic"),
  title("mythic_tracker", "MYTHIC TRACKER", "MYTHEN-SPÜRER", "common", "neutral", "mythic"),
  title("moonlight_wish", "MOONLIGHT WISH", "MONDLICHT-WUNSCH", "common", "neutral", "mythic"),
  title("primal_balance", "PRIMAL BALANCE", "URZEIT-GLEICHGEWICHT", "common", "neutral", "mythic", { proofsAll = { "groudonCaught", "kyogreCaught" } }),
  title("land_witness", "LAND'S WITNESS", "ZEUGE DES LANDES", "common", "proud", "mythic", { proof = "groudonCaught" }),
  title("sea_witness", "SEA'S WITNESS", "ZEUGE DES MEERES", "common", "proud", "mythic", { proof = "kyogreCaught" }),
  title("sky_witness", "SKYWARD OATH", "HIMMELSSCHWUR", "uncommon", "proud", "mythic", { proof = "rayquazaCaught" }),
  title("wishmaker_friend", "WISHMAKER'S FRIEND", "JIRACHIS FREUND", "uncommon", "neutral", "mythic", { proof = "jirachiCaught" }),
  title("apex_of_kanto", "APEX OF KANTO", "KANTOS SPITZE", "uncommon", "proud", "mythic"),
  title("crown_without_end", "CROWN WITHOUT END", "KRONE OHNE ENDE", "uncommon", "proud", "mythic"),
  title("roamer_confidant", "ROAMER'S CONFIDANT", "STREUNER-VERTRAUTER", "uncommon", "neutral", "mythic"),
  title("beast_trinity", "BEAST TRINITY", "BESTIEN-DREIKLANG", "rare", "proud", "mythic"),
  title("tower_bell_heir", "BELL TOWER HEIR", "GLOCKENTURM-ERBE", "rare", "neutral", "mythic"),
  title("island_guardian", "ISLAND GUARDIAN", "INSEL-WÄCHTER", "rare", "proud", "mythic"),
  title("starfall_champion", "STARFALL CHAMPION", "STERNENFALL-CHAMP", "rare", "proud", "mythic"),
  title("three_world_witness", "THREE-WORLD WITNESS", "DREI-WELTEN-ZEUGE", "epic", "neutral", "mythic"),
  title("mythic_cartographer", "MYTHIC CARTOGRAPHER", "MYTHEN-KARTOGRAF", "epic", "neutral", "mythic"),
  title("dream_above_indigo", "DREAM ABOVE INDIGO", "TRAUM ÜBER INDIGO", "epic", "neutral", "mythic"),
  title("kanto_constellation", "KANTO CONSTELLATION", "KANTO-STERNBILD", "epic", "proud", "mythic"),
  title("wish_ascendant", "WISH ASCENDANT", "WUNSCH-ASCENDANT", "legendary", "proud", "mythic"),
}

return {
  version = 1,
  titles = titles,
  rarityOrder = { "common", "uncommon", "rare", "epic", "legendary" },
  rarityWeights = {
    common = 55, uncommon = 25, rare = 12, epic = 6, legendary = 2,
  },
}
