local engine=assert(os.getenv("GEN1RECOMP_DIR"));package.path=engine.."/?.lua;"..engine.."/?/init.lua;"..package.path
local Data=require("src.core.Data");Data:load();assert(Data.pokemon.CHARMANDER and Data.items and Data.tilesets.CAVERN,"engine data loaded")
local Serializer=require("src.core.SaveSerializer");local makeArchive=assert(loadfile("legacy_archive.lua"))();local makePackages=assert(loadfile("hevo_packages.lua"))();local makeAdapter=assert(loadfile("legacy_dungeon_adapter.lua"))()
local files,fail={},false;local fs={getInfo=function(p)return files[p]and{}or nil end,read=function(p)return files[p] end,write=function(p,v)if fail then return false,"injected" end;files[p]=v;return true end,remove=function(p)files[p]=nil;return true end,createDirectory=function()return true end}
local archive=makeArchive({fs=fs,serializer=Serializer,edition="red",directory="test/dungeon",modId="kanto_ascendant",isBadge=function()return false end})
local serial=100
local function newRun(avatar,source)
  serial=serial+1;if source then source=Serializer.decode(Serializer.encode(source)) else source={version="red",player={id=serial},party={},boxes={{}},inventory={},pcItems={},money=0,hallOfFame={{}},modData={}} end
  assert(archive.beginJourney(source,{runRules=archive.safeRunRulesSnapshot(source)}));local save={version="red",player={id=source.player.id},party={},boxes={{}},inventory={},pcItems={},money=0,hallOfFame={{}},modData={}}
  assert(archive.seedNewSave(save));assert(archive.importHandoff(save));assert(archive.markRunStarted(save));assert(archive.finishHandoff(save));assert(archive.setAvatar(save,avatar));return save
end
local function game(save) return {save=save,data=Data,writes=0,writeSave=function(self)self.writes=self.writes+1;return true end} end
local function same(a,b,seen) if type(a)~=type(b) then return false end;if type(a)~="table" then return a==b end;seen=seen or {};if seen[a]==b then return true end;seen[a]=b;for k,v in pairs(a) do if not same(v,b[k],seen) then return false end end;for k in pairs(b) do if a[k]==nil then return false end end;return true end
local journey={activeCharacter=function(save)local active=archive.activeCharacter(save);if active then return active end;local bucket=save.modData and save.modData.kanto_ascendant;local chars=bucket and bucket.extended_characters;return chars and chars.player_character end,advancePath=archive.advancePath,completeHevoPath=archive.completeHevoPath,syncHevoPersistent=archive.syncHevoPersistent,hevoDoorQuestReady=archive.hevoDoorQuestReady,consumeHevoDoorQuest=archive.consumeHevoDoorQuest}
local packages=makePackages({id="kanto_ascendant",exports={}},{enabled=false,journey=journey,modId="kanto_ascendant"})
local mega={}
function mega.hasStone(stone,g)local b=g.save.modData.kanto_ascendant;local s=b.mega_evolution;return s and s.stones and s.stones[stone]==true or false end
function mega.grantStone(stone,g)local b=g.save.modData.kanto_ascendant;b.mega_evolution=type(b.mega_evolution)=="table"and b.mega_evolution or{stones={}};b.mega_evolution.stones=type(b.mega_evolution.stones)=="table"and b.mega_evolution.stones or{};if b.mega_evolution.stones[stone]then return false end;b.mega_evolution.stones[stone]=true;return true end
local adapter=makeAdapter({archive=archive,journey=journey,packages=packages,megaEvolution=mega,modId="kanto_ascendant"})
local red=game(newRun("RED"));packages.install(red)
assert(not adapter.recoverPackages(red,"RED",{"electirizer"}),"recovery cannot leak another character's package")
local recovered,recoveryErr=adapter.recoverPackages(red,"RED",{"protector"});assert(recovered,"validated recovery failed: "..tostring(recoveryErr));assert(adapter.persistent(red.save).packageUnlocks.protector and not adapter.persistent(red.save).packageUnlocks.magmarizer,"named recovery seam may restore a validated subset")
assert(not adapter.finalize(red,{character="RED",evolutionUnlocks={"RHYPERIOR"}}),"production payload cannot provide an evolution subset")
local ok,redResult=adapter.finalize(red,{character="RED",questionIds={"RED_Q"},rivalWitness=true});assert(ok and #redResult.packages==5 and redResult.targetCount==5)
local p=adapter.persistent(red.save);assert(p.meta.RED and not p.permanentItems.BLAZIKENITE and not p.secretUnlocks.RED and p.permanentItems.LEGACY_STARTER_TORCHIC and p.dex.TORCHIC and adapter.run(red.save).rivalWitness.RED,"completion must not grant the optional Mega stone")
assert(p.packageUnlocks.protector and p.packageUnlocks.rollout_knowledge and p.evolutionUnlocks.RHYPERIOR and p.evolutionUnlocks.LICKILICKY and not p.packageUnlocks.electirizer,"RED receives exactly the RED package family")
assert(red.save.inventory.PROTECTOR==1 and red.save.inventory.MAGMARIZER==1 and red.save.inventory.RAZOR_FANG==1,"RED item packages grant exactly one first item")
assert(archive.profile().completedPaths.red,"red seal archived")
assert(adapter.reenter(red.save,"RED"),"own dungeon can be re-entered")
assert(not adapter.claimSecret(red,{character="BLUE",stone="SWAMPERTITE",secret="KA_HEVO_BLUE_SWAMPERTITE_CACHE"}),"cross-character secret rejected")
local secretOk,secretResult=adapter.claimSecret(red,{character="RED",stone="BLAZIKENITE",secret="KA_RED_BLAZIKENITE_SECRET"});assert(secretOk and secretResult.stone=="BLAZIKENITE" and adapter.hasSecret(red.save,"RED") and mega.hasStone("BLAZIKENITE",red),"explicit RED secret atomically grants and synchronizes BLAZIKENITE")
local duplicateSecret,duplicateReason=adapter.claimSecret(red,{character="RED",stone="BLAZIKENITE",secret="KA_RED_BLAZIKENITE_SECRET"});assert(not duplicateSecret and duplicateReason=="claimed","secret grant is idempotent")
assert(not adapter.finalize(red,{character="RED"}),"a seal is only awarded once per run")
local reloaded=Serializer.decode(Serializer.encode(red.save));local blue=game(newRun("BLUE",reloaded));packages.install(blue);assert(adapter.install(blue));local bp=adapter.persistent(blue.save);assert(bp.secretUnlocks.RED and bp.permanentItems.BLAZIKENITE and mega.hasStone("BLAZIKENITE",blue) and bp.evolutionUnlocks.RHYPERIOR and not bp.permanentItems.SWAMPERTITE and not bp.secretUnlocks.BLUE and not bp.packageUnlocks.electirizer,"RED secret and packages survive Save/Load and NG+ without BLUE leakage")
local bok,bresult=adapter.finalize(blue,{character="BLUE",questionIds={"BLUE_Q"}});assert(bok and #bresult.packages==5 and bresult.targetCount==5 and adapter.persistent(blue.save).packageUnlocks.magnetic_field)
assert(blue.save.inventory.ELECTIRIZER==1 and blue.save.inventory.RAZOR_CLAW==1 and blue.save.inventory.DUBIOUS_DISC==1,"BLUE receives one of each item-package first grant")
local green=game(newRun("GREEN",Serializer.decode(Serializer.encode(blue.save))));packages.install(green);local gok,gresult=adapter.finalize(green,{character="GREEN",questionIds={"GREEN_Q"}});assert(gok and #gresult.packages==5 and gresult.targetCount==7 and adapter.persistent(green.save).evolutionUnlocks.HONCHKROW);assert(not adapter.persistent(green.save).permanentItems.SWAMPERTITE and not adapter.persistent(green.save).permanentItems.SCEPTILITE,"BLUE/GREEN completion does not auto-grant secret stones");assert(green.save.inventory.SHINY_STONE==1 and green.save.inventory.DUSK_STONE==1,"GREEN receives one of each item-package first grant");assert(adapter.archiveReady(green.save));assert(adapter.consumeDoorArchive(green.save));assert(not adapter.consumeDoorArchive(green.save),"door archive is run-local once")
local wrong=game(green.save);assert(not adapter.finalize(wrong,{character="BLUE"}),"cross-character reward rejected")
local original={version="red",player={id=999},hallOfFame={},party={},boxes={{}},inventory={},bagOrder={},pcItems={},money=0,flags={},modData={kanto_ascendant={extended_characters={player_character="RED"}}}};local originalGame=game(original);packages.install(originalGame);local originalOk,originalResult=adapter.finalize(originalGame,{character="RED"});assert(originalOk and originalResult.targetCount==5 and adapter.persistent(original).packageUnlocks.protector,"the RED dungeon is completable in the original pre-Hall run")
local legacyAbsent={version="red",player={id=1000},hallOfFame={},party={},boxes={{}},inventory={},bagOrder={},pcItems={},money=0,flags={},modData={kanto_ascendant={}}};assert(adapter.character(legacyAbsent)=="RED" and adapter.canFinalize(legacyAbsent,"RED"),"exact identity-record absence did not migrate to legacy RED")
local future={hallOfFame={},inventory={},flags={},modData={kanto_ascendant={extended_characters={player_character="FUTURE"}}}};local normalizedAdapter=makeAdapter({archive=archive,journey={activeCharacter=function()return nil end},characters={getState=function()return{player_character="RED"}end},packages=packages,megaEvolution=mega,modId="kanto_ascendant"});assert(normalizedAdapter.character(future)==nil and not normalizedAdapter.finalize(game(future),{}),"future raw identity inherited normalized RED reward authority")
local writeFail=game(newRun("RED",green.save));packages.install(writeFail);local writeBefore=Serializer.decode(Serializer.encode(writeFail.save.modData.kanto_ascendant));writeFail.writeSave=function(self)self.writes=self.writes+1;return self.writes>1 end;assert(not adapter.finalize(writeFail,{character="RED"}));assert(same(writeFail.save.modData.kanto_ascendant,writeBefore),"game write failure rolls back save mutation")
local secretWriteFail=game(newRun("RED",writeFail.save));packages.install(secretWriteFail);assert(adapter.finalize(secretWriteFail,{character="RED"}));local swp=adapter.persistent(secretWriteFail.save);swp.secretUnlocks.RED=nil;swp.permanentItems.BLAZIKENITE=nil;secretWriteFail.save.modData.kanto_ascendant.mega_evolution=nil;secretWriteFail.writes=0;local secretBefore=Serializer.decode(Serializer.encode(secretWriteFail.save.modData.kanto_ascendant));secretWriteFail.writeSave=function(self)self.writes=self.writes+1;return self.writes>1 end;assert(not adapter.claimSecret(secretWriteFail,{character="RED",stone="BLAZIKENITE",secret="KA_RED_BLAZIKENITE_SECRET"}));assert(same(secretWriteFail.save.modData.kanto_ascendant,secretBefore),"secret game-write failure rolls back entitlement and Mega runtime")
local rollback=game(newRun("RED",secretWriteFail.save));packages.install(rollback);local before=Serializer.decode(Serializer.encode(rollback.save.modData.kanto_ascendant));fail=true;assert(not adapter.finalize(rollback,{}));fail=false;assert(same(rollback.save.modData.kanto_ascendant,before),"archive write failure rolls back save mutation")
local secretRollback=game(newRun("RED",rollback.save));packages.install(secretRollback);assert(adapter.finalize(secretRollback,{character="RED"}));local srp=adapter.persistent(secretRollback.save);srp.secretUnlocks.RED=nil;srp.permanentItems.BLAZIKENITE=nil;secretRollback.save.modData.kanto_ascendant.mega_evolution=nil;local secretArchiveBefore=Serializer.decode(Serializer.encode(secretRollback.save.modData.kanto_ascendant));fail=true;assert(not adapter.claimSecret(secretRollback,{character="RED",stone="BLAZIKENITE",secret="KA_RED_BLAZIKENITE_SECRET"}));fail=false;assert(same(secretRollback.save.modData.kanto_ascendant,secretArchiveBefore),"secret archive failure rolls back entitlement and Mega runtime")
local migrated=game(newRun("RED",secretRollback.save));packages.install(migrated);migrated.save.modData.kanto_ascendant.hevo_persistent={meta={},evolutionUnlocks={},permanentItems={}};assert(adapter.finalize(migrated,{character="RED",questionIds={"MIGRATED_Q"}}));local mp=adapter.persistent(migrated.save);assert(mp.meta.RED and mp.questionIds.MIGRATED_Q and mp.dex.TORCHIC and mp.packageUnlocks.protector,"old HEVO save gains the package schema")
local pendingSave={version="red",player={id=2001},hallOfFame={},party={},boxes={{}},inventory={},bagOrder={},pcItems={},money=0,flags={},modData={kanto_ascendant={extended_characters={player_character="RED"}}}};local pendingGame=game(pendingSave);packages.install(pendingGame);local pendingAdapter=makeAdapter({archive=archive,journey=journey,packages=packages,modId="kanto_ascendant"});local pendingOk,pendingResult=pendingAdapter.claimSecret(pendingGame,{character="RED",stone="BLAZIKENITE",secret="KA_RED_BLAZIKENITE_SECRET"});assert(pendingOk and pendingResult.pending and pendingAdapter.hasSecret(pendingSave,"RED") and not pendingSave.modData.kanto_ascendant.mega_evolution,"an unavailable Mega runtime stores a durable pending entitlement");assert(adapter.install(pendingGame) and mega.hasStone("BLAZIKENITE",pendingGame),"later Mega installation reconciles the pending entitlement")
print("legacy_dungeon_adapter_test: PASS")
