#!/usr/bin/env python3
"""Build the canonical Pokemon Crystal level-up table used by Ascendant.

The source is pret/pokecrystal's symbolic data.  The generated Lua file only
contains species ids, levels and move ids; no ROM bytes or graphics.
"""

from __future__ import annotations

import argparse
import re
import subprocess
from pathlib import Path


SPECIES_ALIASES = {
    "FARFETCH_D": "FARFETCHD",
    "MR__MIME": "MR_MIME",
}


def species_order(constants: Path) -> list[str]:
    result: list[str] = []
    for line in constants.read_text(encoding="utf-8").splitlines():
        match = re.match(r"\s*const\s+([A-Z0-9_]+)\s*;", line)
        if not match:
            continue
        species = match.group(1)
        if species == "EGG":
            break
        result.append(SPECIES_ALIASES.get(species, species))
        if species == "CELEBI":
            break
    if len(result) != 251:
        raise ValueError(f"expected 251 species constants, found {len(result)}")
    return result


def pointer_labels(pointers: Path) -> list[str]:
    labels = []
    for line in pointers.read_text(encoding="utf-8").splitlines():
        match = re.match(r"\s*dw\s+([A-Za-z0-9]+EvosAttacks)\s*$", line)
        if match:
            labels.append(match.group(1))
    if len(labels) != 251:
        raise ValueError(f"expected 251 learnset pointers, found {len(labels)}")
    return labels


def parse_blocks(source: Path) -> dict[str, list[tuple[int, str]]]:
    blocks: dict[str, list[tuple[int, str]]] = {}
    current: str | None = None
    after_evolutions = False
    for raw in source.read_text(encoding="utf-8").splitlines():
        label = re.match(r"^([A-Za-z0-9]+EvosAttacks):\s*$", raw)
        if label:
            current = label.group(1)
            blocks[current] = []
            after_evolutions = False
            continue
        if current is None:
            continue
        if re.match(r"\s*db\s+0(?:\s*;.*)?$", raw):
            if after_evolutions:
                current = None
            else:
                after_evolutions = True
            continue
        if not after_evolutions:
            continue
        move = re.match(r"\s*db\s+(\d+)\s*,\s*([A-Z0-9_]+)\s*(?:;.*)?$", raw)
        if move:
            blocks[current].append((int(move.group(1)), move.group(2)))
    return blocks


def source_revision(root: Path) -> str:
    try:
        return subprocess.check_output(
            ["git", "-C", str(root), "rev-parse", "HEAD"], text=True
        ).strip()
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def render(root: Path) -> str:
    constants = root / "constants/pokemon_constants.asm"
    pointers = root / "data/pokemon/evos_attacks_pointers.asm"
    attacks = root / "data/pokemon/evos_attacks.asm"
    species = species_order(constants)
    labels = pointer_labels(pointers)
    blocks = parse_blocks(attacks)

    revision = source_revision(root)
    lines = [
        "-- Generated by tools/build_crystal_learnsets.py. DO NOT EDIT.",
        "-- Source: pret/pokecrystal data/pokemon/evos_attacks.asm",
        f"-- Source revision: {revision}",
        "-- This table describes Crystal level-up facts; runtime compatibility",
        "-- decides which move ids can be activated by Gen1 Recomp.",
        "return {",
        "  _meta = {",
        '    source = "pret/pokecrystal:data/pokemon/evos_attacks.asm",',
        f'    revision = "{revision}",',
        "    speciesCount = 251,",
        "  },",
    ]
    for dex, (species_id, label) in enumerate(zip(species, labels), 1):
        rows = blocks.get(label)
        if rows is None:
            raise ValueError(f"missing learnset block {label}")
        lines.append(f"  {species_id} = {{ -- #{dex:03d}")
        for level, move in rows:
            lines.append(f'    {{ level = {level}, move = "{move}" }},')
        lines.append("  },")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--pokecrystal", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.write_text(render(args.pokecrystal.resolve()), encoding="utf-8")


if __name__ == "__main__":
    main()
