#!/usr/bin/env python3
"""Build the offline #001-251 Apricorn Ball weight table.

The inputs are the already bundled local pokecrystal source tree.  Each
Gen-II Dex entry has the authoritative decipound `dw height, weight` fields;
the runtime table stores kilogram values to avoid treating engineless Kanto
data as a neutral Heavy Ball case.  No network access is used.
"""

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[3]
SOURCE = ROOT / ".downloads" / "pokecrystal" / "data" / "pokemon"
BASE = SOURCE / "base_stats"
ENTRIES = SOURCE / "dex_entries"
OUT = Path(__file__).resolve().parents[1] / "apricorn_ball_data.lua"

species_re = re.compile(r"^\s*db\s+\w+\s*;\s*(\d{3})\s*$", re.M)
weight_re = re.compile(r"^\s*dw\s+(\d+),\s*(\d+)\s*;\s*height, weight\s*$", re.M)

rows = {}
for stat in BASE.glob("*.asm"):
    match = species_re.search(stat.read_text())
    if not match:
        continue
    dex = int(match.group(1))
    entry = ENTRIES / stat.name
    value = weight_re.search(entry.read_text()) if entry.exists() else None
    if value:
        # pokecrystal stores tenths of a pound; this is stored as kg.
        rows[dex] = int(value.group(2)) / 10 * 0.45359237

missing = [dex for dex in range(1, 252) if dex not in rows]
if missing:
    raise SystemExit(f"missing Pokecrystal weights: {missing}")

lines = [
    "-- Generated by tools/build_apricorn_ball_data.py; do not hand-edit.",
    "-- Source: local .downloads/pokecrystal/data/pokemon/dex_entries/*.asm",
    "-- Pokecrystal stores decipounds; values below are kilograms.",
    "return { weightKgByDex = {",
]
for dex in range(1, 252):
    # Six decimals preserves the source conversion while remaining readable.
    lines.append(f"  [{dex}] = {rows[dex]:.6f},")
lines.extend(["} }", ""])
OUT.write_text("\n".join(lines))
