#!/usr/bin/env python3
"""Build the narrow HEVO #261-279 catalogue from pret/pokeheartgold.

The source repository keeps HGSS level-up tables in wotbl.narc.  This tool
extracts only the nineteen Package-3 species and emits deterministic Lua.
Runtime registration still filters every row against Gen1 Recomp's actual
move registry; this file never creates move implementations.
"""

from __future__ import annotations

import argparse
import json
import re
import struct
from pathlib import Path


TARGETS = [
    (261, 424, "AMBIPOM", "AMBIDIFFEL", "LONG TAIL", 1.2, 20.3),
    (262, 429, "MISMAGIUS", "TRAUNMAGIL", "MAGICAL", 0.9, 4.4),
    (263, 430, "HONCHKROW", "KRAMSHEF", "BIG BOSS", 0.9, 27.3),
    (264, 461, "WEAVILE", "SNIBUNNA", "SHARP CLAW", 1.1, 34.0),
    (265, 462, "MAGNEZONE", "MAGNEZONE", "MAGNET AREA", 1.2, 180.0),
    (266, 463, "LICKILICKY", "SCHLURPLEK", "LICKING", 1.7, 140.0),
    (267, 464, "RHYPERIOR", "RIHORNIOR", "DRILL", 2.4, 282.8),
    (268, 465, "TANGROWTH", "TANGOLOSS", "VINE", 2.0, 128.6),
    (269, 466, "ELECTIVIRE", "ELEVOLTEK", "THUNDERBOLT", 1.8, 138.6),
    (270, 467, "MAGMORTAR", "MAGBRANT", "BLAST", 1.6, 68.0),
    (271, 468, "TOGEKISS", "TOGEKISS", "JUBILEE", 1.5, 38.0),
    (272, 469, "YANMEGA", "YANMEGA", "OGRE DARNER", 1.9, 51.5),
    (273, 470, "LEAFEON", "FOLIPURBA", "VERDANT", 1.0, 25.5),
    (274, 471, "GLACEON", "GLAZIOLA", "FRESH SNOW", 0.8, 25.9),
    (275, 472, "GLISCOR", "SKORGRO", "FANG SCORP", 2.0, 42.5),
    (276, 473, "MAMOSWINE", "MAMUTEL", "TWIN TUSK", 2.5, 291.0),
    (277, 474, "PORYGON_Z", "PORYGON-Z", "VIRTUAL", 0.9, 34.0),
    (278, 298, "AZURILL", "AZURILL", "POLKA DOT", 0.2, 2.0),
    (279, 360, "WYNAUT", "ISSO", "BRIGHT", 0.6, 14.0),
]

MOVE_ALIASES = {
    "ANCIENT_POWER": "ANCIENTPOWER",
    "CONVERSION_2": "CONVERSION2",
    "DOUBLE_SLAP": "DOUBLESLAP",
    "EXTREME_SPEED": "EXTREMESPEED",
    "POISON_POWDER": "POISONPOWDER",
    "SMOKE_SCREEN": "SMOKESCREEN",
    "SONIC_BOOM": "SONICBOOM",
    "SOLAR_BEAM": "SOLARBEAM",
    "THUNDER_SHOCK": "THUNDERSHOCK",
    "VICE_GRIP": "VICEGRIP",
}


def narc_members(blob: bytes) -> list[bytes]:
    if blob[:4] != b"NARC":
        raise ValueError("wotbl source is not a NARC archive")
    section_count = struct.unpack_from("<H", blob, 14)[0]
    pos = 16
    sections = []
    for _ in range(section_count):
        size = struct.unpack_from("<I", blob, pos + 4)[0]
        sections.append((blob[pos : pos + 4], pos, size))
        pos += size
    _, fat_pos, _ = sections[0]
    count = struct.unpack_from("<H", blob, fat_pos + 8)[0]
    entries = [
        struct.unpack_from("<II", blob, fat_pos + 12 + index * 8)
        for index in range(count)
    ]
    magic, image_pos, _ = sections[-1]
    if magic != b"GMIF":
        raise ValueError("wotbl NARC has no GMIF section")
    base = image_pos + 8
    return [blob[base + start : base + end] for start, end in entries]


def move_constants(path: Path) -> dict[int, str]:
    result = {}
    for line in path.read_text().splitlines():
        if line.startswith("#define NUM_MOVES"):
            break
        match = re.fullmatch(r"#define MOVE_([A-Z0-9_]+)\s+(\d+)", line)
        if match:
            result[int(match.group(2))] = match.group(1)
    return result


def learnset(member: bytes, moves: dict[int, str]) -> list[tuple[int, str]]:
    result = []
    for offset in range(0, len(member), 2):
        packed = struct.unpack_from("<H", member, offset)[0]
        if packed == 0xFFFF:
            break
        move = moves[packed & 0x1FF]
        result.append((packed >> 9, MOVE_ALIASES.get(move, move)))
    return result


def lua_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def render(root: Path) -> str:
    personal = json.loads(
        (root / "files/poketool/personal/personal.json").read_text()
    )["baseStats"]
    members = narc_members(
        (root / "files/poketool/personal/wotbl.narc").read_bytes()
    )
    moves = move_constants(root / "include/constants/moves.h")
    revision = "unknown"
    head = root / ".git/refs/heads/master"
    if head.exists():
        revision = head.read_text().strip()
    else:
        packed = root / ".git/packed-refs"
        if packed.exists():
            for line in packed.read_text().splitlines():
                if line.endswith(" refs/heads/master"):
                    revision = line.split()[0]
                    break

    out = [
        "-- Generated by tools/build_hevo_species_data.py. DO NOT EDIT.",
        "return {",
        "  _meta = {",
        '    source = "pret/pokeheartgold:wotbl.narc+personal.json",',
        f"    revision = {lua_string(revision)},",
        "    speciesCount = 19, dexFirst = 261, dexLast = 279,",
        "  },",
    ]
    for dex, source_dex, species, german, kind, height, weight in TARGETS:
        row = personal[source_dex]
        types = []
        for value in row["types"]:
            value = value.removeprefix("TYPE_")
            if value == "PSYCHIC":
                value = "PSYCHIC_TYPE"
            if value not in types:
                types.append(value)
        rows = learnset(members[source_dex], moves)
        level_one = []
        scheduled = []
        for level, move in rows:
            if level == 1:
                if move not in level_one:
                    level_one.append(move)
            else:
                scheduled.append((level, move))
        out.extend([
            f"  {species} = {{",
            f"    dex = {dex}, sourceDex = {source_dex},",
            f"    name = {lua_string(species.replace('_', '-'))}, de = {lua_string(german)},",
            f"    kind = {lua_string(kind)},",
            "    types = { " + ", ".join(lua_string(v) for v in types) + " },",
            "    stats = { hp = %d, attack = %d, defense = %d, speed = %d, special = %d },"
            % (row["hp"], row["atk"], row["def"], row["speed"], row["spatk"]),
            f"    catchRate = {row['catchRate']}, baseExp = {row['expYield']},",
            f"    growthRate = {lua_string(row['growthRate'])},",
            f"    heightM = {height:.1f}, weightKg = {weight:.1f},",
            "    level1Moves = { " + ", ".join(lua_string(v) for v in level_one) + " },",
            "    learnset = {",
        ])
        for level, move in scheduled:
            out.append(f"      {{ level = {level}, move = {lua_string(move)} }},")
        out.extend(["    },", "  },"])
    out.append("}")
    return "\n".join(out) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--pokeheartgold", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    args.output.write_text(render(args.pokeheartgold))


if __name__ == "__main__":
    main()
