#!/usr/bin/env python3
"""Regenerate the embedded Kanto/Johto breeding table.

The shipped mod reads only breeding_data.lua and never needs network access.
This maintainer tool records PokéAPI's species gender rate, egg groups and
hatch counter for National Pokédex entries 1-251.
"""

import concurrent.futures
import json
from pathlib import Path
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "breeding_data.lua"
URL = "https://pokeapi.co/api/v2/pokemon-species/{}"

# Ascendant's private catalogue slots are not their National-Dex source ids,
# so they cannot be fetched with URL.format(slot). Keep the reviewed projection
# beside the generator to make regeneration deterministic.
EXTENSIONS = {
    252: (1, 20, ["monster", "dragon"]),
    253: (1, 20, ["monster", "dragon"]),
    254: (1, 20, ["monster", "dragon"]),
    255: (1, 20, ["ground"]),
    256: (1, 20, ["ground"]),
    257: (1, 20, ["ground"]),
    258: (1, 20, ["monster", "water1"]),
    259: (1, 20, ["monster", "water1"]),
    260: (1, 20, ["monster", "water1"]),
    261: (4, 20, ["ground"]),
    262: (4, 25, ["indeterminate"]),
    263: (4, 20, ["flying"]),
    264: (4, 20, ["ground"]),
    265: (-1, 20, ["mineral"]),
    266: (4, 20, ["monster"]),
    267: (4, 20, ["monster", "ground"]),
    268: (4, 20, ["plant"]),
    269: (2, 25, ["humanshape"]),
    270: (2, 25, ["humanshape"]),
    271: (1, 10, ["flying", "fairy"]),
    272: (4, 20, ["bug"]),
    273: (1, 35, ["ground"]),
    274: (1, 35, ["ground"]),
    275: (4, 20, ["bug"]),
    276: (4, 20, ["ground"]),
    277: (-1, 20, ["mineral"]),
    278: (6, 10, ["no-eggs"]),
    279: (4, 20, ["no-eggs"]),
}


def fetch(dex):
    request = urllib.request.Request(
        URL.format(dex), headers={"User-Agent": "KantoAscendantDataBuilder/1.0"})
    with urllib.request.urlopen(request, timeout=30) as response:
        data = json.load(response)
    return (
        dex,
        data["gender_rate"],
        data["hatch_counter"],
        [group["name"] for group in data["egg_groups"]],
    )


def main():
    with concurrent.futures.ThreadPoolExecutor(max_workers=24) as executor:
        rows = sorted(executor.map(fetch, range(1, 252)))
    rows.extend((dex, gender, hatch, groups)
                for dex, (gender, hatch, groups) in EXTENSIONS.items())
    lines = [
        "-- Generated by tools/build_breeding_data.py; runtime is offline.",
        "-- #252-279 are Ascendant's authored private-Dex extension.",
        "return {",
    ]
    for dex, gender, hatch, groups in rows:
        encoded = ", ".join(f'"{group}"' for group in groups)
        lines.append(
            f"  [{dex}] = {{ gender = {gender}, hatch = {hatch}, "
            f"groups = {{ {encoded} }} }},")
    lines.append("}")
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"generated {len(rows)} breeding records in {OUTPUT.name}")


if __name__ == "__main__":
    main()
