#!/usr/bin/env python3
"""Regenerate the embedded Kanto/Johto breeding table.

The shipped mod reads only breeding_data.lua and never needs network access.
This maintainer tool records PokéAPI's species gender rate, egg groups and
hatch counter for National Pokédex entries 1-251.
"""

import concurrent.futures
import json
from pathlib import Path
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "breeding_data.lua"
URL = "https://pokeapi.co/api/v2/pokemon-species/{}"


def fetch(dex):
    request = urllib.request.Request(
        URL.format(dex), headers={"User-Agent": "KantoAscendantDataBuilder/1.0"})
    with urllib.request.urlopen(request, timeout=30) as response:
        data = json.load(response)
    return (
        dex,
        data["gender_rate"],
        data["hatch_counter"],
        [group["name"] for group in data["egg_groups"]],
    )


def main():
    with concurrent.futures.ThreadPoolExecutor(max_workers=24) as executor:
        rows = sorted(executor.map(fetch, range(1, 252)))
    lines = [
        "-- Generated by tools/build_breeding_data.py; runtime is offline.",
        "return {",
    ]
    for dex, gender, hatch, groups in rows:
        encoded = ", ".join(f'"{group}"' for group in groups)
        lines.append(
            f"  [{dex}] = {{ gender = {gender}, hatch = {hatch}, "
            f"groups = {{ {encoded} }} }},")
    lines.append("}")
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"generated {len(rows)} breeding records in {OUTPUT.name}")


if __name__ == "__main__":
    main()
