-- Package-only connected early-game route for RC65-EARLY-BALANCE.
--
-- This is deliberately geography and input intent only.  It contains no
-- save mutation, event flag, badge grant, teleport or synthetic battle.
-- `tests/drivers/route.lua` executes every row through the live input stack,
-- real overworld scripts and BattleState.  The route ends immediately after
-- Brock's post-battle script has walked the player out of Pewter Gym.

local edition = assert(os.getenv("POKEPORT_VERSION"),
  "POKEPORT_VERSION is required")
assert(edition == "red" or edition == "blue" or edition == "yellow",
  "connected first-badge route supports only Red, Blue and Yellow")

-- Yellow's Oak interception fires at the north connection (y=0); Red and
-- Blue fire one cell earlier (y=1).  Every later waypoint is common.
local palletOakTriggerY = edition == "yellow" and 0 or 1

return {
  { map = "REDS_HOUSE_2F", steps = {
    { op = "goto", x = 3, y = 6 },
    { op = "goto", x = 5, y = 6 },
    { op = "goto", x = 5, y = 1 },
    { op = "goto", x = 7, y = 1 },
  } },
  { map = "REDS_HOUSE_1F", steps = {
    { op = "goto", x = 7, y = 1 },
    { op = "goto", x = 7, y = 6 },
    { op = "goto", x = 3, y = 6 },
    { op = "goto", x = 3, y = 8 },
  } },
  { map = "PALLET_TOWN", steps = {
    { op = "goto", x = 5, y = 6 },
    { op = "goto", x = 10, y = 6 },
    { op = "goto", x = 10, y = palletOakTriggerY },
  } },
  { map = "OAKS_LAB", steps = {
    -- In Red/Blue this selects Squirtle.  At the same table coordinate in
    -- Yellow, the rival snatches Eevee and Oak gives the player Pikachu.
    { op = "goto", x = 5, y = 3 },
    { op = "goto", x = 5, y = 4 },
    { op = "goto", x = 7, y = 4 },
    { op = "talk" },
    { op = "goto", x = 5, y = 4 },
    { op = "goto", x = 5, y = 6 },
    { op = "battle" },
    { op = "goto", x = 5, y = 12 },
  } },
  { map = "PALLET_TOWN", steps = {
    { op = "goto", x = 12, y = 12 },
    { op = "goto", x = 9, y = 12 },
    { op = "goto", x = 9, y = 2 },
    { op = "goto", x = 10, y = 2 },
    { op = "goto", x = 10, y = -1 },
  } },
  { map = "ROUTE_1", steps = {
    { op = "goto", x = 10, y = 35 },
    { op = "goto", x = 10, y = 30 },
    { op = "goto", x = 8, y = 30 },
    { op = "goto", x = 8, y = 24 },
    { op = "goto", x = 12, y = 24 },
    { op = "goto", x = 12, y = 20 },
    { op = "goto", x = 9, y = 20 },
    { op = "goto", x = 9, y = 14 },
    { op = "goto", x = 14, y = 14 },
    { op = "goto", x = 14, y = 2 },
    { op = "goto", x = 10, y = 2 },
    { op = "goto", x = 10, y = -1 },
  } },
  { map = "VIRIDIAN_CITY", steps = {
    { op = "goto", x = 20, y = 35 },
    { op = "goto", x = 20, y = 28 },
    { op = "goto", x = 19, y = 28 },
    { op = "goto", x = 19, y = 20 },
    { op = "goto", x = 29, y = 20 },
    { op = "goto", x = 29, y = 19 },
  } },
  { map = "VIRIDIAN_MART", steps = {
    { op = "goto", x = 2, y = 5 },
    { op = "goto", x = 3, y = 5 },
    { op = "goto", x = 3, y = 8 },
  } },
  { map = "VIRIDIAN_CITY", steps = {
    { op = "goto", x = 29, y = 20 },
    { op = "goto", x = 29, y = 21 },
    { op = "goto", x = 26, y = 21 },
    { op = "goto", x = 26, y = 30 },
    { op = "goto", x = 20, y = 30 },
    { op = "goto", x = 20, y = 36 },
  } },
  { map = "ROUTE_1", steps = {
    { op = "goto", x = 10, y = 0 },
    { op = "goto", x = 10, y = 3 },
    { op = "goto", x = 8, y = 3 },
    { op = "goto", x = 8, y = 18 },
    { op = "goto", x = 9, y = 18 },
    { op = "goto", x = 9, y = 21 },
    { op = "goto", x = 12, y = 21 },
    { op = "goto", x = 12, y = 24 },
    { op = "goto", x = 10, y = 24 },
    { op = "goto", x = 10, y = 36 },
  } },
  { map = "PALLET_TOWN", steps = {
    { op = "goto", x = 10, y = 0 },
    { op = "goto", x = 10, y = 7 },
    { op = "goto", x = 9, y = 7 },
    { op = "goto", x = 9, y = 12 },
    { op = "goto", x = 12, y = 12 },
    { op = "goto", x = 12, y = 11 },
  } },
  { map = "OAKS_LAB", steps = {
    { op = "goto", x = 5, y = 11 },
    { op = "goto", x = 5, y = 3 },
    { op = "goto", x = 4, y = 3 },
    { op = "goto", x = 4, y = 1 },
    { op = "goto", x = 5, y = 1 },
    { op = "talk", face = "down" },
    { op = "goto", x = 4, y = 1 },
    { op = "goto", x = 4, y = 12 },
  } },
  { map = "PALLET_TOWN", steps = {
    { op = "goto", x = 12, y = 12 },
    { op = "goto", x = 9, y = 12 },
    { op = "goto", x = 9, y = 2 },
    { op = "goto", x = 10, y = 2 },
    { op = "goto", x = 10, y = -1 },
  } },
  { map = "ROUTE_1", steps = {
    { op = "goto", x = 10, y = 35 },
    { op = "goto", x = 10, y = 30 },
    { op = "goto", x = 8, y = 30 },
    { op = "goto", x = 8, y = 24 },
    { op = "goto", x = 12, y = 24 },
    { op = "goto", x = 12, y = 20 },
    { op = "goto", x = 9, y = 20 },
    { op = "goto", x = 9, y = 14 },
    { op = "goto", x = 14, y = 14 },
    { op = "goto", x = 14, y = 2 },
    { op = "goto", x = 10, y = 2 },
    { op = "goto", x = 10, y = -1 },
  } },
  { map = "VIRIDIAN_CITY", steps = {
    { op = "goto", x = 20, y = 35 },
    { op = "goto", x = 20, y = 28 },
    { op = "goto", x = 19, y = 28 },
    { op = "goto", x = 19, y = 20 },
    { op = "goto", x = 29, y = 20 },
    { op = "goto", x = 29, y = 19 },
  } },
  { map = "VIRIDIAN_MART", steps = {
    { op = "goto", x = 3, y = 7 },
    { op = "goto", x = 3, y = 5 },
    { op = "goto", x = 2, y = 5 },
    { op = "shop", list = "viridianBalls" },
    { op = "goto", x = 3, y = 5 },
    { op = "goto", x = 3, y = 8 },
  } },
  { map = "VIRIDIAN_CITY", steps = {
    { op = "goto", x = 29, y = 20 },
    { op = "goto", x = 15, y = 20 },
    { op = "goto", x = 15, y = 17 },
    { op = "goto", x = -1, y = 17 },
  } },
  { map = "ROUTE_22", steps = {
    { op = "goto", x = 39, y = 9 },
    { op = "goto", x = 35, y = 9 },
    { op = "goto", x = 35, y = 12 },
    { op = "goto", x = 33, y = 12 },
    { op = "allowCatch", mon = "nidoran" },
    { op = "manual", name = "catchNidoran" },
    -- The Any% source route leaves here.  RC65 acceptance instead walks
    -- onto the real (29,5) ambush coordinate and lets the map script start,
    -- resolve and finish the first Route 22 rival BattleState.
    { op = "goto", x = 33, y = 5 },
    { op = "goto", x = 29, y = 5 },
    { op = "goto", x = 33, y = 5 },
    { op = "goto", x = 37, y = 9 },
    { op = "goto", x = 40, y = 9 },
  } },
  { map = "VIRIDIAN_CITY", steps = {
    { op = "goto", x = 0, y = 17 },
    { op = "goto", x = 16, y = 17 },
    { op = "goto", x = 16, y = 16 },
    { op = "goto", x = 18, y = 16 },
    { op = "goto", x = 18, y = 6 },
    { op = "goto", x = 17, y = 4 },
    { op = "pickup" },
    { op = "goto", x = 17, y = 4 },
    { op = "goto", x = 17, y = 0 },
    { op = "goto", x = 17, y = -1 },
  } },
  { map = "ROUTE_2", steps = {
    { op = "goto", x = 7, y = 71 },
    { op = "goto", x = 7, y = 57 },
    { op = "goto", x = 4, y = 57 },
    { op = "goto", x = 4, y = 52 },
    { op = "goto", x = 10, y = 52 },
    { op = "goto", x = 10, y = 44 },
    { op = "goto", x = 3, y = 44 },
    { op = "goto", x = 3, y = 43 },
  } },
  { map = "VIRIDIAN_FOREST_SOUTH_GATE", steps = {
    { op = "goto", x = 4, y = 7 },
    { op = "goto", x = 4, y = 1 },
    { op = "goto", x = 5, y = 1 },
    { op = "goto", x = 5, y = 0 },
  } },
  { map = "VIRIDIAN_FOREST", steps = {
    { op = "goto", x = 17, y = 47 },
    { op = "goto", x = 17, y = 43 },
    { op = "goto", x = 26, y = 43 },
    { op = "goto", x = 26, y = 34 },
    { op = "goto", x = 25, y = 34 },
    { op = "goto", x = 25, y = 32 },
    { op = "goto", x = 27, y = 32 },
    { op = "goto", x = 27, y = 20 },
    { op = "goto", x = 25, y = 20 },
    { op = "goto", x = 25, y = 12 },
    { op = "pickup" },
    { op = "goto", x = 25, y = 9 },
    { op = "goto", x = 17, y = 9 },
    { op = "goto", x = 17, y = 16 },
    { op = "goto", x = 13, y = 16 },
    { op = "goto", x = 13, y = 3 },
    { op = "goto", x = 7, y = 3 },
    { op = "goto", x = 7, y = 22 },
    { op = "goto", x = 1, y = 22 },
    { op = "goto", x = 1, y = 19 },
    { op = "pickup" },
    { op = "goto", x = 1, y = 18 },
    { op = "battle" },
    { op = "goto", x = 1, y = 16 },
    { op = "heal" },
    { op = "heal", status = true },
    { op = "goto", x = 1, y = 5 },
    { op = "heal", status = true },
    { op = "goto", x = 1, y = -1 },
  } },
  { map = "VIRIDIAN_FOREST_NORTH_GATE", steps = {
    { op = "goto", x = 4, y = 7 },
    { op = "manual", name = "exitForest" },
    { op = "goto", x = 4, y = 1 },
    { op = "goto", x = 5, y = 1 },
    { op = "goto", x = 5, y = 0 },
  } },
  { map = "ROUTE_2", steps = {
    { op = "goto", x = 3, y = 11 },
    { op = "goto", x = 3, y = 8 },
    { op = "goto", x = 8, y = 8 },
    { op = "goto", x = 8, y = -1 },
  } },
  { map = "PEWTER_CITY", steps = {
    { op = "goto", x = 18, y = 35 },
    { op = "goto", x = 18, y = 22 },
    { op = "goto", x = 19, y = 22 },
    { op = "goto", x = 19, y = 13 },
    { op = "goto", x = 10, y = 13 },
    { op = "goto", x = 10, y = 18 },
    { op = "goto", x = 16, y = 18 },
    { op = "goto", x = 16, y = 17 },
  } },
  { map = "PEWTER_GYM", steps = {
    { op = "goto", x = 4, y = 13 },
    { op = "goto", x = 4, y = 8 },
    { op = "goto", x = 1, y = 8 },
    { op = "goto", x = 1, y = 4 },
    { op = "goto", x = 4, y = 4 },
    { op = "goto", x = 4, y = 2 },
    { op = "talk", face = "up" },
    { op = "battle" },
    { op = "goto", x = 4, y = 14 },
  } },
}
