#!/usr/bin/env python3
"""Build bundled Crystal battle animations for all Pokémon #001-251.

The public Crystal Animated Sprites with Shiny Visuals mod stores each
animation as numbered PNG frames plus a Lua duration table. Kanto Ascendant
uses the same deliberately simple format. Its complete bundled pack works
standalone, while an installed external animation mod can still take
ownership of the Kanto species it replaces.

Source GIFs are the Pokémon Crystal normal/shiny animations mirrored by the
PokeAPI sprites repository. Every species is downloaded and validated before
the Lua timing table is replaced.
"""

from __future__ import annotations

import argparse
import io
import tempfile
import urllib.request
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
DEST = ROOT / "assets" / "crystal_animated" / "front"
DATA = ROOT / "crystal_animation_data.lua"
BASE = (
    "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/"
    "versions/generation-ii/crystal/animated"
)
DEX_NUMBERS = range(1, 252)
VARIANTS = {
    "normal": "{dex}.gif",
    "shiny": "shiny/{dex}.gif",
}
CANVAS_SIZES = (40, 48, 56)


def fetch(url: str) -> bytes:
    request = urllib.request.Request(
        url,
        headers={"User-Agent": "kanto-ascendant-crystal-animation-builder/1.0"},
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        body = response.read()
    if not body.startswith((b"GIF87a", b"GIF89a")):
        raise ValueError(f"{url} did not return a GIF")
    return body


def rgba_frames(body: bytes) -> tuple[list[Image.Image], list[int]]:
    gif = Image.open(io.BytesIO(body))
    frames: list[Image.Image] = []
    durations: list[int] = []
    for index in range(getattr(gif, "n_frames", 1)):
        gif.seek(index)
        frame = gif.convert("RGBA")
        frames.append(frame.copy())
        durations.append(max(20, int(gif.info.get("duration") or 100)))
    if not frames:
        raise ValueError("animation has no frames")
    if any(frame.size != frames[0].size for frame in frames):
        raise ValueError("animation frame dimensions are inconsistent")
    return frames, durations


def animation_source(dex: int, variant: str, pattern: str) -> tuple[list[Image.Image], list[int]]:
    if dex == 201:
        # PokeAPI intentionally has no generic animated Unown: Crystal stores
        # its letter forms separately. Keep Ascendant's real form-A Crystal
        # art as a static, timing-compatible exception instead of inventing
        # movement or substituting another species.
        suffix = "_shiny" if variant == "shiny" else ""
        image = Image.open(
            ROOT / "assets" / "crystal" / f"unown_front{suffix}.png"
        ).convert("RGBA")
        return [image], [1000]
    url = f"{BASE}/{pattern.format(dex=dex)}"
    return rgba_frames(fetch(url))


def crop_box(frames: list[Image.Image]) -> tuple[int, int, int, int]:
    width, height = frames[0].size
    bounds = [frame.getchannel("A").getbbox() for frame in frames]
    bounds = [bound for bound in bounds if bound]
    if not bounds:
        raise ValueError("animation is completely transparent")
    min_x = min(bound[0] for bound in bounds)
    min_y = min(bound[1] for bound in bounds)
    max_x = max(bound[2] for bound in bounds)
    max_y = max(bound[3] for bound in bounds)
    visible_w, visible_h = max_x - min_x, max_y - min_y
    canvas = next(
        (
            size
            for size in CANVAS_SIZES
            if visible_w <= size and visible_h <= size
        ),
        max(width, height),
    )
    canvas = min(canvas, width, height)

    # Crystal centers front sprites horizontally and rests them on the bottom
    # of a 5x5, 6x6 or 7x7 tile canvas. Keep one crop for every frame so the
    # animation cannot wobble when its visible bounds change.
    left = (width - canvas) // 2
    top = height - canvas
    if min_x < left:
        left = min_x
    if max_x > left + canvas:
        left = max_x - canvas
    if min_y < top:
        top = min_y
    if max_y > top + canvas:
        top = max_y - canvas
    left = max(0, min(width - canvas, left))
    top = max(0, min(height - canvas, top))
    return left, top, left + canvas, top + canvas


def write_png(frame: Image.Image, target: Path) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        dir=target.parent, prefix=".frame-", suffix=".png", delete=False
    ) as handle:
        temp = Path(handle.name)
    try:
        frame.save(temp, format="PNG", optimize=True)
        temp.replace(target)
    finally:
        temp.unlink(missing_ok=True)


def lua_table(animation_data: dict[str, dict[int, list[int]]]) -> str:
    lines = [
        "-- Generated by tools/install_crystal_animations.py.",
        "-- Frame durations are milliseconds from the source Crystal GIFs.",
        "return {",
    ]
    for variant in ("normal", "shiny"):
        lines.append(f"  {variant} = {{")
        for dex in DEX_NUMBERS:
            durations = ", ".join(str(value) for value in animation_data[variant][dex])
            lines.append(f'    ["{dex}"] = {{ {durations} }},')
        lines.append("  },")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Build normal/shiny Crystal animation frames for #001-251."
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="download and replace already generated frame directories",
    )
    args = parser.parse_args()

    animation_data: dict[str, dict[int, list[int]]] = {
        "normal": {},
        "shiny": {},
    }
    for variant, pattern in VARIANTS.items():
        for dex in DEX_NUMBERS:
            target_dir = DEST / variant / str(dex)
            marker = target_dir / "001.png"
            if marker.exists() and not args.force:
                raise RuntimeError(
                    f"{marker.relative_to(ROOT)} already exists; use --force "
                    "to rebuild the complete timing-safe set"
                )
            if args.force and target_dir.exists():
                for old_frame in target_dir.glob("*.png"):
                    old_frame.unlink()
            frames, durations = animation_source(dex, variant, pattern)
            box = crop_box(frames)
            for index, frame in enumerate(frames, 1):
                write_png(frame.crop(box), target_dir / f"{index:03d}.png")
            animation_data[variant][dex] = durations
            print(
                f"{variant:6} #{dex}: {len(frames):2} frames, "
                f"{box[2] - box[0]}x{box[3] - box[1]}"
            )

    body = lua_table(animation_data)
    with tempfile.NamedTemporaryFile(
        dir=ROOT, prefix=".crystal-animation-", suffix=".lua", delete=False
    ) as handle:
        temp_data = Path(handle.name)
        handle.write(body.encode("utf-8"))
    temp_data.replace(DATA)
    print("installed 502 Crystal animations and crystal_animation_data.lua")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
