#!/usr/bin/env python3
"""Build clean Mega Charizard X battle art from BLaDoM's animation.

The source animation presents a hand-separated Gen-V-style front and back
sprite on a three-times pixel canvas. This tool extracts those pixels instead
of trying to reduce modern artwork automatically:

- 56x56 transparent battle canvases matching Gen1 Recomp's Crystal slots
- recognizable normal and derived shiny palettes
- nearest-neighbour pixels without antialiasing
- a reduced 11-fps front loop and static player backs

Source post and author-provided animation:
https://www.reddit.com/r/pokemon/comments/7phgbg/
https://i.imgur.com/CyUFlo5.gif
"""

from __future__ import annotations

import io
import tempfile
import urllib.request
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
STATIC_DEST = ROOT / "assets" / "mega"
ANIM_DEST = ROOT / "assets" / "mega_animated" / "mega_charizard_x"
DATA_DEST = ROOT / "mega_animation_data.lua"
SOURCE = "https://i.imgur.com/CyUFlo5.gif"

CANVAS = 56
FRAME_STEP = 3
BACKGROUND = (76, 76, 76)
FRONT_BOX = (482, 40, 778, 332)
BACK_BOX = (45, 45, 367, 332)

# BLaDoM's source contains a compact 15-color pixel palette. Shiny art keeps
# every authored shade boundary while remapping the charcoal body toward
# green and the blue fire/accent ramp toward red-gold.
SHINY_MAP = {
    (16, 16, 16): (8, 16, 13),
    (38, 38, 38): (22, 58, 43),
    (77, 77, 77): (43, 101, 70),
    (115, 115, 115): (72, 148, 99),
    (191, 191, 191): (194, 202, 171),
    (248, 248, 248): (248, 248, 232),
    (41, 71, 102): (91, 44, 42),
    (61, 107, 153): (145, 66, 53),
    (99, 144, 166): (190, 111, 67),
    (138, 199, 229): (231, 166, 78),
    (41, 150, 204): (201, 52, 45),
    (115, 191, 229): (235, 95, 52),
    (170, 218, 242): (255, 184, 81),
    (69, 149, 229): (238, 89, 48),
    (217, 33, 33): (222, 36, 36),
}


def fetch(url: str) -> bytes:
    request = urllib.request.Request(
        url,
        headers={"User-Agent": "kanto-ascendant-mega-sprite-builder/2.0"},
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        body = response.read()
    if not body.startswith((b"GIF87a", b"GIF89a")):
        raise ValueError(f"{url} did not return a GIF")
    return body


def gif_frames(body: bytes) -> tuple[list[Image.Image], list[int]]:
    gif = Image.open(io.BytesIO(body))
    if gif.size != (804, 364):
        raise ValueError(f"unexpected source canvas {gif.size}")
    frames, durations = [], []
    for index in range(gif.n_frames):
        gif.seek(index)
        frames.append(gif.convert("RGBA").copy())
        durations.append(max(20, int(gif.info.get("duration") or 30)))
    return frames, durations


def transparent_crop(frame: Image.Image, box: tuple[int, int, int, int]):
    cropped = frame.crop(box)
    pixels = []
    for red, green, blue, _alpha in cropped.getdata():
        if (red, green, blue) == BACKGROUND:
            pixels.append((0, 0, 0, 0))
        else:
            pixels.append((red, green, blue, 255))
    cropped.putdata(pixels)
    return cropped.resize((CANVAS, CANVAS), Image.Resampling.NEAREST)


def shiny_frame(image: Image.Image) -> Image.Image:
    pixels = []
    for red, green, blue, alpha in image.getdata():
        if not alpha:
            pixels.append((0, 0, 0, 0))
            continue
        pixels.append((*SHINY_MAP.get((red, green, blue), (red, green, blue)), 255))
    output = Image.new("RGBA", image.size)
    output.putdata(pixels)
    return output


def sampled_fronts(
    frames: list[Image.Image],
    durations: list[int],
) -> tuple[list[Image.Image], list[int]]:
    output, output_durations = [], []
    for start in range(0, len(frames), FRAME_STEP):
        converted = transparent_crop(frames[start], FRONT_BOX)
        duration = sum(durations[start : start + FRAME_STEP])
        if output and converted.tobytes() == output[-1].tobytes():
            output_durations[-1] += duration
        else:
            output.append(converted)
            output_durations.append(duration)
    return output, output_durations


def write_png(image: Image.Image, target: Path) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        dir=target.parent, prefix=".mega-frame-", suffix=".png", delete=False
    ) as handle:
        temp = Path(handle.name)
    try:
        image.save(temp, format="PNG", optimize=True)
        temp.replace(target)
    finally:
        temp.unlink(missing_ok=True)


def write_data(timings: dict[str, list[int]]) -> None:
    lines = [
        "-- Generated by tools/install_mega_crystal_animations.py.",
        "-- Durations are milliseconds after source-frame reduction.",
        "return {",
        '  ["CHARIZARD_X"] = {',
    ]
    for variant in ("normal", "shiny"):
        duration = ", ".join(str(value) for value in timings[variant])
        lines.append(f"    {variant} = {{ {duration} }},")
    lines.extend(("  },", "}", ""))
    DATA_DEST.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    source, source_durations = gif_frames(fetch(SOURCE))
    normal, durations = sampled_fronts(source, source_durations)
    variants = {
        "normal": normal,
        "shiny": [shiny_frame(frame) for frame in normal],
    }
    timings = {variant: list(durations) for variant in variants}

    for variant, frames in variants.items():
        target = ANIM_DEST / variant
        target.mkdir(parents=True, exist_ok=True)
        for old in target.glob("*.png"):
            old.unlink()
        for index, frame in enumerate(frames, 1):
            write_png(frame, target / f"{index:03d}.png")
        suffix = "_shiny" if variant == "shiny" else ""
        write_png(frames[0], STATIC_DEST / f"mega_charizard_x_front{suffix}.png")

    back = transparent_crop(source[0], BACK_BOX)
    write_png(back, STATIC_DEST / "mega_charizard_x_back.png")
    write_png(
        shiny_frame(back),
        STATIC_DEST / "mega_charizard_x_back_shiny.png",
    )
    write_data(timings)
    print(
        f"installed {len(normal)} clean Mega Charizard X "
        "normal/shiny animation frames and static backs"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
