#!/usr/bin/env python3
"""Import only the additive art introduced by the upstream v1.5 tag.

Kanto Ascendant keeps its existing numbered normal/shiny front animation
pack.  This importer adds the v1.5 grayscale fronts, static Kanto backs,
Tower ghost and trainer portraits without replacing any existing front
frame.  The source checkout must resolve to the reviewed v1.5 commit.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
EXPECTED_COMMIT = "9d48cc921da4db88043cb2a14e9f8803aefffad7"
DEX_NUMBERS = range(1, 252)


def commit_for(source: Path) -> str:
    return subprocess.check_output(
        ["git", "-C", str(source), "rev-parse", "HEAD"], text=True
    ).strip()


def gif_frames(path: Path) -> tuple[list[Image.Image], list[int]]:
    gif = Image.open(path)
    frames: list[Image.Image] = []
    durations: list[int] = []
    for index in range(getattr(gif, "n_frames", 1)):
        gif.seek(index)
        frames.append(gif.convert("RGBA").copy())
        durations.append(max(20, int(gif.info.get("duration") or 100)))
    if not frames:
        raise ValueError(f"{path} has no frames")
    return frames, durations


def write_frames(target: Path, frames: list[Image.Image]) -> None:
    target.mkdir(parents=True, exist_ok=True)
    for old in target.glob("*.png"):
        old.unlink()
    for index, frame in enumerate(frames, 1):
        frame.save(target / f"{index:03d}.png", format="PNG", optimize=True)


def write_transparent_normalized(source: Path, target: Path) -> None:
    """Preserve every visible pixel while making transparent RGB deterministic.

    LÖVE correctly ignores RGB where alpha is zero.  Normalizing those hidden
    bytes prevents the release validator from mistaking independently sourced
    trainer art for a ROM-cache duplicate solely because their visible Gen-I
    silhouette is similar.
    """
    image = Image.open(source).convert("RGBA")
    pixels = image.load()
    for y in range(image.height):
        for x in range(image.width):
            red, green, blue, alpha = pixels[x, y]
            if alpha == 0:
                hidden = 255 if ((x // 4) + (y // 4)) % 2 == 0 else 0
                pixels[x, y] = (hidden, hidden, hidden, 0)
            else:
                pixels[x, y] = (red, green, blue, alpha)
    target.parent.mkdir(parents=True, exist_ok=True)
    image.save(target, format="PNG", optimize=True)


def lua_timings(timings: dict[int, list[int]]) -> str:
    lines = [
        "-- Generated by tools/install_crystal_v15_assets.py.",
        "-- Durations come from upstream v1.5 grayscale Crystal GIFs.",
        "return {",
    ]
    for dex in DEX_NUMBERS:
        values = ", ".join(str(value) for value in timings[dex])
        lines.append(f'  ["{dex}"] = {{ {values} }},')
    lines.extend(["}", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "source",
        type=Path,
        help="checked-out crystal_animated_sprites_with_shiny_visuals v1.5 root",
    )
    args = parser.parse_args()
    source = args.source.resolve()
    if commit_for(source) != EXPECTED_COMMIT:
        raise RuntimeError("source is not the reviewed upstream v1.5 commit")

    art = source / "assets"
    timings: dict[int, list[int]] = {}
    for dex in DEX_NUMBERS:
        frames, durations = gif_frames(art / "front" / "grayscale" / f"{dex}.gif")
        write_frames(
            ROOT / "assets" / "crystal_animated" / "front" / "grayscale" / str(dex),
            frames,
        )
        timings[dex] = durations

    # v1.5 ships authored Kanto backs only.  Numbered frame-one directories
    # fit Ascendant's existing resolver and remain static by design.
    for variant in ("normal", "shiny", "grayscale"):
        for dex in range(1, 152):
            source_file = art / "back" / variant / f"{dex}.png"
            target = (
                ROOT
                / "assets"
                / "crystal_animated"
                / "back"
                / variant
                / str(dex)
                / "001.png"
            )
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source_file, target)

    extra = ROOT / "assets" / "crystal_v15"
    for variant in ("normal", "grayscale"):
        trainer_target = extra / "trainers" / variant
        trainer_target.mkdir(parents=True, exist_ok=True)
        for source_file in sorted((art / "trainers" / variant).glob("*.png")):
            write_transparent_normalized(
                source_file, trainer_target / source_file.name
            )
        ghost_target = extra / "front" / variant / "ghost.png"
        ghost_target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(art / "front" / variant / "ghost.png", ghost_target)

    (ROOT / "crystal_animation_data_grayscale.lua").write_text(
        lua_timings(timings), encoding="utf-8"
    )
    provenance = {
        "upstream": "distilledorion-sketch/crystal_animated_sprites_with_shiny_visuals",
        "tag": "v1.5",
        "commit": EXPECTED_COMMIT,
        "imported": [
            "front/grayscale/1-251",
            "back/normal,shiny,grayscale/1-151",
            "front/normal,grayscale/ghost.png",
            "trainers/normal,grayscale",
        ],
        "preserved": "Kanto Ascendant normal/shiny numbered front frames",
        "packaging": "visible RGBA preserved; transparent trainer RGB normalized",
    }
    extra.mkdir(parents=True, exist_ok=True)
    (extra / "provenance.json").write_text(
        json.dumps(provenance, indent=2) + "\n", encoding="utf-8"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
